### ISSUE TITLE
Safari Microphone enable issue

### ISSUE THREAD

**Issue by Alex-YddeR** [edumeet/edumeet#1004]
**Describe the bug**
1. Mac OS Version: 12.3.1
2. Safari Version: Version 15.4 (17613.1.17.1.13)
3. Demo Link : https://letsmeet.no

**To Reproduce**
1. Go to Safari browser https://letsmeet.no
4. Join the session with at-least 2 participants
5. Try to enable and disable microphone

**Expected behavior**
Mic should get enabled and voice should be audible

**Console Error**
A MediaStreamTrack ended due to a capture failure

**Demo URL:**
https://letsmeet.no

**Client:**
 - Browser : safari,
 - Browser version : Version 15.4 (17613.1.17.1.13)

Thanks
Alex

**Comment by Alex-YddeR** [comment]
Hi Team,

Anything on the above scenario.

Thanks

**Comment by Alex-YddeR** [comment]
Dear Team

Any update on the above issue

Thanks
Alex

**Comment by Alex-YddeR** [comment]
Dear Team,

Any update

**Comment by stemcc** [comment]
Are you still seeing this issue on Safari 15.5?

**Comment by Alex-YddeR** [comment]
Yes.
