### ISSUE TITLE
Issue with bluetooth devices for android and IOS.

### ISSUE THREAD

**Issue by Alex-YddeR** [edumeet/edumeet#1015]
Dear Team,

1. for IOS devices when connected with bluetooth and joined muting audio, we don't hear the voice of other users until unmute.
2. for Android users they cant hear any voice in bluetooth headset, but when device disconnected we hear from mobile phone but not on speaker.

Tested on https://letsmeet.no and develop branch same issue

Thanks
Alex

**Comment by Astagor** [comment]
The whole mobile audio thing is strange, I think on Chrome and Android the audio input and output devices are switched. See my post [https://stackoverflow.com/questions/60994113/android-mobile-browser-navigator-mediadevices-enumeratedevices-method-returns/73419325#73419325](url). @Alex-YddeR have you tried FF on Android? For me in FF on Android by BT headset works.

**Comment by Astagor** [comment]
@havfo @misi the same happens also in Whereby and others.
