### ISSUE TITLE
Issue in mediasoup version

### ISSUE THREAD

**Issue by Alex-YddeR** [edumeet/edumeet#1018]
Dear Team,

With the development branch we could not install node modules since mediasoup version is having problems. below is the error we are getting

FAILED: subprojects/libuv-v1.43.0/libuv.a.p/src_unix_stream.c.o 

Platform: ubuntu
Version: Ubuntu 20.04.3 LTS
Codename:	focal

Thanks
Alex

**Comment by havfo** [comment]
This should be fixed by updating the mediasoup version.
