### ISSUE TITLE
drag and drop file upload

### ISSUE THREAD

**Issue by nullaegy** [edumeet/edumeet#1033]
share file button is not accepting drag and drop upload, it would be a nice feature.

**Comment by havfo** [comment]
Active development on the client is happening in the new client repository that you can find here: https://github.com/edumeet/edumeet-client

That new client supports drag and drop. If you want to use the new client with the old server you need to check out the `havfo/old-room-server` branch and drop the build output into the usual place in the server. If you want to use the new room-server it is located here: https://github.com/edumeet/edumeet-room-server

And that also needs at least one media-node that you can find here: https://github.com/edumeet/edumeet-media-node
