### ISSUE TITLE
Frequent joining and quitting meetings will cause the memory of chrome browser to continue to grow

### ISSUE THREAD

**Issue by bingofree2015** [edumeet/edumeet#1045]
I used two machines to open the chrome browser and join the same conference room. One machine (Machine A) observed the changes in memory, and the other machine (Machine B) frequently joined and exited the conference through automated testing tools, with a frequency of 1 second. This lasted about 5 hours

The browser memory of machine A continues to grow from 113.347K to 497.890K. If it lasts for about 24 hours, the browser memory may grow to more than 1G, causing the browser to crash.

**Comment by havfo** [comment]
Are you testing with the client in this repo, or the new client here: https://github.com/edumeet/edumeet-client
