### ISSUE TITLE
Settings to run locally

### ISSUE THREAD

**Issue by eryson** [edumeet/edumeet#1056]
**Describe the bug**
I'm having some problems running the project locally, after running the project, and clicking to enter a room, the socket has SSL errors.

**To Reproduce**
1. Clone project.
2. Build application
```bash
cd app
yarn && yarn build

cd ../server
yarn && yarn build
```
3. Run application
```bash
cd server
sudo DEBUG=* yarn start

cd ../app
yarn start
```
4. Click to enter the room.

**Expected behavior**
Be able to run the project locally and join a room.

**Screenshots**
Before entering the room:
![image](https://user-images.githubusercontent.com/8783173/226417867-576171cb-1c2d-427d-95ad-a70346ec1068.png)

After clicking to enter the room:
![image](https://user-images.githubusercontent.com/8783173/226418156-14511cfc-3501-4743-a129-0f04468a0498.png)

**Branch/Versions:**
Running the master branch of the project (version: "3.5.5").
Node: v16.17.0
Yarn: v1.22.19

**Server (if available please complete the following information):**
 - OS: Ubuntu 22.04.2 LTS

**Client:**
 - Browser: Chrome
 - Browser version: 111.0.5563.64 (Official Build) (64-bit)

**Additional context**
.env:
```bash
NODE_ENV="development"
REACT_APP_VERSION=$npm_package_version
REACT_APP_NAME=$npm_package_name
```
app/src/config.ts
```bash
// Changed developmentPort.default to:
default : 8889

// Changed serverHostname.default to:
default  : '127.0.0.1'
```

app/public/config.js
```bash
// Changed config.developmentPort to:
default : 8889

// Changed config.serverHostname to:
default  : '127.0.0.1'
```

server/config/config.yaml
```bash
listeningPort: 443
listeningHost: localhost

fileTracker: "wss://tracker.openwebtorrent.com"

tls:
  cert: ./certs/edumeet-demo-cert.pem
  key:  ./certs/edumeet-demo-key.pem

turnAPIURI: "stun:stun.l.google.com:19302"
turnAPIKey: "examplekey"

backupTurnServers: 
- urls: 
  - "stun:stun.l.google.com:19302?transport=tcp"
  # username: "Your username"
  # credential: "Your's credential"

redisOptions:
  host: "127.0.0.1"                                                                                                                                                                  
  port: "6379"            
  # password: "_REDIS_PASSWORD_"

prometheus:
  enabled: true
  deidentify: true
  numeric: true
  listen: localhost
   
mediasoup:
  webRtcTransport:
    listenIps:
    - ip: ""
      announcedIp: ""
```

Server log:
[server_log.txt](https://github.com/edumeet/edumeet/files/11021343/server_log.txt)

**Comment by N7Remus** [comment]
When runing localy you have to accept the certificate manualy.
On the network tab if you click the wws://<address> and revrite it to https://<address> so you can accept it .
