### ISSUE TITLE
edumeet4 - recording, transcribing feature not available in Firefox

### ISSUE THREAD

**Issue by axel-rank** [edumeet/edumeet#1083]
https://edumeet-v4-demo.geant.org/vcc

Chromium
![chromium](https://github.com/edumeet/edumeet/assets/12480617/befe93a9-1c3e-415f-b578-ef40f0d10a7a)

Firefox
![firefox](https://github.com/edumeet/edumeet/assets/12480617/0041290f-872b-44f6-8b6f-31108844a751)

**Comment by havfo** [comment]
This is intentional as Firefox does not support the APIs we are using for these features.
