### ISSUE TITLE
Certificate not generated

### ISSUE THREAD

**Issue by pashajanx** [edumeet/edumeet#1086]
Hi, running the script does not create a certificate

Certbot failed to authenticate some domains (authenticator: webroot). The Certificate Authority reported these problems:
Domain: mydomin
Type: connection
Detail: 138.*.0: Fetching http://mydomin.well-known/acme-challenge/UDK_b86JeDZdo8hAToHYSg27vh86inEHADHCXHqR6es: Connection refused

**Comment by havfo** [comment]
Make sure port 80/tcp is open and not pointed to some other service on the host.
