### ISSUE TITLE
Your web application in the background on android web view.

### ISSUE THREAD

**Issue by eshpilevsky** [edumeet/edumeet#1100]
Good afternoon, please tell me how I can make an Android web view application, that it in the background can transmit video on your application? very need to realize it, please help! In the Browser, if you minimize the application, the video transmission is interrupted.

**Comment by N7Remus** [comment]
I think that this is a security/privacy feature of android.
We do not do android development, but you would have to lock in permissions for camera and simply run edumeet as a simple website inside your application.
