### ISSUE TITLE
Resolution don't change on setting page

### ISSUE THREAD

**Issue by misi** [edumeet/edumeet#113]
![chrome-capture](https://user-images.githubusercontent.com/311629/69425148-ad917500-0d2a-11ea-9529-3c846aa464e7.gif)

**Comment by misi** [comment]
mm: develop git version
google Chrome: 78.0.3904.108 (Hivatalos verzió) (64 bites) linux

**Comment by misi** [comment]
It happens only if you have multiple webcams.

**Comment by havfo** [comment]
Fixed in new client
