### ISSUE TITLE
Local recording

### ISSUE THREAD

**Issue by misi** [edumeet/edumeet#212]

**Comment by mackostr** [comment]
maybe we can consider this recording API?:
https://w3c.github.io/mediacapture-record/MediaRecorder.html
example:
https://webrtc.github.io/samples/src/content/getusermedia/record/

**Comment by cap19** [comment]
This would be a very valuable enhancement in a class room setting as well as other use cases.

**Comment by divy-work** [comment]
This will make it a complete video confrencing solution!

**Comment by cap19** [comment]
Just wondering if this one this one is still on the roadmap?

**Comment by christian-2** [comment]
IMO this feature should come with a visual indicator that makes it clear to all participant when recording occurs (inside the tool; applies also to #327).

**Comment by verbavolant** [comment]
@misi 
it would be, on a monitor less server:
- install chrome ( https://github.com/jitsi/jibri )
- install xvfb: apt-get install xvfb
- install alsa with a sound loop
then start chrome
 xvfb-run -a --server-args="-screen 0 1280x800x24 -ac -nolisten tcp -dpi 96 +extension RANDR" google-chrome --console --no-first-run --user-data-dir=$HOME/.config/chrome-test --use-fake-device-for-media-stream --use-file-for-fake-video-capture=/tmp/testvideo.y4m --enable-logging --v=1 --vmodule=*third_party/libjingle/*=3,*=0 https://multiparty.test.com/room123

but i need to enter directly into the room...

**Comment by havfo** [comment]
Fixed in new client
