### ISSUE TITLE
Simulcast for screen sharing not working

### ISSUE THREAD

**Issue by Astagor** [edumeet/edumeet#214]
I did some experimentation with simulcast for screen sharing and if the config you set:
simulcastSharing   : true,
The screen sharing is not working. The client gets undefined undefined instead of  the current layers.
See screen shot.
![image](https://user-images.githubusercontent.com/11389003/79455791-b3e00080-7fed-11ea-8150-2a4ccb14b064.png)

With simulcastSharing   : false, it works fine. 
Simulcast on normal video also works fine.

**Comment by Astagor** [comment]
I did some more testing and sometimes it works but 8 out of 10 times it doesn't. Tested in current Chrome. With simulcastSharing set to false it always works.

**Comment by havfo** [comment]
There is in general issues with simulcast in screen sharing. We might want to disable the option until browsers support it properly.

**Comment by Astagor** [comment]
Yeah, maybe just put a comment in config, that currently the simulcast for screen sharing should be left on false.
