### ISSUE TITLE
Help to install

### ISSUE THREAD

**Issue by wtitec** [edumeet/edumeet#217]
I tried to do the installation but I couldn't.  how to install and how to adjust the HTTPS configuration and create the stun server?

**Comment by Astagor** [comment]
Please give more details. What has failed by the installation? What OS?

**Comment by utkarshdubey** [comment]
@Astagor You have any idea about how do I generate a custom SSL certificate using Let'sencrypt?

**Comment by Astagor** [comment]
Have a look here:
[https://www.digitalocean.com/community/tutorials/how-to-use-certbot-standalone-mode-to-retrieve-let-s-encrypt-ssl-certificates-on-ubuntu-1804](url)

Then in server/config/config.js put:

`	tls          :
	{
		cert : `/etc/letsencrypt/live/YOUR_DOMAIN.COM/fullchain.pem`,
		key  : `/etc/letsencrypt/live/YOUR_DOMAIN.COM/privkey.pem`
	},`

**Comment by utkarshdubey** [comment]
Aight thanks, I have yet another question: How do I change the title from Multiparty Meeting to something I like.. I can't find the Layout.js or some file like that @Astagor

**Comment by misi** [comment]
@utkarshdubey 
copy config.example.js to config.js 
modify this line in your config.js :https://github.com/havfo/multiparty-meeting/blob/effdd3005b9641d1d503d70af064eab0a9c550a8/app/public/config/config.example.js#L48
and after you modified run in the app directory the `npm run build`

**Comment by misi** [comment]
@wtitec  See coturn.net for stun/turn server.

**Comment by utkarshdubey** [comment]
> @utkarshdubey
> copy config.example.js to config.js
> modify this line in your config.js :
> 
> https://github.com/havfo/multiparty-meeting/blob/effdd3005b9641d1d503d70af064eab0a9c550a8/app/public/config/config.example.js#L48
> 
> 
> and after you modified run in the app directory the `npm run build`

Already did that, yet it shows the title as Multiparty meeting. Clearance: I'm talking about the Webpage's title.

**Comment by Astagor** [comment]
Modify app/public/index.html and rebuild app.

**Comment by utkarshdubey** [comment]
> Have a look here:
> [https://www.digitalocean.com/community/tutorials/how-to-use-certbot-standalone-mode-to-retrieve-let-s-encrypt-ssl-certificates-on-ubuntu-1804](url)
> 
> Then in server/config/config.js put:
> 
> `tls : { cert :`/etc/letsencrypt/live/YOUR_DOMAIN.COM/fullchain.pem`, key : `/etc/letsencrypt/live/YOUR_DOMAIN.COM/privkey.pem` },`

Since ports 80/443 are already in use by the application. It is a problem generating the certificates, for that I dug deep and found that I'd have to use something called ``--webroot``, but it isn't solving my problem either. Do you have a proper command list to achieve what I want?

**Comment by Astagor** [comment]
So what is on 80 and 443?

**Comment by utkarshdubey** [comment]
@Astagor I think it's nginx.

**Comment by utkarshdubey** [comment]
@Astagor I've just deployed your app as a service.

**Comment by misi** [comment]
stop the app until you run cert validation...

**Comment by utkarshdubey** [comment]
But again, the cert validation requires a webpage to be live at an address. What will I show until then?

**Comment by wtitec** [comment]
Complementing the question. Due to the pandemic, I need to build a service to teach classes online.
What hardware specifications, OS, and bandwidth are needed for 30 people?

**Comment by utkarshdubey** [comment]
@wtitec I'd suggest you may want to go with a popular cloud hosting service such as Digital Ocean, Linode, etc.. Moreover you can host it on your own servers as well if you know what you're doing.
For the specifications:-
1) Any Linux distro should be perfect.
2) You can easily host a 30 people meeting environment with a 5$ DO droplet.

Visit the link below for more information on the specifications of the 5$ droplet:
https://www.digitalocean.com/pricing/

**Comment by misi** [comment]
> ut again, the cert validation requires a webpage to be live at an address. What will I show until then?

certbot will run a webserver, with the needed info during cert signing challenge check.

**Comment by utkarshdubey** [comment]
Yeah already done the requires, thanks.

**Comment by roman-drozd-it** [comment]
Seems to be resolved. No new responses much over 1 mounth.
