### ISSUE TITLE
Set peers audio level (gain control)

### ISSUE THREAD

**Issue by misi** [edumeet/edumeet#235]

**Comment by bristow** [comment]
Thanks for your software, it's amazing !

I have some malfunctions with smartphones. The sound (not the microphone) is too low and users can't hear conversations well. Is it related to this issue?

**Comment by misi** [comment]
@bristow  I think this issue is more about different mic levels and when playing out we need to somehow equalize this.

**Comment by so010** [comment]
Should be not a problem anymore:
- autoGain is default now
- audiolevel is adjustable on receiver side for each participant individually
- audio level indicators should help the user to identify the problem
