### ISSUE TITLE
Cannot understand the error

### ISSUE THREAD

**Issue by hdavy2002** [edumeet/edumeet#238]
I am using the ansible way and this is what I get. I am unable to figure it out.

fatal: [li2180-200.members.linode.com]: FAILED! => {"reason": "no action detected in task. This often indicates a misspelled module name, or incorrect module path.\n\nThe error appears to have been in '/root/mm-ansible/roles/mm/tasks/mm.yml': line 58, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: tear down existing services\n  ^ here\n"}

fatal: [li1984-226.members.linode.com]: FAILED! => {"reason": "no action detected in task. This often indicates a misspelled module name, or incorrect module path.\n\nThe error appears to have been in '/root/mm-ansible/roles/mm/tasks/mm.yml': line 58, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: tear down existing services\n  ^ here\n"}

**Comment by cap19** [comment]
I got stuck at the exact same step with the same error message... The error appears to have been in '/root/mm-ansible/roles/mm/tasks/mm.yml': line 58, column 3

Couldn't figure it out... Both, docker and manual install worked fine for me.

**Comment by hdavy2002** [comment]
Thats the statement starting from line 58

- name: tear down existing services
  become: yes
  docker_compose:
    project_src: "{{ deployment_directory}}"
    state: absent
  when: oldmm_dir.stat.exists and oldmm_dir.stat.isdir
  ignore_errors: yes

**Comment by misi** [comment]
You should ignore this error

**Comment by misi** [comment]
It is only delete the previous instance if exists if not then it tires abut fails because this is the first time installation. You are right I can make it more intelligently, but it was fast quick and dirty solution. Thanks for reporting it. I will fix it later..

**Comment by misi** [comment]
Which operating system and version @cap19  hdavy2002 did you use?

**Comment by hdavy2002** [comment]
I was using Debian 10. I can try Ubuntu 18.04 LTS today. I am using a VPS from Linode.

**Comment by cap19** [comment]
I got the error while using Ubuntu 18.04 LTS.

**Comment by misi** [comment]
I will check it ASAP. Sorry for the delay!
