### ISSUE TITLE
support hosting below root of website

### ISSUE THREAD

**Issue by nlgranger** [edumeet/edumeet#249]
Hosting the server behind a reverse proxy in a subdirectory doesn't seem to work.
For instance, when opening https://www.example.com/meeting/someroomname the room id is `meeting` and trying to open it triggers requests to https://www.example.com/socket.io/?peerId=lhdf2khd&roomId=meeting&EIO=3&transport=polling&t=N6YMh7j instead of https://www.example.com/meeting/socket.io/?peerId=lhdf2khd&roomId=meeting&EIO=3&transport=polling&t=N6YMh7j

**Comment by Astagor** [comment]
I have the problem with this too, would make life much easier.

**Comment by Astagor** [comment]
What was the problem here?

**Comment by Astagor** [comment]
Is this done? I cannot get it to work.
In your last commit  https://github.com/havfo/multiparty-meeting/commit/2373bf44d8733e101d0f8cec4c948290d893cc91 there is the line in server.js 
	io = require('socket.io')(mainListener, { path: '/' });
But in the current developer branch it is
	io = require('socket.io')(mainListener);
@havfo

**Comment by havfo** [comment]
It has been removed on purpose. The path needs to be syncronized in server and client, and I couldn't find a nice way of doing that apart from having a config on both client and server that is equal. Didn't get the time to properly test for bugs before 3.3.

**Comment by Astagor** [comment]
OK. So I'll wait. Thanks.
