### ISSUE TITLE
Bandwidth and framerate

### ISSUE THREAD

**Issue by atygr** [edumeet/edumeet#254]
Hello. How can I set up the maximum possible bandwidth and framerate for my metting's video? Which files and parameters should be changed?
I tried to set the following parameters:

server/config.js
`
...
{
	kind       : 'video',
	mimeType   : 'video/VP8',
	clockRate  : 90000,
	parameters :
	{
		'x-google-start-bitrate' : 18000,
		'x-google-min-bitrate' : 10000,
		'x-google-max-bitrate' : 24000,
		'b' : 'AS:10000',
		'max-br' : '12000'
	}
}
...
initialAvailableOutgoingBitrate        : 18000000, 
minimumAvailableOutgoingBitrate  : 14000000, 
maxIncomingBitrate                        : 14000000 
`

app/config.js

`
...
defaultResolution  : 'high',
...
simulcastEncodings :
	[
		{ scaleResolutionDownBy: 1, maxBitrate: 15000000, maxFramerate: 60 },
		{ scaleResolutionDownBy: 1, maxBitrate: 15000000, maxFramerate: 60 },
		{ scaleResolutionDownBy: 1, maxBitrate: 15000000, maxFramerate: 60 }
	],`

app/RoomClient.js
...
`codecOptions :
	{
              videoGoogleStartBitrate : 12000
	},`

But it doesn't help and the video doesn't have a high enough bitrate - (it 3-4Mb, ~15fps)

**Comment by havfo** [comment]
The most important variable to change is in `server/config/config.js`:
`maxIncomingBitrate: 2000000`

This is the maximum bandwidth the client is allowed to send to the server.

**Comment by atygr** [comment]
Thanks havfo. I set this parameter to 14000000. How else can I try to force use of a certain bitrate?

**Comment by havfo** [comment]
From your `config.js` it seems you have `simulcast` enabled. If that is the case, you need to change your simulcast encodings. At the moment you send 3 full resolution streams to the server. Either disable `simulcast` or remove all but one encoding.

**Comment by atygr** [comment]
Thanks for the tip, I've already disabled simulcast.

**Comment by havfo** [comment]
Try adding `'frameRate': 60` to the different resolutions in `VIDEO_CONSTRAINS` in `RoomClient.js`

**Comment by atygr** [comment]
The video starts to go in good quality, but then the resolution starts to decrease.

**Comment by atygr** [comment]
Сan you give advice on how to determine the bottleneck (client settings, websoup server settings, turn server settings, hardware restrictions)?
