### ISSUE TITLE
Service ramdomly crashed with error 'ERR_MULTIPLE_CALLBACK();'

### ISSUE THREAD

**Issue by elgfon** [edumeet/edumeet#255]
Hi,

The service crashes from time to time either with the latest stable version (3.2.1) or with the master branch.
I've got the same error, but I can't find out where it occurs. It is very unpredictable, either the service fails in a few seconds after startup or it can lasts more than 1 hour and half without any issue reported by my users.

The common pattern is the service fails with this same error (the path `/srv/multiparty-meeting/` and `/srv/multiparty-meeting-3.2.1` are where the server files are located):
```
_stream_writable.js:415                   
    throw new ERR_MULTIPLE_CALLBACK();               
    ^

Error [ERR_MULTIPLE_CALLBACK]: Callback called multiple times
    at onwrite (_stream_writable.js:415:11)
    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:87:12)
    at Immediate._onImmediate (/srv/multiparty-meeting/server/node_modules/handle-thing/lib/handle.js:127:11) 
    at processImmediate (internal/timers.js:456:21)
    at process.topLevelDomainCallback (domain.js:137:15) {
  code: 'ERR_MULTIPLE_CALLBACK'              
} 
```

I'm running nodejs  version 13.13.0 and using npm version 6.14.4.

I tried to set `numWorkers : 1` in `server/config/config.js` as a workaround in case of race conditions due to multiple workers, but I still get the same failure.

Here is an extract of the logs when the server is started with `systemd` and has encountered multiple crashes since its initial startup:
```
Apr 23 12:37:18 mpm systemd[1]: multiparty-meeting.service: Scheduled restart job, restart counter is at 24.
Apr 23 12:37:18 mpm systemd[1]: Stopped multiparty-meeting is a audio / video meeting service running in the browser and powered by webRTC.
Apr 23 12:37:18 mpm systemd[1]: Started multiparty-meeting is a audio / video meeting service running in the browser and powered by webRTC.
Apr 23 12:37:19 mpm server.js[20864]: - process.env.DEBUG: undefined
Apr 23 12:37:19 mpm server.js[20864]: - config.mediasoup.logLevel: undefined
Apr 23 12:37:19 mpm server.js[20864]: - config.mediasoup.logTags: undefined
Apr 23 12:37:19 mpm server.js[20864]: (node:20864) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated
Apr 23 12:37:27 mpm server.js[20864]: _stream_writable.js:415
Apr 23 12:37:27 mpm server.js[20864]:     throw new ERR_MULTIPLE_CALLBACK();
Apr 23 12:37:27 mpm server.js[20864]:     ^
Apr 23 12:37:27 mpm server.js[20864]: Error [ERR_MULTIPLE_CALLBACK]: Callback called multiple times
Apr 23 12:37:27 mpm server.js[20864]:     at onwrite (_stream_writable.js:415:11)
Apr 23 12:37:27 mpm server.js[20864]:     at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:87:12)
Apr 23 12:37:27 mpm server.js[20864]:     at Immediate._onImmediate (/srv/multiparty-meeting-3.2.1/server/node_modules/handle-thing/lib/handle.js:127:11)
Apr 23 12:37:27 mpm server.js[20864]:     at processImmediate (internal/timers.js:456:21)
Apr 23 12:37:27 mpm server.js[20864]:     at process.topLevelDomainCallback (domain.js:137:15) {
Apr 23 12:37:27 mpm server.js[20864]:   code: 'ERR_MULTIPLE_CALLBACK'
Apr 23 12:37:27 mpm server.js[20864]: }
Apr 23 12:37:27 mpm systemd[1]: multiparty-meeting.service: Main process exited, code=exited, status=1/FAILURE
Apr 23 12:37:27 mpm systemd[1]: multiparty-meeting.service: Failed with result 'exit-code'.
```

Any idea how to find out ? Thanks !

**Comment by havfo** [comment]
I have commited somthing that hopefully fixes this.

**Comment by mi4aux** [comment]
error remains ... running up2date develop-branch with fix commit (45a89b9) included

**Comment by havfo** [comment]
Could you please verify if you had commit 7e9160927684e85d73ab41dcf8359b1ce7f42617 included?

**Comment by mi4aux** [comment]
commit 7e91609 not included (missed by a hour)
updated now ... will give feedback if error occurs again

**Comment by mi4aux** [comment]
error is still there ... 
if it relevant / useful info - noticed crash after crash on this use-case:
8 users over 6 rooms, 2 of them in all 6 rooms and 1 user/room tried to share screen.
not when same 8 users are splitted over 2 rooms, 2 of them in all 2 and 3 screenshare / room.

**Comment by havfo** [comment]
I'm not sure I understand the use-case.

You have 6 rooms with 8 users pr. room, in total 48 users?

Two users pr. room share screen at the same time, in total 12 users sharing screen at the same time?

Which Node version are you running?

**Comment by mi4aux** [comment]
just 8 users in total, distributed over 6 rooms ... 6 users only in 1 room, 2 users in all 6 rooms
in each room just 1 user sharing screen (or trying ... there the repeated crash happened)

nodejs 13.13.0

**Comment by havfo** [comment]
Thank you, I will try to reproduce this.

**Comment by misi** [comment]
Use nodejs 10.x to avoid it temporary. According my experience it do not occour with 10.x. 
We still investigate the issue.

**Comment by misi** [comment]
I reverted all docker images to node 10.x
