### ISSUE TITLE
Regarding stats fo rooms and peers etc

### ISSUE THREAD

**Issue by nareshinstavc** [edumeet/edumeet#259]
How do i see stats in MM session.? Do i have to enable user login ?

**Comment by misi** [comment]
We not yet implemented detailed stats on the interface.

**Comment by divy-work** [comment]
@misi Just an idea, why not use a database to store stats regarding meetings. Maybe kind of a meeting log, with details about its start and end, etc.

I can create a PR if needed.

**Comment by misi** [comment]
We are speaking about web app detailed stats frontend stats here, if i am right. If we speak about server logs see in development branch StatusLogger: https://github.com/havfo/multiparty-meeting/blob/cb5f4cd48eb0be3c844705eeebf6a6d950d75fcb/server/config/config.example.js#L84

**Comment by christian-2** [comment]
FYI the new Prometheus exporter (see `prom.md` in branch `develop`) reports the numbers of rooms (`edumeet_rooms`) and peers (`sum(edumeet_peers`) into a (time series) database.
