### ISSUE TITLE
Enter room directly + Room API

### ISSUE THREAD

**Issue by huzaifahj** [edumeet/edumeet#277]
I'm wondering if there's a way to go directly into the video call session, without the lobby screen. This is because I want to embed the call directly into an app. So don't enable audio/video and just join the call, the user can then enable it after.

Further to that, are you planning to implement a sort of simple API? A bit like the Jitsi external API, which is much easier to follow than mediasoups demo code and has simple functions (e.g. mute()).

Great work though. I think it's the first usable mediasoup demo I've seen.

**Comment by havfo** [comment]
There is no way of entering directly no, but this is something we have discussed previously and is something we can add. The simplest would be to have a URL parameter, `enter=true` or something like that.

We have also discussed having a sort of room API, but there has so far not been time to develop this. It is something we want to have at some time in the future.

Much appreciated! If you have any input or want to contribute in some way, don't hesitate to contact us.

**Comment by huzaifahj** [comment]
I understand, the URL parameter would be great!

Can I also ask, what is browser support like? Does it work on Safari and Firefox?

**Comment by havfo** [comment]
Supported browsers are:
Chromium based
Firefox
Safari (no screen sharing)
MS Edge (both new and old)

**Comment by havfo** [comment]
To have video between all these, make sure to configure a codec that all of them support. A safe bet is VP8. If you can exclude Safari, VP9 is preferable.

**Comment by huzaifahj** [comment]
That's perfect! I really want to use this instead of Jitsi, browser support is so patchy.

**Comment by cap19** [comment]
> Supported browsers are:
> Chromium based
> Firefox
> Safari (no screen sharing)
> MS Edge (both new and old)

Does screen share work for MS Edge?

On Win 10, Microsoft Edge 44.18362.449.0, Microsoft EdgeHTML 18.18362 the screen share button is disabled for me.

**Comment by cap19** [comment]
Also, camera does not work in MS Edge. Is that a known issue or something to do with my Edge version?

**Comment by havfo** [comment]
> > Supported browsers are:
> > Chromium based
> > Firefox
> > Safari (no screen sharing)
> > MS Edge (both new and old)
> 
> Does screen share work for MS Edge?
> 
> On Win 10, Microsoft Edge 44.18362.449.0, Microsoft EdgeHTML 18.18362 the screen share button is disabled for me.

I commited 65f47d4b8dfd9f5ae4ba3dce3dd26e6b5fb97b53 that fixes screen sharing on MS Edge

**Comment by cap19** [comment]
On letsmeet.no I get an error while screen sharing in MS Edge. Not sure if the commit made it's way there...

![mm1](https://user-images.githubusercontent.com/63865380/81072780-49afd280-8eac-11ea-96fa-0af732de8f62.png)

**Comment by havfo** [comment]
I don't have the old MS Edge to test with at the moment. Will have to come back to this later.
