### ISSUE TITLE
Problem with overRoomLimit

### ISSUE THREAD

**Issue by Astagor** [edumeet/edumeet#297]
Yes, there is a problem with my own commit. #293 
I don't know how to best fixed it.

The problem: 
- the overRoomLimit checks the limit when a user clicks join and displays an message that the room limit is reached. So far so good.
- but if now the user clicks join for a second time, the server knows already this peerId, as it has already tried once to join the room and the hijack session if kicks the peer out.

So I have the following approaches to fixing it:
- do not display the message on the dialog but reload the whole page with roomId set 
`window.location = '/this_.roomId'`

- some how reset the roomClient, like it is being inited in index.js

- add a session token in RoomClient, so it has it, but then the server closes and old peer when returning and creates a new one, which causes the RoomClient to reload to '/'.

I'm a bit lost here, as it is again on the border on http requests and having a socket connection

**Comment by so010** [comment]
Can I ask about what is actually the use case for this option?

**Comment by havfo** [comment]
In case you have limited server capacity, but still want to have a local installation.

**Comment by Astagor** [comment]
Yes, to prepare rooms with dynamic maxLastN and uses per room. I have rooms for max 20 users and they have maxLastN set 10. I have rooms for 100 users, but then these rooms have maxLastN set to 2. This way I make sure that nobody overloads the server. As I have fixed rooms, I control how many users are per server.
