### ISSUE TITLE
Simulcast order question

### ISSUE THREAD

**Issue by Astagor** [edumeet/edumeet#319]
One question, does the order have importance on the simulcastEncodings?
	simulcastEncodings :
	[
		{ scaleResolutionDownBy: 1 },
		{ scaleResolutionDownBy: 1.1 },
		{ scaleResolutionDownBy: 1.5 }
	],

Is there a weight parameter?

Even if I'm on a symmetric 100Mbps network, often the browser does not use the maximum quality. That is why I have the 1.1 value, as usually it is the second-best it uses.

**Comment by havfo** [comment]
The order needs to be correct, always order them by `scaleResolutionDownBy` in **descending** order. In your example that means that you must change them to the opposite order.

Ref: https://mediasoup.org/documentation/v3/mediasoup/rtp-parameters-and-capabilities/#Simulcast

**Comment by havfo** [comment]
Also remember that the encodings you listed here means that there will be sent 3 video streams of almost the same resolution. This is not very optimal. The reason to have simulcast is usually to enable clients with bad network or CPU to get a substantially smaller resolution stream that they can handle.

On letsmeet.no we use:
```
simulcastEncodings :
[
	{ scaleResolutionDownBy: 4 },
	{ scaleResolutionDownBy: 1 }
]
```

**Comment by Astagor** [comment]
OK, got that, but still, it is very often that the resolution gets locked at the lowest. And it does not go up anymore.
I have now
	simulcastEncodings :
	[
		{ scaleResolutionDownBy: 2 },
		{ scaleResolutionDownBy: 1.5 },
		{ scaleResolutionDownBy: 1 }
	],

Sending low resolution 320x240 ends up with 160x120 being shown. I have 100 Mbit connection.

**Comment by havfo** [comment]
Yes, so also, this is not constrained by your connection necessarily. All 3 streams need to fit into the bitrate `maxIncomingBitrate` specified in the server. If they don't, it will scale down.

In the example above you are sending the following streams:
```
0: 160x120
1: 213x160
2: 320x240
```

What is shown at the other end is also dependent on what that browser decides based on network and CPU.

**Comment by Astagor** [comment]
Yes, that is clear for me, but as I'm testing locally, it is a bit strange that not the highest resolution is shown. Also in the advanced info I get:
Current spatial-temporal layers: 1 1 (sometimes 1 0 or 0 1).
In the preferred is 2 2. I have never reached 2 2.

Normally I have
maxIncomingBitrate              : 1500000
but setting it to
maxIncomingBitrate              : 9500000
did not change a thing.

I have also observed the following
simulcastEncodings :
[
{ scaleResolutionDownBy: 4 },
{ scaleResolutionDownBy: 2 },
{ scaleResolutionDownBy: 1 }
],

camera set to medium, I get 320x240 (scale 2)
now i change camera to low, I get 80x60 (scale 4)
I change back to medium, , I get 320x240 (scale 2)

This is something I don't understand, just switching the camera resolution to lower, changes the scale rate in the wrong direction. That is why in my initial post I was trying to revert the order.

**Comment by Astagor** [comment]
What is more funny:
my config
simulcastEncodings :
[
{ scaleResolutionDownBy: 4 },
{ scaleResolutionDownBy: 2 },
{ scaleResolutionDownBy: 1 }
],
now I play only with the resolution setting of the sender, and the receiver I get:
I start in medium (640x480) - I get 320x240 (scale 2)
I change to low (320x200) - I get 80x60 (scale 4) it never goes up
i change to high (1280x720) - I get 320x180 (scale 4) for like 4 seconds and the I get 1280x720 (scale 1)

So something is NOT OK. Only when choosing higher resolution I get the lowest scale to be received.

**Comment by havfo** [comment]
This sounds weird... The order should always be descending. We would have to look at this more closely, but don't have time for it right now. Does simulcast behave correctly for you if you test on letsmeet.no ?

**Comment by Astagor** [comment]
At letsmeet.no  a bit different, but still strange:

I start in medium (640x480) - I get 640x480 (scale 1)
I change to low (320x240) - I get 80x60 (scale 4) it never goes up
i change to high (1280x720) - I get 320x180 (scale 4) for like 4 seconds and the I get 1280x720 (scale 1)

**Comment by Astagor** [comment]
I did one more test:
	simulcastEncodings :
	[
		{ scaleResolutionDownBy: 2},
		{ scaleResolutionDownBy: 1}
	],

I start in medium (640x480) - I get 640x480 (scale 1)
I change to low (320x240) - I get 160x120 (scale 2) it never goes up
I change to high (1280x720) - I get 640x360 (scale 2) for like 4 seconds and then I get 1280x720 (scale 1).

So in this configuration it works as expected for medium and high. For low it stays always at scale 2.

**Comment by so010** [comment]
I tested a little bit with chrome  and traffic analyze:
- medium (640x480) and high (1280x720) seems to work like expected from simulcast.
- low (320x240) looks like producer sends out ONLY the lowest stream 80x60to server (data rate producer to server  === data rate server to consumer)
- very high: consumer gets always lowest stream (scaleDownBy 4) with data rate around 170KiB/s and producer data rate shows is typical saw tooth pattern with max 265KiB/s 
- ultra: data rate producer to server  === data rate server to consumer and is scaled down by 4 

Interpretation
The problem with setting low is weird because there is no reason to limit to sending out lowest stream only. In setting high Chrome tries to ramb up to SEND higher quality streams but Chrome is limiting himself in total bandwidth to 265 KiB/s and the streams just don't fit in.
In setting ultra Chrome just decides that this will never happen and sends only lowest stream quality.

**Comment by Astagor** [comment]
Good, I thought I'm crazy. But not good, as this renders simulcast almost unusable. As many people with problems with their bandwidth set to low, and getting 80x60 is not an option when the view port is so large.

**Comment by Astagor** [comment]
I have changed in all my 3 deployments to:
simulcastEncodings :
[
{ scaleResolutionDownBy: 1.6},
{ scaleResolutionDownBy: 1}
],

So it works good for high and medium. For low you get then 200x150, which is ugly, but not unacceptable.

**Comment by so010** [comment]
This actually works quite good in Firefox, Firefox ESR and Chrome (not tested witch Edge and Safari yet)
"Ultra"-setting is for number fetish only and will only work if you switch of simulcast because browsers limit bandwidth to around 5.5 mbit/s in reality.

simulcastEncodings :
[		
    { maxBitRate: 50000 },
    { maxBitRate: 1000000 },
    { maxBitRate: 3800000 }
],

You can play around with the numbers but try to keep the sum under 5000000.

**Comment by so010** [comment]
Tested now with a beefy machine and it is actually working with higher data-rates as well.
Tested now with 12000000 maxIncomingBitrate in server-settings and
simulcastEncodings :
[
{ maxBitRate: 50000 },
{ maxBitRate: 1000000 },
{ maxBitRate: 10000000 }
],
This is somehow working even with "Ultra"-settings.

**Comment by Astagor** [comment]
Some new insights. Current version of dev.
	 simulcastEncodings :
	 [
	   	 { maxBitRate: 300000 },
		 { maxBitRate: 1000000 }
	 ],

I start in medium (640x480) - I get 640x480 (stats show sending: 1 Mbps)
I change to low (320x240) - I get 320x240 (stats show sending: 0,24 Mbps) and on the ME screen the red icon of bad connection appears. However on the receiver I have no icon of bad connection on the incoming video.

It seems that choosing low resolution, causes the sender browser to think that there are bandwidth/performance problems, as the red symbol appears on ME. If I switch to medium, the transfer goes up to 1 Mbps and the red symbol disapears.
