### ISSUE TITLE
OIDC Auth Issue

### ISSUE THREAD

**Issue by Alex-YddeR** [edumeet/edumeet#323]
Dear Team,

I have provided OIDC credentials in config and I can successfully login with.

but when I just enabled OIDC in config and now logged in to the application with out authentication. when I restart services or some how services restarted, clients are not able to login back automatically needs to refresh the page and login back manually

But above scenario is working fine when we comment Auth OIDC section in config

Below is the example config.
oidc:
                {
                        // The issuer URL for OpenID Connect discovery
                        // The OpenID Provider Configuration Document
                        // could be discovered on:
                        // issuerURL + '/.well-known/openid-configuration'

                        issuerURL     : 'https://dev-fdff.auth0.com/.well-known/openid-configuration',
                        clientOptions :
                        {
                                client_id     : 'S1uh8L6l5mf7T1I8ZJEMYekTWZvU',
                                client_secret : ‘fdfdfdsfdsfdsfdsf-Ez0To81',
                                scope                   : 'openid email profile',
                                // where client.example.com is your multiparty meeting server
                                redirect_uri  : 'https://live.example.com/auth/callback'
                        }

Also please let me know example config how do i now enable roles in the config

Thanks

**Comment by L4ky** [comment]
Did you change the "redirect uri" ?
You just need to change live.example.com to your FQDN.

**Comment by Alex-YddeR** [comment]
Yes everything works it redirects after login. Here I am saying when services restarted even I am not logged in with oidc credentials it doesn’t login back successfully to app everytime. 

But same has been working when I comment the auth

**Comment by Alex-YddeR** [comment]
Yes, This has been observed when OIDC Auth is enabled and then services restarted clients not getting connected back automatically everytime.

**Comment by misi** [comment]
We need to check it.. Thanks for the feedback.
