### ISSUE TITLE
Feature Request: Session Recording

### ISSUE THREAD

**Issue by chinthakadeshapriya** [edumeet/edumeet#327]
It is a valuable feature if we have session recorded to the cloud storage

**Comment by bpcurse** [comment]
Recording is a feature that has to be well planned and implemented regarding all the possible privacy implications and legal issues.
Don't make the same mistake(s) as BigBlueButton did: https://github.com/bigbluebutton/bigbluebutton/issues/9202

**Comment by misi** [comment]
See #212  maybe it is duplicate

**Comment by abakanindex** [comment]
Hi there, I need this feature, please suggest how to implement recording on server side. I found [this](https://www.webrtc-experiment.com/RecordRTC) which is working locally. How integrate this with MM? Any help or suggestion most welcome

Regard & thanks
