### ISSUE TITLE
During Session service restarted Logs Below

### ISSUE THREAD

**Issue by Alex-YddeR** [edumeet/edumeet#331]
Dear Team,

Suddenly during the session, services has been restarted and below is the error log found.

1|mmdevelo | (node:1287) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated
1|mmdevelo | Error: This socket has been ended by the other party
1|mmdevelo |     at Socket.writeAfterFIN [as write] (net.js:454:14)
1|mmdevelo |     at Interactive.log (/home/ubuntu/mmdevelop/multiparty-meeting/server/lib/interactiveServer.js:581:17)
1|mmdevelo |     at Interface.<anonymous> (/home/ubuntu/mmdevelop/multiparty-meeting/server/lib/interactiveServer.js:47:9)
1|mmdevelo |     at Interface.emit (events.js:327:22)
1|mmdevelo |     at Interface.EventEmitter.emit (domain.js:485:12)
1|mmdevelo |     at Interface.close (readline.js:424:8)
1|mmdevelo |     at Socket.ontermend (readline.js:209:10)
1|mmdevelo |     at Socket.emit (events.js:327:22)
1|mmdevelo |     at Socket.EventEmitter.emit (domain.js:485:12)
1|mmdevelo |     at endReadableNT (_stream_readable.js:1201:12) {
1|mmdevelo |   code: 'EPIPE'
1|mmdevelo | }
1|mmdevelo | (node:1388) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated

**Comment by misi** [comment]
@Alex-YddeR 
Which node version have you used? 
If not 10.x try to use test with node10.x

**Comment by Alex-YddeR** [comment]
I have used Node Version v13.13.0.  will test with10.x
