### ISSUE TITLE
Ask user once for mic and cam permission

### ISSUE THREAD

**Issue by Astagor** [edumeet/edumeet#345]
I have noticed that other webrtc solution ask just one question to give access to both cam and mic. In MM there are always to separate questions. It is not critical, but can improve the user experience.

**Comment by cap19** [comment]
If the user joins with Audio Only ask for mic only. If they join with Audio and Video then ask for both together.

Don't force camera permission if the user only wants to stay on audio for the whole meeting.

**Comment by N7Remus** [comment]
Will be redesigned later..
