### ISSUE TITLE
More room parameters configuration to different users

### ISSUE THREAD

**Issue by Astagor** [edumeet/edumeet#356]
This is maybe not for now, but for the future. 
I think it would be grate to have the possibility in userMapping to override the config parameters as (maxLastN, autoMuteThreshold, drawerOverlayed and others) per user. So as an example, if the user is a teacher, he can have maxLastN set to 10 and the students to 2.

**Comment by cap19** [comment]
Do this in the database.

**Comment by havfo** [comment]
Yes, these settings will be provisioned from the server based on room configuration, or global rules if the room has not been claimed

**Comment by Alex-YddeR** [comment]
It should be like a mode (Lecture Mode), by enabling this the person who gets activated with lecture mode will see all the user videos where as remaining users will be able to view only lecture user.
So we have hand-raise and chat option to raise the queries and then lecture mode user will enable them based on the request if required.

**Comment by havfo** [comment]
We want to hear all these types og use cases to be able to provide a general way of handling the different cases.
