### ISSUE TITLE
Mobile friendly?

### ISSUE THREAD

**Issue by cap19** [edumeet/edumeet#360]
Generally m-m works quite well on mobile. However, the small screen does present certain limitations. I don't know the goal or how far the design goes when in comes to mobile support...

In this case my OIDC returns email address as a username. Could also happen when OIDC returns a long first and last name.

It becomes hard to fit the name along with all the icons now in the participant list. Here, the mute speaker icon is cut off.

![IMG_3983](https://user-images.githubusercontent.com/63865380/81849113-ad28a880-951b-11ea-8c5b-361b61dd7449.jpg)

**Comment by misi** [comment]
A PR would be very welcomed. :) 
We do our best to fix it..

**Comment by cap19** [comment]
Thanks @misi for tagging this. I would love to fix this but my coding skill sets are limited. 

I hope someone from the community chimes in. I don't know if something like
if mobile, display icons in a new row under the name
