### ISSUE TITLE
Screen share tool tip visible without the button v2

### ISSUE THREAD

**Issue by Astagor** [edumeet/edumeet#371]
Current dev version, steps:
- join a room with audio and video
- on ME press mute MIC (don't move mouse outside of ME)
- press TAB key, the stop video highlights
- move the mouse outside of ME
- the buttons disappear, but stop video label stays

**Comment by misi** [comment]
Thanks!
It seems we need to control the state of all button tooltips and  when buttons are hidden hide them..
