### ISSUE TITLE
activateOnHostJoined and lobby

### ISSUE THREAD

**Issue by Astagor** [edumeet/edumeet#376]
activateOnHostJoined works great when the host is inside. But if people come before the host does, they stay in the lobby. I think they should be automatically promoted when a host enters, like any other users do which come after the host.

**Comment by havfo** [comment]
You are correct, this is the intended function, so this is a bug.

**Comment by so010** [comment]
What is the status of this?

**Comment by Astagor** [comment]
Hmm, I don't remember, but it might be fixed. I will check.

**Comment by Astagor** [comment]
It is fixed.

**Comment by Astagor** [comment]
It is fixed in my version. I will make a pull request
