### ISSUE TITLE
How to go back to auto spotlight?

### ISSUE THREAD

**Issue by cap19** [edumeet/edumeet#388]
Lets say LastN is 1 and there are three total participants in the room. By default the active participant is in spotlight.

But once I select a participant through the arrow keys or highlighting them in the participant list, the spotlight stays on the participant as it should.

Question: how do I go back to auto spotlight?

**Comment by havfo** [comment]
At the moment you need to click the selected peer again.

**Comment by cap19** [comment]
Ah ok, selecting the peer again works in the participant list.

Once you use the arrow keys in the Democratic or Flimstrip view, selecting the peer again in those view does not go back to auto spotlight.

The arrow key functionality is nice way to navigate. I love it. There needs to be a easy way to go back to auto spotlight otherwise it might cause confusion to the users.

**Comment by havfo** [comment]
Yes, we probably want to have some sort of reset button.

**Comment by cap19** [comment]
Our users are having negative experiences with the arrow key spotlight without an easy way to reset  back to auto spotlight. They see the shortcut in the Help and try it and then are stuck with the manual spotlight until they join the meeting again.

While a fix is being devised, where can I disable/comment the arrow key functionality in the code?

**Comment by havfo** [comment]
Comment out the entire two first cases in this switch https://github.com/havfo/multiparty-meeting/blob/b2e91e6d2ce1964f2c66b3c282057c1bce4effde/app/src/RoomClient.js#L305

**Comment by cap19** [comment]
Thank you @havfo
