### ISSUE TITLE
Mic reinit does not work

### ISSUE THREAD

**Issue by Astagor** [edumeet/edumeet#395]
I have a USB mic NOT connected, the audio settings is set on default device, which is now the internal mic of laptop. I connect the usb mic and the system detects it, the default mic gets changed to usb mic, in setting now it is set but no sound is being received from the usb mic. If I change the mic in the settings nothing happens, I have to reload the page in order to use the mic connected. So when connecting a mic while in the room, you cannot use it without leaving and entering the room, although it appears in settings.

**Comment by misi** [comment]
It happens the same with any browser?

**Comment by Astagor** [comment]
OK, I have tested in more on various browser. It is a problem of the audio meter on ME. The mic gets reinited correctly, you have to unmute it, but then the remote side hears everything perfectly. However, the audio meter on ME acts in strange way, it show NO or sometimes a bit of sound, but on the receiver side I see full range of audio coming from the user. So the audio meter does not start correctly after reinit or with some wrong scale. I also noticed that if I enable and disable (just back and forth) the automaticUnmute option, the meter starts to work correctly.  @so010

**Comment by havfo** [comment]
Please check this with commit 1efb1c4a2be007de1dbbf48b3f2b7555f19d1d3a

**Comment by havfo** [comment]
@Astagor please test with latest develop

**Comment by Astagor** [comment]
Well, it works better. Now it is like this:
The USB mic is unplugged, the system has build-in mic as default and also default is chosen in MM. Everything works.
Now I connect the USB mic, the system and MM detects the new mic. The system sets the mic as default, so in MM settings the value changes automatically from build-in mic to USB mic. However, MM still keeps taking the audio from the build-in mic instead of the USB mic. You need in settings to change the audio device to make it start working. So it seams that the audio device is bound by ID, that is good, but: I think what is lacking is, if in MM the default device is chosen as the audio device (same probably for the camera), when a new device appears or disappears from the system, MM should check what is the current default device and update the used device ID to it.
