### ISSUE TITLE
Audio meter

### ISSUE THREAD

**Issue by Astagor** [edumeet/edumeet#399]
The new audio meter, has 1 small thing that are a bit disturbing:
- the meter shows more RED then before, the audio is not overdriven, but the meter gets red by normal level of speaking. One client, being a audio guy said, that it annoys him, as red usually mean that is on the border or over the border of being to loud. He said it should be green 50% of the bar, 25% yellow, 25% red.

This is not critical.

**Comment by so010** [comment]
I already adjusted this in https://github.com/havfo/multiparty-meeting/commit/ad3f7df203561d94fe892ff5ebe5c6b5aec49188
Please check if it is better there!

**Comment by Astagor** [comment]
Much better. One more question, in my deployments I have the autoUnmute turned off for now and the autoGain on. What is your experience with autoGain, as it works great, but of course in amplifies the background nosie, when a person is not speaking and unmuted?

Second question, if you activate autoUnmute, then the autoGain should be automatically disabled right? As it would not allow to have a steady level measurement.

**Comment by so010** [comment]
> Second question, if you activate autoUnmute, then the autoGain should be automatically disabled right? As it would not allow to have a steady level measurement.

Good question - I have to test. I think browser's autoGain should be able to distinguish between noise and voice and will not increase noise above a defined level and the user is able to identify that noise level in the level meter in settings and adjust sensitivity this with the slider.
