### ISSUE TITLE
Limiting to less Frame Rate should consume less bandwidth?

### ISSUE THREAD

**Issue by Alex-YddeR** [edumeet/edumeet#408]
Does limiting frame rate helps us to decrease the bandwidth requirement at both server and client end. i think framerate also plays major role on bandwidth requiremens.

**Comment by misi** [comment]
@Alex-YddeR  Yes we added adjustable FPS constraints.  
Check the latest develop branch..

**Comment by Alex-YddeR** [comment]
My question is if we decrease the frame rate does the bandwidth requirement goes down with out reducing the resolution? why exactly is useful the frame rate option,
