### ISSUE TITLE
Question- How can I add my own authentication service

### ISSUE THREAD

**Issue by rvigneshw** [edumeet/edumeet#423]
I have developed an nodejs based Auth app which basically gives jwt for every successful sign in. 
So my question is how can I integrate that login with this. So that I can allow only the registered users in my Auth app to join or create meeting

**Comment by havfo** [comment]
You need to develop this, we have no support for plugging in arbitrary authentication schemes. In general we use passport for authentication, so you might want to look into that.

**Comment by misi** [comment]
If your auth app use JWT I think it should be OAuth2 and OIDC compatible, to be more standard conform. 
That is the use case we are supporting out of the box.

**Comment by rvigneshw** [comment]
I'm basically using Strapi.js for user authentication so is it compatitable if that so where can I look to change files to handle it [I mean I don't want anyone to create meeting on my server without authentication]

**Comment by misi** [comment]
Can you explain more what your setup?
https://strapi.io/documentation/v3.x/plugins/users-permissions.html#login can use OIDC OP as authN source, and we also suport OIDC for user auth. So e.g. you can use google auth for both?

**Comment by rvigneshw** [comment]
(currently) My setup is my strapi backend running on heroku so when anyone access my mulitparty meeting server a custom login screen is shown  which sends data to strapi backend and with that jwt token it allows the user to attend the meeting 
(question) i want to eliminate the custom login screen and want to use the built in auth service
How can i achieve that?

**Comment by superliwei** [comment]
I got this issue too.

**Comment by Aleeeeeeeex** [comment]
@rvigneshw We have developed a login method that checks valid login from external api with json response.. You can have code if that helps you.

**Comment by jijamik** [comment]
@Aleeeeeeeex  Hello, i'm working on a custom login method, my others apps use a custom API  as SSO, can you show me how you did ?

**Comment by Aleeeeeeeex** [comment]
@jijamik
Added this to server/config/config.js
```
api : {
			requestURL: 'https://localhost',
			endpoint: '/mobile/token',
			method: 'POST',
			type: 'login'
		}
```

and this inside server/server.js
```
function setupAPIAuth() {
	const apiAuthStrategy = new LocalStrategy(async (username, plaintextPassword, done) => {
			try {
				const params = {
					GrantType: 'string',
					ClientSecret: 'string',
					ClientId: 'string',
					Username: username,
					Password: plaintextPassword,
					RefreshToken: 'string',
					Type: config.auth.api.type
				}

				const endpoint = `${config.auth.api.requestURL}${config.auth.api.endpoint}`
				const options = {
					method: config.auth.api.method,
					uri: endpoint,
					headers: {
						'Content-Type': 'application/json'
					},
					body: params,
					json: true
				}

		    const result = await rp(options)

				if (result['success']) {
					return done(null, {
						 id: 1,
						 _userinfo: {
							 id           : 1,
		 					username     : username,
		 					displayName  : username,
		 					emails       : [ { value: username } ],
		 					meet_roles   : [ 'meetingadmin', 'moderator', 'authenticated' ]
						 }
					 });
				} else {
					return done(null, null);
				}

		  } catch (err) {
		    return done(null, null);
		  }
		}
	);

	passport.use('local', apiAuthStrategy);
}
```
