### ISSUE TITLE
Chat refactor

### ISSUE THREAD

**Issue by torjusti** [edumeet/edumeet#43]
Currently, all information about which user was sent by the current user is lost, and all messages are converted to responses.

To fix this, I believe that a lot of work concerning how peers are handled server-side is needed. For example, the peer name is reset when loading the page. Ideally, the peer name should persist for the entire session, and probably somehow be connected to the OpenID identity given that it exists.

Any thoughts?

**Comment by torjusti** [comment]
I also think we should not distinguish between actions for adding messages by the user or from other users. Rather, the client should check if the message was sent by itself or not and render accordingly. This helps solve the problem with sending the list to the user on refresh. Again, some kind of persistent ID is required.

**Comment by misi** [comment]
@torjusti @havfo 
Is this still an open issue? I think it is already addressed.

**Comment by misi** [comment]
@havfo can you please chek it?
