### ISSUE TITLE
shared screen frozen after New Window (but not Fullscreen)

### ISSUE THREAD

**Issue by christian-2** [edumeet/edumeet#433]
When another user shares her screen I can obtain a larger view by clicking either on the "New Window" or "Fullscreen" icon in the smaller view. The two options show different behavior in that only "Fullscreen" gives a larger view that remains live, whereas with "New Window" the larger view is apparently frozen as a static image. Is this a feature or a bug?

**Comment by havfo** [comment]
This is a bug, which browser are you using?

**Comment by christian-2** [comment]
It's Firefox 76.0.1 (w/ Private Window, i.e. w/o cookies) on macOS.

**Comment by Astagor** [comment]
Happened to me also on Chrome

**Comment by havfo** [comment]
Fixed in new client
