### ISSUE TITLE
Settings persistence

### ISSUE THREAD

**Issue by Astagor** [edumeet/edumeet#444]
It happened to me 2 times, that after upgrading the app when I open the settings I could not choose a camera nor change maxN. Can it be that the settings stored in the browser get recalled by the new version of the app with changed schema of settings, that some strange things happen? When I deleted the storage and re entered the room the settings were good again. Maybe the settings stored in the browser should have a version number and if a new version of settings is implemented, the app should delete the stored values or there should be done upgrade procedure. Normal users will not clear the browser storage.

**Comment by Alex-YddeR** [comment]
Yes, even we cannot see the list of audio/video devices connected for the first time login in incognito private browser. once refreshed devices appears.

**Comment by so010** [comment]
Looks like a bug if user mediadevices are not allowed to use automatically. This affects all first time users because browser will ask for permission to access cam/mic.

**Comment by so010** [comment]
Is Fixed now, but let this open because we should do that with settings persistence and clean cookies if version differs.

**Comment by Astagor** [comment]
@so010 In the example config you have other values than in the code 48000 vs 96000. I think they should be the same to keep in consistent.
Also in RoomClient you have:
			const {
				sampleRate = 96000,
				channelCount = 1,
				volume = 1.0,
				sampleSize = 16,
				opusStereo = false,
				opusDtx = true,
				opusFec = true,
				opusPtime = 20,
				opusMaxPlaybackRate = 96000
			} = window.config.centralAudioOtions;

I would change it to
....
= window.config.centralAudioOtions?window.config.centralAudioOtions:{};

To be backward compatible with old configs without the centralAudioOtions. Our code makes the app crash with configs not having the tag. The changed just uses the default values from code.

**Comment by Astagor** [comment]
@misi you have added to throw an error, don't you think using defaults from code is better?

**Comment by so010** [comment]
I really wanted to make it incompatible with old configs because I want to force everybody to update this. There were some bugs making audio not working like configured.

**Comment by Astagor** [comment]
But which values are recommended from code or config there are differences in opusPtime, opusMaxPlaybackRate, sampleRate  ?

**Comment by so010** [comment]
The ones I made in config.example.js but I agree defaults in code should be the same as in config example. Not really sure about the 96Khz sampling rate. But looks like that this is working nicely without using more bandwidth.

**Comment by so010** [comment]
https://github.com/edumeet/edumeet/commit/365d7fdd0d9b8594446339c619192dfe8292d5e1

**Comment by Astagor** [comment]
Great! How does the persistence reset work, what should be set and where to reset the store?

**Comment by so010** [comment]
sorry referred to wrong commit :
https://github.com/edumeet/edumeet/commit/3387c133eec8709265e5ff49e37e166ede30b556

See store.js in migrations:
https://github.com/edumeet/edumeet/blob/eeebaf05414286fc922128ccf17f21f95606078c/app/src/store.js#L14

right now we have version 0 where we delete everything from history.
next version 1 we have to implement like this:
oldValue = undefined; // will remove oldValue from next local storage
new values can be defined from config.js and go that way to new local storage

redux-persist will save a version number to each local store. Next time it starts it will check if there are newer versions here in migrations and iterate over all defined greater version functions until newest version is reached.
