### ISSUE TITLE
Bad network indicator on ME when camer set to low

### ISSUE THREAD

**Issue by Astagor** [edumeet/edumeet#450]
Scenario:
	 simulcastEncodings :
	 [
	   	 { maxBitRate: 250000 },
		 { maxBitRate: 750000 }
	 ],
2 clients, both start in camera "medium"
1 switches the camera to "low" and gets on the ME window the red mark for the connection. On the remote side no indicator. This is related to #319 that for camera set to low, the worst simulcast video is only sent (I see it on the stats 250kb sending). Can it be that there is an bug in the calculation of the quality of the network for low resolution streams? That could explain this and the things from 319. Or maybe just the interpretation on the sender side is buggy as the receiver does not get the indicator?

**Comment by misi** [comment]
@Astagor  What is ME window?

**Comment by Astagor** [comment]
Own video, ME in the English interface.

**Comment by misi** [comment]
Shame on me.. :)

**Comment by misi** [comment]
@Astagor  Can you retest on letsmeet.no? I don't experience it. Can you help to reproduce the issue?
