### ISSUE TITLE
Cannot add back camera iPhone on letsmeet

### ISSUE THREAD

**Issue by Alex-YddeR** [edumeet/edumeet#451]
Not able to add or change back camera on iPhone safari browser. My version of IOS is 13.5
I checked this on letsmeet portal

Thanks

**Comment by Alex-YddeR** [comment]
Can anyone facing this issue?

**Comment by Astagor** [comment]
I don't have an iPhone, sorry.

**Comment by Astagor** [comment]
On the other hand, I can get access to an iPad today evening.

**Comment by Alex-YddeR** [comment]
> On the other hand, I can get access to an iPad today evening.

May be iOS version if different in your case

But  I Am Not able to add or change back camera on iPhone safari browser. 
My version of IOS is 13.5
I checked this on letsmeet portal and also in develop branch portal it’s the same issue. 
Checked in incognito it’s the same issue. 
If I tried to select back camera it doesn’t apply at all.

**Comment by cap19** [comment]
See this https://github.com/havfo/multiparty-meeting/issues/359

**Comment by Alex-YddeR** [comment]
I was able to do this in some days back.

**Comment by Astagor** [comment]
@havfo This is a critical bug. On all mobile device and MS Surface. On my Android I cannot switch camera. Also on Surface. When I change the camera in settings it jumps back to the previous camera!

**Comment by havfo** [comment]
I can change the camera on my device. Could you please remove all instances of `facingMode  : { ideal: 'user' },` in `RoomClient.js` and test again?

**Comment by Astagor** [comment]
Yes this has helped. Now I can switch camera.

**Comment by Astagor** [comment]
This was only on Android, iOS, MS surface. On my laptop with 2 web cams I could switch.

**Comment by Astagor** [comment]
Does commenting this out destroy something else? Or was it just an extra feature?

**Comment by havfo** [comment]
Will not screw up anything to remove it, simply an extra feature to try to get a user facing camera.

**Comment by Astagor** [comment]
OK. The interesting thing was, that I could not turn on the camera facing the user on MS surface, I had only the back camera. On Android and iOS it was OK, got the front camera, not the back...

**Comment by Astagor** [comment]
As for me, it can be closed now.

**Comment by havfo** [comment]
@Alex-YddeR can you verify with latest develop? (not on letsmeet yet)

**Comment by Alex-YddeR** [comment]
Thanks for the update.
