### ISSUE TITLE
Bug in handling name change

### ISSUE THREAD

**Issue by Astagor** [edumeet/edumeet#454]
On ME screen the user can change his name. If he enters an empty string Guest is being assigned automatically. So far so good. But now if he clicks the 'Guest' to change it again, the input is not editable anymore and the user cannot change the name. Tested with https://letsmeet.no/.

**Comment by Astagor** [comment]
I think it is something to due with the store.

**Comment by misi** [comment]
@Astagor  Can you retest it.
It seems it is working now on letsmeet.no

**Comment by misi** [comment]
I will close I see this is fixed..

**Comment by Astagor** [comment]
Yes, this has been fixed.
