### ISSUE TITLE
Bug putting user into Spotlight ignores maxLastN and lastN

### ISSUE THREAD

**Issue by Astagor** [edumeet/edumeet#456]
Like it the title, when using the new participant menu I can put user into Spotlight and I see more users at the same time with video, then maxLastN allows. I think that the put into Spotlight function should obey the users lastN setting (thus also not exceed the maxLastN) and just replace videos not in spotlight for those set to spotlight.

**Comment by misi** [comment]
This has been fixed. I close it.
