### ISSUE TITLE
[Feature Request] - MM WebRTC Broadcating to RTMP - Is that really hard to implement?

### ISSUE THREAD

**Issue by jzvi12** [edumeet/edumeet#463]
Hi there, this has been probably asked or requested before but I think MM should be the first one to get it implemented since it has a wonderful UI and features.

Is this something you guys are already working on? If not, do you see this feature being added soon (this year)?

Maybe you guys can share, in a very high level, what would be the right approach of implementation for MM to get this added?

**Comment by enterux** [comment]
We have some work being done on this, but most of it is hack in progress ..

**Comment by jzvi12** [comment]
Any updates?

I see from https://edumeet.org/technical-overview/ that the broadcast feature is available on the production version? What does this mean?
