### ISSUE TITLE
Permit moderator to promote peer as a presenter

### ISSUE THREAD

**Issue by chinthakadeshapriya** [edumeet/edumeet#469]
How can we permit moderator to promote peer as a presenter ?

**Comment by havfo** [comment]
Ser https://github.com/havfo/multiparty-meeting/issues/437#issuecomment-640083519

**Comment by chinthakadeshapriya** [comment]
Have pushed the code for modify roles.

**Comment by havfo** [comment]
See 5a4bd1f4f53a099ddf0288a9eea352efd4094f2a
