### ISSUE TITLE
Is there any forum? so we can share our knowledge, ask question . . . 

### ISSUE THREAD

**Issue by abakanindex** [edumeet/edumeet#470]
If there is any forum blog, if not please create discord for example. If already exist please share

**Comment by harivyas35** [comment]
Hi Were you able to deploy it as a service

**Comment by misi** [comment]
There is a mailing list: community@lists.edumeet.org, and monthly there is a community meeting.
See more in the https://github.com/havfo/multiparty-meeting/blob/master/README.md#community-driven-support

**Comment by misi** [comment]
@harivyas35 Yes I was able to deploy it as a service.

**Comment by harivyas35** [comment]
HI @misi ,
Firstly Thank you for replying to my comment .
I am not able to deploy it as a service .
I tried installed the debian package and changed the ip address as well but the service is running but not able to connect to thag ip adress in browser . Also i tried the manual way as well edited both config file for server ,added TURN server to the config file and edited the listing port as 3443 ans ListningRedirectPort as 8000 but after running the server as 'npm start ' and putting the ip address and port number in browser i could only see first two pages until entering our user name . And after clicking on join audio only or audio/video both ,the page gets stuck  there . And after i inspect it ,i can see "resource not found ,connetion refused " error , i request you to please help me with this ,as i have searched a lot for this error on internet but was not able to find and proper solution .

Regards,
Hari Vyas

**Comment by misi** [comment]
@harivyas35  please use the community list for support. You need to check if server is running, and you connect to the right port with the web app. I propose to check the ansible script.https://github.com/misi/mm-ansible/
