### ISSUE TITLE
Select audio output device

### ISSUE THREAD

**Issue by vlzkonopatov** [edumeet/edumeet#474]
When you select an output device (Bluetooth headset), switching is successful, but the sound level becomes very quiet and almost nothing is heard. Has anyone encountered such a problem? Android device.

**Comment by misi** [comment]
I don't have experienced such issue and AFAIU it should be a local issue.

**Comment by Astagor** [comment]
Issues with headsets are often caused by the vendor implementation of audio sinks on Android. On my OnePlus5 and a sunny BT headset it works fine, but the same headset on Samsung S7 does not.

**Comment by misi** [comment]
I think it is more a browser issue then ours, so I close this issue now.
If you disagree, then please let me know and I will reopen it.
