### ISSUE TITLE
No Audio or Video on mobile

### ISSUE THREAD

**Issue by harishruparel** [edumeet/edumeet#475]
Hi, I am new to this and have limited coding skills hence looking for help here. I have cloned this on my ubuntu server and when started, I am able to  start the meeting but when I use the link in my Mobile - chrome on Android and IOS, there is no Audio nor video. The desktop cannot see the video from Mobile neither cannot hear, and the Mobile cannot see the video nor hear from desktop. although the camera and mic are allowed. Please help. However Desktop to desktop is working fine.

**Comment by verbavolant** [comment]
Audio/Video on mobile iOS is not supported by apple webkit. You should use safari, it works!

**Comment by livingloves** [comment]
I am Having The Same Problem To 
My Friend And I ware Testing the Server 

I can't able to see his Video and Audio 
He Can't able to get my Video and Audio  

How to Fix It ?

We Both Are Testing is on Laptop
