### ISSUE TITLE
Spotlights and lastN

### ISSUE THREAD

**Issue by Astagor** [edumeet/edumeet#476]
I just wanted to get back to the topic that the number of spotlights should be limited to the current last N of the user. For large rooms with 100 users I limit maxLastN to 2 so I can have on the server some of such rooms. If now users using spotlights can have more videos, they can destroy the whole stability of the server and overload the bandwidth capacity. The server admin loses the control.

**Comment by havfo** [comment]
Should a new selected peer push out another peer, or should it not be possible to select more before deselecting another peer?

**Comment by Astagor** [comment]
I have implemented in my own code, that it is a FIFO, so the first selected is automatically deselected.

**Comment by Astagor** [comment]
@havfo have a look at my pull request.
