### ISSUE TITLE
Chat window reverse order

### ISSUE THREAD

**Issue by Astagor** [edumeet/edumeet#477]
I think that the chat window should display newest messages on the top, so the user does not have to scroll down to see newest.

**Comment by hhuseyinpay** [comment]
Or auto-scroll might add. Messages are displaying at the bottom in almost every massaging app.

**Comment by Astagor** [comment]
True but I hate when the window jumps down on an incoming messages and I have been searching something in the history

**Comment by hhuseyinpay** [comment]
When a new message comes in, we should check whether the scroll bar is at the bottom or not. If the scroll bar is at the bottom when a new message comes in, add the message and move the scroll bar to down. If the scroll bar is at the top when a new message comes in, just add the massage.

**Comment by havfo** [comment]
Does this not happen correctly. I tested in both Chrome and Firefox, and both of them scroll correctly on new messages. If you "leave" the bottom, you have to scroll down to the bottom again to make it auto-scroll again.

**Comment by Astagor** [comment]
I will test one more time. Sorry if I have mixed up something.
