### ISSUE TITLE
Connection REFUSED Error comming .

### ISSUE THREAD

**Issue by harivyas35** [edumeet/edumeet#478]
Hi ,
I am perfectly able to use this app using 'sudo npm start' command.
But as i use 'npm start' command , and open the app hitting theb url 'https://ipaddr:3443/roomname'
then the initial page for joining the room is displaying , but after i click to join the room with only audio or audio+video' the page stucks and when i inspect it in chromium browese ,and error 'Connection refused' is displayed.
I request you to please help me as i am new to this.

Regards,
Hari Vyas

**Comment by misi** [comment]
Check if server is runing and you configured to listen on the right port.
Check browser dev console

**Comment by harivyas35** [comment]
Hi Misi,
I am trying to deploy the app as a service but not
able to do so .Below things i have changed
in app/public/config/config.js file 

developmentPort : 8000,
productionPort  : 8000,

And the changes in server/congig/config.js are as follows
listeningPort         : 8000,
listeningRedirectPort : 8080,
In  mediasoup WebRtcTransport settingsoup
I have put the ip as 127.0.0.1.
and 
 fileTracker  : 'wss://tracker.lab.vvc.niif.hu:8000',
TURN server , i have kept the port as 8000.
and I have generated cert.pem and key.pem and used them
with the above setting i am able to run the app locally
using command line .But after i create the service by 
following the command and start the service , the
service stops with the below error:
(code=exited, status=1/FAILURE).
I request you to please help me with this issue as i am
new to this tech stack.

Note: When i keep the port as 443 in my turn server
and fileTracker  : 'wss://tracker.lab.vvc.niif.hu:443'
the service starts and when i put my ip-127.0.0.1 i can
start the app ,but as soon as i try to join the room
it says unable to join the room.And the pages gets
reloaded.

Regards,
Hari Vyas

**Comment by misi** [comment]
Try to use your interface ip

**Comment by bianxg** [comment]
I meet same problem. "I click to join the room with only audio or audio+video' the page stucks ". 
Please help.

npm -v
6.14.4

node -v
v13.14.0

lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.6 LTS
Release:	16.04
Codename:	xenial

vi server/config/config.js
...
listeningPort         : 8443,
...
 { ip: '192.168.2.223', announcedIp: null }

$cd server
$npm start

I use chrome visit:
https://192.168.2.223:8443/qu0pgfcg

browser dev console show:
GET https://192.168.2.223/socket.io/?peerId=jkpbmqle&roomId=qu0pgfcg&EIO=3&transport=polling&t=NBBexLT net::ERR_CONNECTION_REFUSED

**Comment by havfo** [comment]
Please set `developmentPort` and `productionPort` in the app config. `developmentPort` is the port that the client will use for socket connection if you do `npm start` in the app folder. `productionPort` is the port that the client will use for the socket connection if you do a `npm run build` in the app folder, and then run the server.

**Comment by bianxg** [comment]
Now I do a npm start in the app folde, but same as before. Must I generate cert.pem and key.pem?

$npm start
You can now view multiparty-meeting in the browser.

  Local:            https://localhost:4443
  On Your Network:  https://192.168.2.223:4443

Note that the development build is not optimized.
To create a production build, use npm run build.

https://192.168.2.223:4443/jcfi0ml9

GET https://192.168.2.223:3443/socket.io/?peerId=9vecl1l3&roomId=jcfi0ml9&EIO=3&transport=polling&t=NBBlrcG net::ERR_CONNECTION_REFUSED

**Comment by bianxg** [comment]
get it. Thanks

**Comment by harivyas35** [comment]
My issue is solved ,thank you for the replies
