### ISSUE TITLE
About box translation (and Privacy Policy)

### ISSUE THREAD

**Issue by pioskala** [edumeet/edumeet#482]
Could About box text be added to the translations? Maybe would be good to make samething similar with Privacy Policy?

Regards,
Piotr

**Comment by misi** [comment]
I don't understand the question. Can you explain more why and how you think? @pioskala

**Comment by pioskala** [comment]
![image](https://user-images.githubusercontent.com/26139820/85392673-28826e80-b54c-11ea-8992-b575c2561ef8.png)
It would be good to add possibility to translate this text.
I'm not sure how to solve Privacy Policy but how should I do it if we want it in two languages?

**Comment by misi** [comment]
We can add a full translation not an issue. 
We (core devopers) agreed that in 3.3 it was good enough as a start to have it only in English, but we can reconsider it.
