### ISSUE TITLE
TURN backup servers not kicking in if TURN API fails.

### ISSUE THREAD

**Issue by Astagor** [edumeet/edumeet#484]
Today the GEANT TURN API was down for about 30 minutes. In MM when joining a room it waited before timing out and then reloaded a next room. But when I've commented out the TURN API in config.js the backup turn server configuration worked. So there should be some kind of backup mechanism, that if the TRUN API fails, then the backup TURN servers should be used automatically.

**Comment by misi** [comment]
API call need to have a short time limit. 
https://github.com/havfo/multiparty-meeting/blob/46a2c075f03a7e348ecfbc34ba425cc458f5f3a0/server/lib/Room.js#L501
e.g.
`timeout: 3000`
