### ISSUE TITLE
Can't see the video of other participants

### ISSUE THREAD

**Issue by zhengxiaochuan-3** [edumeet/edumeet#487]
and no log  to check out the reason

![image](https://user-images.githubusercontent.com/10624990/85095131-22765000-b223-11ea-903b-337ee67ffc09.png)

![image](https://user-images.githubusercontent.com/10624990/85094986-b398f700-b222-11ea-84d4-37b290f9dd44.png)

**Comment by abakanindex** [comment]
Hi, I think it is because of TURN server not configured. Please if some knows to configure TURN server for MM. And if I want use third party service like Xirsys.com how I can integrate? 
Thanks

**Comment by vidukapoor** [comment]
i think you have too use turn server configuration, in latest release.
https://github.com/havfo/multiparty-meeting/issues/459

**Comment by havfo** [comment]
If you don't need a TURN server, you can remove `turnAPIKey`, `turnAPIURI`, `turnAPIparams`, `backupTurnServers` from the config.

**Comment by zhengxiaochuan-3** [comment]
I`m using a aws vm with a pubic IP, So i don`t need a turn server.  
And I already remove turnAPIKey, turnAPIURI, turnAPIparams, backupTurnServers from the config.
Stiil can`t see other participants

**Comment by havfo** [comment]
The TURN server is not because of the server. The TURN server is for the clients that might be behind restrictive firewalls or NAT.

**Comment by zhengxiaochuan-3** [comment]
Thank you. I should configure the announcedIp for my demo

**Comment by zhengxiaochuan-3** [comment]
> The TURN server is not because of the server. The TURN server is for the clients that might be behind restrictive firewalls or NAT.

Yes, But I do have a public ip ,so I don`t need a STUN/TURN server

**Comment by misi** [comment]
> > The TURN server is not because of the server. The TURN server is for the clients that might be behind restrictive firewalls or NAT.
> 
> Yes, But I do have a public ip ,so I don`t need a STUN/TURN server

No you need TURN even if you have public IP. 
e.g. in case of strict firewall that filters UDP traffic

**Comment by zhengxiaochuan-3** [comment]
> > > The TURN server is not because of the server. The TURN server is for the clients that might be behind restrictive firewalls or NAT.
> > 
> > 
> > Yes, But I do have a public ip ,so I don`t need a STUN/TURN server
> 
> No you need TURN even if you have public IP.
> e.g. in case of strict firewall that filters UDP traffic

ok, thanks.

**Comment by vidukapoor** [comment]
> If you don't need a TURN server, you can remove `turnAPIKey`, `turnAPIURI`, `turnAPIparams`, `backupTurnServers` from the config.

i have removed all the config of the turn server, but not able to get the video of the other participants.

<img width="1321" alt="Screen Shot 2020-06-23 at 9 42 26 PM" src="https://user-images.githubusercontent.com/14005853/85428355-b1c09200-b59a-11ea-826d-cd67e6c50166.png">
<img width="235" alt="Screen Shot 2020-06-23 at 9 42 37 PM" src="https://user-images.githubusercontent.com/14005853/85428371-b5ecaf80-b59a-11ea-8053-6fc41ae2bea3.png">

i am thinking the red mark for the signal is denoting issue here.

**Comment by aravindgp** [comment]
> > If you don't need a TURN server, you can remove `turnAPIKey`, `turnAPIURI`, `turnAPIparams`, `backupTurnServers` from the config.
> 
> 1. removed all the config of the turn server, but not able to get the video of the other participants.
> 2. using public IP here.
> 
> <img alt="Screen Shot 2020-06-23 at 9 42 26 PM" width="1321" src="https://user-images.githubusercontent.com/14005853/85428355-b1c09200-b59a-11ea-826d-cd67e6c50166.png">
> 
> <img alt="Screen Shot 2020-06-23 at 9 42 37 PM" width="235" src="https://user-images.githubusercontent.com/14005853/85428371-b5ecaf80-b59a-11ea-8053-6fc41ae2bea3.png">
> 
> i am thinking the red mark for the signal is denoting issue here.
> 
> non-working-hash: [0ad219d](https://github.com/edumeet/edumeet/commit/0ad219d98f74ed2f57f55a64c24515e26f0a4f08) (Jun 15, 2020)
> working hash: [9c34ff4](https://github.com/edumeet/edumeet/commit/9c34ff4d79c5990bec2cb0d9728e78e335e0cba7) (April 23, 2020, i have tested)

@havfo @misi Can anyone respond to this issue ?

**Comment by havfo** [comment]
@aravindgp Are the clients you are testing with on public IP without firewalls?

**Comment by aravindgp** [comment]
Yes on digitalocean servers. I can enable them can you suggest what needs to be done. Still no luck for us.

**Comment by aravindgp** [comment]
Worked after port allowing explicitly in server!

**Comment by aravindgp** [comment]
> @aravindgp Are the clients you are testing with on public IP without firewalls?

Thank you

**Comment by shaikh-kamran** [comment]
@aravindgp what exactly you allowed, and on which server? TURN server or app server and please tell me exactly which ports you have allowed

**Comment by aravindgp** [comment]
APP SERVER
