### ISSUE TITLE
Scalability issues

### ISSUE THREAD

**Issue by hhuseyinpay** [edumeet/edumeet#490]
Hi. We are using mm with the following configs:
**server**
routerScaleSize      : 40,
mediasoup            :
                numWorkers : 8, //Object.keys(os.cpus()).length, 
**app**
lastN                : 4,
mobileLastN          : 4,
maxLastN             : 4,
autoMuteThreshold    : 4,

When there are 100+ attendees and 2-3 speakers in a meeting, the client app uses too much CPU. Attendees that are using phones or low spec computers frequently lose the connection and some of them have the sound-video issue. 

My computer is MacBook 2017 i7
![Screen Shot 2020-06-17 at 21 25 55](https://user-images.githubusercontent.com/14811488/84939262-bc84ae00-b0e6-11ea-99d7-1e8d7a5149e3.png)

Ubuntu 20 VM on ESXi 6.7: 12 CPU 16GB RAM 
(Physical server: 2 x 20 CPUs x Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz)

![Screen Shot 2020-06-17 at 21 26 12](https://user-images.githubusercontent.com/14811488/84939600-416fc780-b0e7-11ea-9f38-9b95b7055a03.png)

**Comment by misi** [comment]
What is causing this high cpu on the client.
We planned but not yet reached the point where we can test 100+ endpoints in a room.. :-/

**Comment by hhuseyinpay** [comment]
I'm sorry for the late response. Its been rough days for me.
@misi I think there are lots of calculations in the frontend. For example, someone opens the mic spotlight changes by calculations. This is good for small meetings but when numbers greater than 100, moderators should choose who will be in the spotlight.
@havfo All other settings are default. I think 4 is not a problem in most cases. We are also using bigbluebutton, we do not receive a complaint about that.

**Comment by misi** [comment]
@hhuseyinpay  many thanks for the info and the feedback.
