### ISSUE TITLE
New feature plan

### ISSUE THREAD

**Issue by zhengxiaochuan-3** [edumeet/edumeet#491]
Are there any plans to support :
1. cascaded sfu 
2. distributed room across sfu servers

**Comment by misi** [comment]
Yes. It is on the roadmap see https://github.com/havfo/multiparty-meeting/tree/feat-media-node 
depends how much developer resource we have.

**Comment by chrispawned** [comment]
Awesome. Looking forward to that @misi

**Comment by octalframes** [comment]
Is this meeting room implementation sfu based?

**Comment by misi** [comment]
@octalframes Yes.
