### ISSUE TITLE
New features

### ISSUE THREAD

**Issue by Astagor** [edumeet/edumeet#495]
I have implemented 2 functions:
- disable mirror for own video (in settings)
- hide self view - hide own videos (main + extra) and screen sharing

I'm on holidays now, but if I find an hour I can make a pull request. Should I?

**Comment by misi** [comment]
Yes

**Comment by Astagor** [comment]
I will do it next week, I'm on holidays now.

**Comment by misi** [comment]
Let's wait for Stefan @so010 review..

**Comment by misi** [comment]
I will close this issue, let's cont on PR's
