### ISSUE TITLE
New release has issue with turn servers ...

### ISSUE THREAD

**Issue by aravindgp** [edumeet/edumeet#496]
> > If you don't need a TURN server, you can remove `turnAPIKey`, `turnAPIURI`, `turnAPIparams`, `backupTurnServers` from the config.
> 
> 1. removed all the config of the turn server, but not able to get the video of the other participants.
> 2. using public IP here.
> 
> <img alt="Screen Shot 2020-06-23 at 9 42 26 PM" width="1321" src="https://user-images.githubusercontent.com/14005853/85428355-b1c09200-b59a-11ea-826d-cd67e6c50166.png">
> 
> <img alt="Screen Shot 2020-06-23 at 9 42 37 PM" width="235" src="https://user-images.githubusercontent.com/14005853/85428371-b5ecaf80-b59a-11ea-8053-6fc41ae2bea3.png">
> 
> i am thinking the red mark for the signal is denoting issue here.
> 
> non-working-hash: [0ad219d](https://github.com/edumeet/edumeet/commit/0ad219d98f74ed2f57f55a64c24515e26f0a4f08) (Jun 15, 2020)
> working hash: [9c34ff4](https://github.com/edumeet/edumeet/commit/9c34ff4d79c5990bec2cb0d9728e78e335e0cba7) (April 23, 2020, i have tested)

@havfo @misi Can anyone respond to this issue ?

_Originally posted by @aravindgp in https://github.com/edumeet/edumeet/issues/487#issuecomment-650609430_

**Comment by aravindgp** [comment]
closed for lack of knowledge

**Comment by aravindgp** [comment]
Closed after allowing ports

**Comment by shaikh-kamran** [comment]
Which Ports exactly?
