### ISSUE TITLE
Signalling API (for external clients)

### ISSUE THREAD

**Issue by jprjr** [edumeet/edumeet#504]
Hi there -

I didn't know if you had any kind of documentation on signalling.

So far, I've been really impressed with Edumeet's interface flexibility and options!

My use-case: I'd like to write a custom, headless client that can push video via WebRTC. I think if I can get a grip on the API/signalling aspect, it would be possible. Thank you!

**Comment by havfo** [comment]
There is a stripped down signaling client [here](https://www.github.com/edumeet/edumeet-sip/tree/master/src%2FRoomClient.js) that is used for a SIP gateway. Hope it can be of help.

**Comment by roman-drozd-it** [comment]
No response longer than 1 month. Considered resolved.
