### ISSUE TITLE
[Feature Suggestion] Per-stream, client-side volume control

### ISSUE THREAD

**Issue by jprjr** [edumeet/edumeet#505]
I'd like to suggest a feature: add a volume slider in addition to mute for incoming audio/video streams.

This way, if somebody is speaking too loudly into their microphone, I can just turn them down.

**Comment by Beiri22** [comment]
I would appreciate this feature. I've had several meetings with varying volumes of the participants. I can't tell anyone to change their mic settings, most due to lack of technical background. An easy way to adjust the per-user-volume live in the meeting would be nice.

**Comment by so010** [comment]
This bug was introduced by me. I thought people can and want control their mic levels by themselves and so I made autoGainControl = false by default. This is difficult to roll back. You need latest develop branch AND update autoGainControl in your app/pub/config/config.js to make this default true to all existing settings on all clients.

**Comment by jmencak** [comment]
`autoGainControl == true` is one option, but it isn't a silver bullet at least in my experience. It is unclear to me whether it is [supported on Safari](https://developer.mozilla.org/en-US/docs/Web/API/MediaTrackSettings/autoGainControl) and I do not own an Apple device to test.  Another reason for using manual volume control per participants apart from broken or unsupported `autoGainControl` would be audio volume sensitive setups (groups of musicians playing together).

Methods of implementation:
  - set the volume attribute of the `<audio>` element
  - use Web Audio API and `gainNode` (`createGain()`)

I believe both have its advantages and disadvantages.  The first cannot go above 100% of volume sent by the peer and therefore it can only reduce the volume.  The second does not have this disadvantage but could potentially add audio delay?  This assumption needs to be verified and measured how bad this can be.

/assign @jmencak

**Comment by jmencak** [comment]
Closing as the functionality merged into the `develop` branch.

**Comment by kmpartner** [comment]
I tried to implement client-side volume control. When used it with multiple party, echo problem happened and it is difficult to tell whether volume control is working or not. 
How can I solve this echo problem?
