### ISSUE TITLE
Turn API config and support

### ISSUE THREAD

**Issue by chrispawned** [edumeet/edumeet#506]
```
	turnAPIKey    : 'examplekey',
	turnAPIURI    : 'https://example.com/api/turn',
	turnAPIparams : {
		'uri_schema' 	: 'turn',
		'transport' 		: 'tcp',
		'ip_ver'    		: 'ipv4',
		'servercount'	: '2'
```
Is this template config supported for authentication to TURN server (Ex: Coturn Rest API) based on time-based credential mechanism?
This doesn't seem to work with Coturn API

**Comment by misi** [comment]
Hi,

Yes it depends on coturn rest but also adds a layer above.
See these: 
* https://github.com/misi/stun-api
* https://github.com/misi/stun-ansible

**Comment by roman-drozd-it** [comment]
No response much more than 1 month. Closed as resolved.
