### ISSUE TITLE
Problem In Screenshare

### ISSUE THREAD

**Issue by harivyas35** [edumeet/edumeet#507]
Hi,
Suppose there are 20 participants in a room. 19 Have joined using theier phones and one has joined using his/her laptop.
The person using laptop is  sharing the screen . And as number of visible videos (by default is 1 in phones ) .then if other participants unmute let say 5 participants and they are discussing which is shared on the screen ,then they won't be able to see the shared screen as the number of visible videos is set to one (the participant who speaks his/her video element is rendered) .
I know this can be solved by seeting number of visible videos to more number of participants who are active speakers .
But in mobile when we set number of visible vodeos to more than 5 the in both views.The screen doesn't looks good . It looks messy with the 'video paused 'message comming out of the video element. So if this screen share issue can be solved then that would be great .The acceptable scenario could be 'if the number of visible videos in phone is set to one and someone in the room is sharing the screen and other users have used full screen to that shared screen element ,then even after other participants unmute and speaks then the shared screen should not disapper for the participants.

Regards,
Hari vyas

**Comment by misi** [comment]
Sorry for the late reply!

We know that we need to work on this to make it better, so if you can help on it it would be great. 
Please if you have the possibility, then please help us with Pull Request that makes it in better way.

**Comment by harivyas35** [comment]
Hi @misi ,
Thank you for your reply . I am still learning react . I will surely try to implement ,and if i succeed i will raise a pull request.

Regards,
Hari Vyas
