### ISSUE TITLE
Video & audio of other participants not coming on server

### ISSUE THREAD

**Issue by woshik** [edumeet/edumeet#508]
Hi,
I install the application manually, locally it's working fine but when I upload the application on the server, video, and audio not coming of other participants. Video, screen share those sections are black. I can create room anyone can join there everything working fine but the video and audio not working, I setup the config file also but not working

here is my server
https://msdev.wiresquare.com/

also the server config file
https://codeshare.io/5PjJdd

What could this be, can anyone please help me?

Thank You.

**Comment by havfo** [comment]
Your config looks good, but you have no TURN server configured. If your clients are behind restrictive firewalls or NAT you may have trouble with the connections. Also make sure you have opened 40000-49999 in the server firewalls.

If you have opened 40000-49999 TCP on the server, you may also test with the parameter `forceTcp=true` in the URL when you join the room.

**Comment by woshik** [comment]
@havfo thank you so much for your help. Can you please help to setup TURN server?
Now, I am using amazon aws. So there are some restrictive firewalls.

Thank you.

**Comment by misi** [comment]
@woshik Try to use coturn or similiar TURN server. See: https://coturn.net

**Comment by pierguinzani** [comment]
@woshik, how did you solve your problem? Can you share your solution? I have the same problem.
