### ISSUE TITLE
Question: userMapping for LTI integration with Moodle

### ISSUE THREAD

**Issue by zmartinovic** [edumeet/edumeet#509]
Hi,

we are testing eduMeet and are looking to connect it with Moodle using LTI. What is recommended user mapping for this purpose? Is this configuration OK?

`userMapping : async ({ peer, roomId, userinfo }) =>
{
	if (
		Array.isArray(userinfo.meet_roles) &&
		userinfo.meet_roles.includes('Instructor')
	)
	{
		peer.addRole(userRoles.MODERATOR);
	}
	if (
		Array.isArray(userinfo.meet_roles) &&
		userinfo.meet_roles.includes('Administrator')
	)
	{
		peer.addRole(userRoles.ADMIN);
	}
	peer.addRole(userRoles.AUTHENTICATED);
}`

If there are some other tips for Moodle integration we would love to try them.

Best,
Zvonko

**Comment by misi** [comment]
Sorry for the late reply. 
I don't have any further tip. I use it the same way.
