### ISSUE TITLE
Microphone unmuted after network reconnection

### ISSUE THREAD

**Issue by hajoscher** [edumeet/edumeet#510]
When being disconnected due to network issues whilst muted, 
the user is unmuted after being reconnected.
That is problematic since it might unmute the user unknowingly. 

Tested today on https://edumeet.geant.org/ while my network was bad.

**Comment by zhengxiaochuan-3** [comment]
+1

**Comment by misi** [comment]
In 3.3.0?

**Comment by misi** [comment]
I think I see the root of the issue. Only settings is persistent. `Me` properties are not..

**Comment by misi** [comment]
I was little bit wrong. `Me` Redux state also does not contain the manual mute status.
All in all AFAIU the issue is that we don't store audio video muted state in the persistent local storage.

**Comment by so010** [comment]
Same for video mute

**Comment by misi** [comment]
Fixed in https://github.com/edumeet/edumeet/commit/48baea3cf28a9ad501794a3205574bb9f9fb5357
