### ISSUE TITLE
Massive Connection Drops and Echo Problem

### ISSUE THREAD

**Issue by harivyas35** [edumeet/edumeet#513]
Hi ,
I have deployed the software on aws (Specs 1gb ram ,1 core )and using it . Even after having around 10-15 participants there is too much connection drop and if more than 3 or 4 simultaneously keeps there audio on there is to much ECHO. Can you really help me with this.
Note : I don't have turn API configured , but i have Backup TURN server configured.

Regards,
Hari Vyas

**Comment by misi** [comment]
Try to add more cpu and memory. e.g. 4 cpu and 4Gig RAM.

**Comment by harivyas35** [comment]
Hi @misi,
Thank you for the reply.
Just a small question will this server config (4gb ram and 4 core ) handle atleast 40 participants in a room and around 300-400 participants concurrently. 

Regards,
Hari Vyas

**Comment by misi** [comment]
@harivyas35 
It is a good question:
AFAIK we does not finished yet our tests, to test the limitations of the system.
40 participant and  300 concurrently in one room should work.

**Comment by roman-drozd-it** [comment]
Explained. No new response much over 1 month.
