### ISSUE TITLE
Pease show a sample using Auth conf

### ISSUE THREAD

**Issue by bianxg** [edumeet/edumeet#520]
For example, how to configure an OpenID Connect provider such as google. Thanks.

auth :
	{
		lti :
		{
			consumerKey    : 'key',
			consumerSecret : 'secret'
		},
		oidc:
		{
			// The issuer URL for OpenID Connect discovery
			// The OpenID Provider Configuration Document
			// could be discovered on:
			// issuerURL + '/.well-known/openid-configuration'

			issuerURL     : 'https://example.com',
			clientOptions :
			{
				client_id     : '',
				client_secret : '',
				scope       		: 'openid email profile',
				// where client.example.com is your multiparty meeting server
				redirect_uri  : 'https://client.example.com/auth/callback'
			}

		}
	},

**Comment by misi** [comment]
@bianxg 
For google side setup see: 

- https://developers.google.com/identity/protocols/oauth2/openid-connect
- https://console.developers.google.com/

For eduMeet side you  need to have client_id and client_secret from google side
After it just copy inside the following config and replace you server FQDN
```js
oidc:
{
  issuerURL     : 'https://accounts.google.com/',
  clientOptions :
  {
  client_id     : '',
  client_secret : '',
  redirect_uri  : 'https://YOURSERVER_FQDN/auth/callback'
  }
}
```

**Comment by bianxg** [comment]
Thanks
