### ISSUE TITLE
How can I install LTI?

### ISSUE THREAD

**Issue by jhonforde** [edumeet/edumeet#522]
Hello, I want to use LTI for validation. However, there is no document to install the LTI system. How can I install an LTI system in the project? Is there a install document step by step ?

**Comment by misi** [comment]
@jhonforde 

Sorry for my delayed reply.

You don't need to install anything only configure the key/secret see: 
* https://github.com/edumeet/edumeet/blob/master/LTI/LTI.md

If I can help more please just let me know!
