### ISSUE TITLE
Moodle LTI user mapping problems

### ISSUE THREAD

**Issue by zmartinovic** [edumeet/edumeet#523]
We have a problem enabling user mapping when using Moodle LTI. We use this in our config:

	userMapping : async ({ peer, roomId, userinfo }) =>
	{
		if (userinfo.picture != null)
		{
			if (!userinfo.picture.match(/^http/g))
			{
				peer.picture = `data:image/jpeg;base64, ${userinfo.picture}`;
			}
			else
			{
				peer.picture = userinfo.picture;
			}
		}

		if (userinfo.nickname != null)
		{
			peer.displayName = userinfo.nickname;
		}

		if (userinfo.name != null)
		{
			peer.displayName = userinfo.name;
		}

		if (userinfo.email != null)
		{
			peer.email = userinfo.email;
		}
		
		if (userinfo.meet_roles.includes('Learner'))
		{
			peer.addRole(userRoles.AUTHENTICATED);
		}
		
		if (userinfo.meet_roles.includes('Instructor'))
		{
			peer.addRole(userRoles.MODERATOR);
		}
​
		if (userinfo.meet_roles.includes('Administrator'))
		{
			peer.addRole(userRoles.ADMIN);
		}
	},

but we get an error:
multiparty-meeting-server:ERROR room creation or room joining failed [error:"TypeError: Cannot read property 'includes' of undefined at Object.userMapping (/usr/local/src/multiparty-meeting/server/config/config.js:152:27) at /usr/local/src/multiparty-meeting/server/server.js:593:19 at processTicksAndRejections (internal/process/task_queues.js:97:5) at async AwaitQueue._runTask (/usr/local/src/multiparty-meeting/server/node_modules/awaitqueue/index.js:77:19) at async AwaitQueue._next (/usr/local/src/multiparty-meeting/server/node_modules/awaitqueue/index.js:57:3)"]

It seems like userinfo.meet_roles is not defined. Did anyone managed to enable roles mapping from Moodle?

Thanks,
Zvonko

**Comment by misi** [comment]
>Did anyone managed to enable roles mapping from Moodle?
Yes it works for me. => It should be some local configuration issue..

**Comment by zmartinovic** [comment]
Hi misi,

Can we get your config file (with excluded IPs and other auth data) so that we can compare it with our and check for the problem? Btw what Moodle version are you using? We are testing on Moodle 3.9.

Thanks,
Zvonko

**Comment by misi** [comment]
Try to double check that it is not commented out!
If I understand it correctly, Your error is about that it is missing the whole userMapping..

e.g.
```
        userMapping           : async ({ peer, roomId, userinfo }) =>
        {
                        if ( userinfo.lti && userinfo.lti.roles && userinfo.lti.roles.includes('Instructor')
                        )
                        {
                                        peer.addRole(userRoles.MODERATOR);
                        }
                        if (userinfo.picture != null)
                        {
                                        if (!userinfo.picture.match(/^http/g))
                                        {
                                                        peer.picture = `data:image/jpeg;base64, ${userinfo.picture}`;
                                        }
                                        else
                                        {
                                                        peer.picture = userinfo.picture;
                                        }
                        }

                        if (userinfo.nickname != null)
                        {
                                        peer.displayName = userinfo.nickname;
                        }

                        if (userinfo.name != null)
                        {
                                        peer.displayName = userinfo.name;
                        }

                        peer.addRole(userRoles.AUTHENTICATED);
        },
```

**Comment by zmartinovic** [comment]
Hi,

actually no, userMapping function is working, we get user fullname. Looking at your config I can see that we need to use userinfo.lti object and we tried to get roles from userinfo object like in example. We will try this now 👍 

Best,
Zvonko

**Comment by misi** [comment]
Let me know if you need more info..

**Comment by zmartinovic** [comment]
Thanks, we have just tried and now roles are working 👍 
Since we are here, just to ask how can we change the system language? Is there a full list of config values so that we can check them all?

Best regards,
Zvonko
