### ISSUE TITLE
Bug: Spotlights race

### ISSUE THREAD

**Issue by Astagor** [edumeet/edumeet#524]
Just not to loose the error we have identified. When users join at the same time, for example using the "join all from lobby" option, there is a race in the spotlights. It might happen that the notification about a user joining comes before the list of spotlights is being initialized by the room client from the current room state from server, then the user is not in the spotlights. This is how I have understood what is happening. @havfo

**Comment by roman-drozd-it** [comment]
Done regarding project 3.5
