### ISSUE TITLE
Server error on socket.io - net::ERR_CONNECTION_TIMED_OUT

### ISSUE THREAD

**Issue by kcsf** [edumeet/edumeet#527]
Hi,
We're trying to get this working on Linode/NGinx.

Here is the error in chrome console:
GET https://mydomain.com:8000/socket.io/?peerId=sv7v260g&roomId=znyzsnow&EIO=3&transport=polling&t=NGoIosp net::ERR_CONNECTION_TIMED_OUT

We've read everything we can find with regards.  Do you provide professional support?
We'd like to pay someone to jump on remote desktop and get this sorted out asap.

Thank you!

**Comment by havfo** [comment]
Try adding this to the nginx ws proxy config: `proxy_connect_timeout 75s;
 proxy_read_timeout 75s;
 proxy_send_timeout 75s;`

**Comment by misi** [comment]
We can try to help if you can explain more your setup. We provide professional support for free if you are related to Higher Education or Research.

**Comment by kcsf** [comment]
Thanks for responding so quickly guys.
I don't see where where to configure "nginx ws proxy".  If this is a necessary part of the config, where can I find it in the documentation?  Alternatively, it would be great if you would share a working copy of the nginx.conf file (with server blocks).

Here's mine (not fully working):

`user www-data;
worker_processes auto;
pid /run/nginx.pid;
include /etc/nginx/modules-enabled/*.conf;

events {
	worker_connections 768;
	# multi_accept on;
}

http {

	##
	# Basic Settings
	##

	sendfile on;
	tcp_nopush on;
	tcp_nodelay on;
	keepalive_timeout 75;
	types_hash_max_size 2048;
	# server_tokens off;

	# server_names_hash_bucket_size 64;
	# server_name_in_redirect off;

	include /etc/nginx/mime.types;
        default_type application/octet-stream;  


	##
	# SSL Settings
	##

  ssl_certificate /etc/ssl/cloudflare/star_mydomain_live.cert.pem;
  ssl_certificate_key /etc/ssl/cloudflare/star_mydomain_live.key;
	ssl_protocols TLSv1 TLSv1.1 TLSv1.2; # Dropping SSLv3, ref: POODLE
	ssl_prefer_server_ciphers on;
  ssl_session_cache   shared:SSL:10m;
  ssl_session_timeout 10m;

	##
	# Logging Settings
	##

	access_log /var/log/nginx/access.log;
	error_log /var/log/nginx/error.log;

	##
	# Gzip Settings
	##

	gzip on;

	# gzip_vary on;
	# gzip_proxied any;
	# gzip_comp_level 6;
	# gzip_buffers 16 8k;
	# gzip_http_version 1.1;
	# gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

  index index.html;
  
	##
	# Virtual Host Configs
	##

	include /etc/nginx/conf.d/*.conf;
	include /etc/nginx/sites-enabled/*;
 
  
}`

and here's the basic server block.conf

`server {
    listen       80;
    listen       [::]:80;
    listen       443 ssl;
    listen       [::]:443;
    server_name  mydomain.com;
    access_log   /var/log/nginx/mydomain.com.access.log;
    error_log    /var/log/nginx/mydomain.com error;
    
    add_header 'Access-Control-Allow-Origin' '*';
    
    root         /var/www/mydomain.com/multiparty-meeting/app/build/;
    index  index.html;

    }`

**Comment by havfo** [comment]
Having a NGINX proxy is not something we have documentation for. It is supported in the same way that HAProxy is supported. To make it work you need to configure NGINX to proxy-pass websocket to the edumeet server.

**Comment by kcsf** [comment]
Is a proxy even necessary?
I'm just trying to get the basic initial installation up and running.  If a proxy config on the server is only necessary for larger groups, then - how do I shut it off?  Is there any other reason I would be getting this Server error on socket.io problem?

Alternatively, I'd just as soon scrap the linode/nginx server and start from scratch with something you have documenation for.  What do you recommend?  Digital Ocean w/Ubuntu & Apache?  Something else?

I'm also happy to pay one of you guys to jump on remote desktop and help sort this out.  Do you do slack or hangouts?  Do you have a scheduling system for picking a time to connect?

**Comment by so010** [comment]
> Is a proxy even necessary?
> I'm just trying to get the basic initial installation up and running. If a proxy config on the server is only necessary for larger groups, then - how do I shut it off? Is there any other reason I would be getting this Server error on socket.io problem?

It is not necessary. Just uninstall/deactivate your nginx and let edumeet serve directly.

**Comment by misi** [comment]
I think this question is solved my conclusion stop nginx and run edumeet directly. If there is any open question please open a new issue. Thanks!
