### ISSUE TITLE
Unable to Join Room

### ISSUE THREAD

**Issue by AugustoZanoni** [edumeet/edumeet#528]
I'm getting trouble with something, i've follow the steps to run with the correct config, but when I join the room, after about 1 second i get the notification "Unable to Join Room" and get redirected to root page. My ports are config:

`listeningPort         : 3443,
listeningRedirectPort : 8080,
turnAPIKey    : 'examplekey',
	turnAPIURI    : 'turn:numb.viagenie.ca',
	turnAPIparams : {
		'uri_schema' 	: 'turn',
		'transport' 		: 'tcp',
		'ip_ver'    		: 'ipv4',
		'servercount'	: '2'
	},

	// Backup turnservers if REST fails or is not configured
	backupTurnServers : [
		{
			urls : [
				'turn:numb.viagenie.ca'
			],
			username   : 'webrtc@live.com',
			credential : 'muazkh'
		}
	],
	fileTracker  : 'wss://tracker.lab.vvc.niif.hu:443',`

I've opened in dev, and got the log:

![image](https://user-images.githubusercontent.com/49280362/91626493-e596aa00-e985-11ea-8a98-c219e93b1073.png)

I've tried to run on docker but got the same problem

**Comment by pierguinzani** [comment]
Hey @AugustoZanoni. Take a look at this solution #529 , it might work for you.

**Comment by asim47** [comment]
@AugustoZanoni  did you find its solution?

**Comment by AugustoZanoni** [comment]
> @AugustoZanoni  did you find its solution?

Yes, sure. @pierguinzani posted a solution that helped me. You got to set your ip address locally of u want to test on your machine and set ur public IP if u want to deploy like this: {private:'192.168.0.1', announced:'172.999.9.99'}

You can comment on the turn server configs. It will use only stun servers. It's only needed to change the port on the server config. Because the app config it's already set 4443 for development. Hope it helps. Check the issue @pierguinzani  mentioned for further details
