### ISSUE TITLE
How to add authenticate users via a username and password using passport-local 

### ISSUE THREAD

**Issue by bianxg** [edumeet/edumeet#531]
Does anyone add this feature?  I add some code to server.js, but not work.
Also how to limit user join room only after login? Thanks

async function setupLocalAuth()
{
	// Configure the local strategy for use by Passport.
	//
	// The local strategy require a `verify` function which receives the credentials
	// (`username` and `password`) submitted by the user.  The function must verify
	// that the password is correct and then invoke `cb` with a user object, which
	// will be set at `req.user` in route handlers after authentication.
	passport.use(new LocalStrategy(
		function (username, password, cb) {
			db.users.findByUsername(username, function (err, user) {
				if (err) { return cb(err); }
				if (!user) { return cb(null, false); }
				if (user.password != password) { return cb(null, false); }
				return cb(null, user);
			});
		}));

	// Configure Passport authenticated session persistence.
	//
	// In order to restore authentication state across HTTP requests, Passport needs
	// to serialize users into and deserialize users out of the session.  The
	// typical implementation of this is as simple as supplying the user ID when
	// serializing, and querying the user record by ID from the database when
	// deserializing.
	passport.serializeUser(function (user, cb) {
		cb(null, user.id);
	});

	passport.deserializeUser(function (id, cb) {
		db.users.findById(id, function (err, user) {
			if (err) { return cb(err); }
			cb(null, user);
		});
	});
	
	app.use(passport.initialize());
	app.use(passport.session());

	// Define routes.
	app.get('/auth/login',
		(req, res) => {
			//logger.warn('login  %o',req.query.state);
			//logger.warn('login  %o',req.query);
			//const state = JSON.parse(base64.decode(req.query.state));
			const { peerId, roomId } = req.query;
			res.render('login',{peerId:peerId,roomId:roomId});
		});

	app.post('/auth/login',
		passport.authenticate('local', { failureRedirect: '/auth/login' }),
		async (req, res,next) => {
			try
			{				
				//const state = JSON.parse(base64.decode(req.query.state));

				//const { peerId, roomId } = state;
				const peerId = req.body.peerId;
				const roomId = req.body.roomId;

				req.session.peerId = peerId;
				req.session.roomId = roomId;

				let peer = peers.get(peerId);

				if (!peer) // User has no socket session yet, make temporary
					peer = new Peer({ id: peerId, roomId });

				if (peer.roomId !== roomId) // The peer is mischievous
					throw new Error('peer authenticated with wrong room');

				//logger.info('[login user: "%o"]', req.user);
				//logger.info('-----------------------------');
				//logger.info('[peer: "%o"]', peer);
				//logger.info('-----------------------------');

				let _userinfo = {};
				_userinfo.name = req.user.username;
				if (req.user.emails.length > 0)
					_userinfo.email = req.user.emails[0].value;
				_userinfo.picture=null;

				if (typeof config.userMapping === 'function')
				{
					await config.userMapping({
						peer,
						roomId,
						userinfo : _userinfo
					});
				}

				peer.authenticated = true;

				logger.info('[peer update: "%o"]', peer);
				logger.info('-----------------------------');

				res.send(loginHelper({
					displayName : peer.displayName,
					picture     : peer.picture
				}));
			}
			catch (error)
			{
				return next(error);
			}
		});
}

**Comment by bianxg** [comment]
The process is as below:
1) after click "Log in" button, open a new browser window (or tab)
![image](https://user-images.githubusercontent.com/3364079/91958728-50573500-ed3a-11ea-8a5f-514db7fca042.png)
2) submit with correct username and password 
3) server will call 
app.post('/auth/login',
		passport.authenticate('local', { failureRedirect: '/auth/login' }),
		async (req, res,next) => 
4)then call (authenticate ok)
res.send(loginHelper({
					displayName : peer.displayName,
					picture     : peer.picture
				}));
5) at this time, user is loged in (the Login button is green now)
6) click "AUDIO AND VIDEO" button to join room
But the react page is refreshed and the access address is changed to "https://192.168.2.40:3443/?displayName=Jack"

I don't know why the react page is refreshed after authenticate. Please help. Thanks.

**Comment by bianxg** [comment]
![image](https://user-images.githubusercontent.com/3364079/91960625-b644bc00-ed3c-11ea-8260-54eac2a7350f.png)

**Comment by bianxg** [comment]
The reason is that, the user info that I used in passport-local is different with OAuth2. This will result in websocket close which will refresh the page. The last question, how can I limit user create or join room only after login? 

Boolean(socket.handshake.session.passport) &&
		Boolean(socket.handshake.session.passport.user)
			)
			{
				logger.info('socket.handshake.session.passport: "%o"',socket.handshake.session.passport);
				logger.info('socket.handshake.session.passport.user: "%o"',socket.handshake.session.passport.user);
				
				const {
					id,
					displayName,
					picture,
					email,
					_userinfo
				} = socket.handshake.session.passport.user;

**Comment by so010** [comment]
Did you have a look at the userMapping and accessFromRoles function examples in https://github.com/edumeet/edumeet/blob/master/server/config/config.example.js
This function is called for each user and you can do there whatever you want.
I think for your question the first example should do:
userMapping : async ({ peer, roomId, userinfo }) =>
	{
		peer.addRole(userRoles.MODERATOR);
		peer.addRole(userRoles.AUTHENTICATED);
	},

in combination with:
accessFromRoles : {
		// The role(s) will gain access to the room
		// even if it is locked (!)
		[BYPASS_ROOM_LOCK] : [ userRoles.ADMIN ],
		// The role(s) will gain access to the room without
		// going into the lobby. If you want to restrict access to your
		// server to only directly allow authenticated users, you could
		// add the userRoles.AUTHENTICATED to the user in the userMapping
		// function, and change to BYPASS_LOBBY : [ userRoles.AUTHENTICATED ]
		[BYPASS_LOBBY]     : [ userRoles.ATHENTICATED ]
	},

**Comment by bianxg** [comment]
I find the reason of redirect after login . ( https://192.168.2.40:3443/?displayName=jack)

app.all('*', async (req, res, next) =>
	{		
		if (req.secure || config.httpOnly)
		{
			let ltiURL;

			try
			{
				ltiURL = new URL(`${req.protocol }://${ req.get('host') }${req.originalUrl}`);
			}
			catch (error)
			{
				logger.error('Error parsing LTI url: %o', error);
			}

			if (
				req.isAuthenticated &&
				req.user &&
				req.user.displayName &&
				!ltiURL.searchParams.get('displayName') &&
				!isPathAlreadyTaken(req.url)
			)
			{

				ltiURL.searchParams.append('displayName', req.user.displayName);

				res.redirect(ltiURL);
