### ISSUE TITLE
Question: changing the language

### ISSUE THREAD

**Issue by zmartinovic** [edumeet/edumeet#532]
Hi,

what is the config to change the eduMeet language? I have looked but couldn't find the setting :) Also, is it in app or server config where we set this option?

Thanks,
Zvonko

**Comment by havfo** [comment]
The language is chosen automatically based on your browser locale, there is no way of setting it manually at this time.

**Comment by zmartinovic** [comment]
Thanks for the info :) Then I will vote for the in app lang menu as a new feature :)
