### ISSUE TITLE
How to deploy on server?

### ISSUE THREAD

**Issue by callmemonky** [edumeet/edumeet#533]
What changes do I need to make to get it up and running on the server.

I've configured the server. I'm also attaching my config file. But somehow I'm not able to access the app on Public IP of my VPS.

(PS: This is my first time hosting)

Here are the exact steps I've followed.
My server's Local IP : 172.17.96.82 
I have a public IP Address

1. I cloned repository at path "/home"
2. Made changes to Config files (attached below)
3. I did npm install in both app and sever folders.
4. npm run build in app folder
5. redis-server (in first terminal)
6. npm start (in second terminal) in server folder.
7. npm start (in third terminal) in app folder.

So technically I should be getting my app at _publicip:443_ port (tried all the ports, nothing)

Here's my config file (important snippets)

`const os = require("os");
const userRoles = require("../userRoles");

const { BYPASS_ROOM_LOCK, BYPASS_LOBBY } = require("../access");

const {
  CHANGE_ROOM_LOCK,
  PROMOTE_PEER,
  SEND_CHAT,
  MODERATE_CHAT,
  SHARE_SCREEN,
  EXTRA_VIDEO,
  SHARE_FILE,
  MODERATE_FILES,
  MODERATE_ROOM,
} = require("../permissions");

// const AwaitQueue = require('awaitqueue');
// const axios = require('axios');

module.exports = {
  // Auth conf
  /*
    	auth :
	{
                lti :
                {
                        consumerKey    : 'key',
                        consumerSecret : 'secret'
                },
                oidc:
                {
                        // The issuer URL for OpenID Connect discovery
                        // The OpenID Provider Configuration Document
                        // could be discovered on:
                        // issuerURL + '/.well-known/openid-configuration'

                        issuerURL     : 'https://example.com',
                        clientOptions :
                        {
                                client_id     : '',
                                client_secret : '',
                                scope                   : 'openid email profile',
                                // where client.example.com is your multiparty meeting server
                                redirect_uri  : 'https://client.example.com/auth/callback'
                        }

                }
        },
`

`// URI and key for requesting geoip-based TURN server closest to the client
  turnAPIKey: "examplekey",
  turnAPIURI: "turn:numb.viagenie.ca",
  turnAPIparams: {
    uri_schema: "turn",
    transport: "tcp",
    ip_ver: "ipv4",
    servercount: "2",
  },

  // Backup turnservers if REST fails or is not configured
  backupTurnServers: [
    {
      urls: ["turn:numb.viagenie.ca"],
      username: "webrtc@live.com",
      credential: "muazkh",
    },
  ],

  fileTracker: "wss://tracker.lab.vvc.niif.hu:443",
  redisOptions: {},
  // session cookie secret
  cookieSecret: "T0P-S3cR3t_cook!e",
  cookieName: "multiparty-meeting.sid",
  // if you use encrypted private key the set the passphrase
  tls: {
    cert: `${__dirname}/../certs/cert.pem`,
    // passphrase: 'key_password'
    key: `${__dirname}/../certs/privkey.pem`,
  },
  // listening Host or IP
  // If omitted listens on every IP. ("0.0.0.0" and "::")
  // listeningHost: 'localhost',
  // Listening port for https server.
  listeningPort: 443,
  // Any http request is redirected to https.
  // Listening port for http server.
  listeningRedirectPort: 80,
  // Listens only on http, only on listeningPort
  // listeningRedirectPort disabled
  // use case: loadbalancer backend
  httpOnly: false,
  // WebServer/Express trust proxy config for httpOnly mode
  // You can find more info:
  //  - https://expressjs.com/en/guide/behind-proxies.html
  //  - https://www.npmjs.com/package/proxy-addr
  // use case: loadbalancer backend
  trustProxy: "",
  // This logger class will have the log function
`

`// mediasoup WebRtcTransport settings.
    webRtcTransport: {
      listenIps: [
        // change 192.0.2.1 IPv4 to your server's IPv4 address!!
        { ip: "172.17.96.82", announcedIp: null },

        // Can have multiple listening interfaces
        // change 2001:DB8::1 IPv6 to your server's IPv6 address!!
        // { ip: '2001:DB8::1', announcedIp: null }
      ],
      initialAvailableOutgoingBitrate: 1000000,
      minimumAvailableOutgoingBitrate: 600000,
      // Additional options that are not part of WebRtcTransportOptions.
      maxIncomingBitrate: 1500000,
    },
  },
  // Prometheus exporter
  /*
    	prometheus: {
                deidentify: false, // deidentify IP addresses
                numeric: false, // show numeric IP addresses
                port: 8889, // allocated port
                quiet: false // include fewer labels
        }
	*/
};
`

Also, this is how my multiparty-meeting.service looks like.

```
[Unit]
Description=multiparty-meeting is a audio / video meeting service running in the browser and powered $
After=network.target

[Service]
ExecStart=/home/pingping/server/server.js
Restart=always
User=nobody
Group=nogroup
Environment=PATH=/usr/bin:/usr/local/bin
Environment=NODE_ENV=production
WorkingDirectory=/home/pingping/server
AmbientCapabilities=CAP_NET_BIND_SERVICE

[Install]
WantedBy=multi-user.target

```

``

**Comment by harivyas35** [comment]
Hi @callmemonky ,
Do you know the internal working of this application.

**Comment by callmemonky** [comment]
> Hi @callmemonky ,
> Do you know the internal working of this application.
> 

Yeah. I'm working on it. Why did you ask?

**Comment by harivyas35** [comment]
Hi @callmemonky ,
If you know the internal working of this application then you should not face any issue to deploy it on server .
I would really encourage you to please read the documentation of the technology on which this app is based upon. 

Regards

**Comment by callmemonky** [comment]
I think it's more of server side things than app working.

I would appreciate you directing me in a right direction..as it will save a lot of time and energy. Plus definitely gonna learn from it.

**Comment by so010** [comment]
How do you start your server?
your configured user (nobody) in multiparty-meeting.service is not allowed to listen on privileged ports like 443 or 80
Recommended for this is either to configure unprevileged ports and make a firewallrule
iptables -A PREROUTING -i bond0 -p tcp -m tcp --dport 443 -j REDIRECT --to-ports 4443
iptables -A PREROUTING -i bond0 -p tcp -m tcp --dport 80 -j REDIRECT --to-ports 8080

or allow the configured user access to these ports via systemd config (I don't know how to do this).

**Comment by callmemonky** [comment]
@so010 hey Stefan! I ran those commands..didn't work. Can you guide how to deploy?

**Comment by pierguinzani** [comment]
Hey, @callmemonky.  I have the same problem. I'm using the docker on AWS. This solution https://github.com/edumeet/edumeet/issues/508 seems to have solved this guy's, but it didn't work for me. See if it works for you. Basically what he did, in addition to defining the turn server, was defining the external ip there in announcedIp:
![image](https://user-images.githubusercontent.com/49373874/91975797-56c3bd80-ecf6-11ea-9de1-9d60d69d4ae9.png)

**Comment by callmemonky** [comment]
> Hey, @callmemonky.  I have the same problem. I'm using the docker on AWS. This solution https://github.com/edumeet/edumeet/issues/508 seems to have solved this guy's, but it didn't work for me. See if it works for you. Basically what he did, in addition to defining the turn server, was defining the external ip there in announcedIp:
> ![image](https://user-images.githubusercontent.com/49373874/91975797-56c3bd80-ecf6-11ea-9de1-9d60d69d4ae9.png)
> 

Not working.

**Comment by so010** [comment]
> @so010 hey Stefan! I ran those commands..didn't work. Can you guide how to deploy?

the iptables command depends on how your firewall is configured but "bond0" here is the local network interface which is in your case different I assume, run "ip a" to check your interfaces. It depends as well how your VPS is setting up network for your servers. So if local ip is different from public ip then you need to define public ip for announcedIp.
You can as well check logging.

**Comment by so010** [comment]
> or allow the configured user access to these ports via systemd config (I don't know how to do this).

This seems to do this (not tested)
https://stbuehler.de/blog/article/2017/06/23/systemd__allow_normal_process_to_bind_to_privileged_port.html

and an alternative:
https://liquidat.wordpress.com/2018/01/04/howto-run-programs-as-non-root-user-on-privileged-ports-via-systemd/

**Comment by pierguinzani** [comment]
Not Working for me :/

**Comment by eshpilevsky** [comment]
https://github.com/edumeet/edumeet/issues/541 @pierguinzani @callmemonky @so010 @harivyas35 @ibc Help me please!

**Comment by ibc** [comment]
> I can't connect to the video conference -> #541 [...] @ibc Help me please!

Please don't do that again.

**Comment by so010** [comment]
logs?

**Comment by eshpilevsky** [comment]
- process.env.DEBUG: undefined
- config.mediasoup.worker.logLevel: warn
- config.mediasoup.worker.logTags: [ 'info', 'ice', 'dtls', 'rtp', 'srtp', 'rtcp' ]
(node:19044) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated

**Comment by pierguinzani** [comment]
@eshpilevsky, Check if the port used in the application is already being used.

**Comment by misi** [comment]
If you can't connect on TCP to port 80 to your VPS is your local issue. Please solve it with your VPS provider.
```
I've configured the server. I'm also attaching my config file. But somehow I'm not able to access the app on Public IP of my VPS.
```
If you configure according our documentation and your VPS NAT settings are correct, you should be able to connect to port TCP 80 and 443.
I don't think we can help you more on it, because your issue is likely not bug in our sw. Please open a separate issue with a exact problem statement, and we will try to help.
