### ISSUE TITLE
How to deploy this app on VPS?

### ISSUE THREAD

**Issue by callmemonky** [edumeet/edumeet#534]
Hey I am trying to deploy this app on VPS. I'm noob at this. Would appreciate someone guide through the process.

**Comment by so010** [comment]
This depends completely what kind of VPS you have. Usually network is a issue there because these services are behind NAT.
You have to find public IP and local IP (command 'ip a') of your server and configure in server/config/config.js:
webRtcTransport :
		{
			listenIps :
			[
				{ ip: 'local IP', announcedIp: 'public IP' }

**Comment by misi** [comment]
I think VPS could have global IP. We provide direct support only for education and research (NREN) community. Otherwise please go to mailinglist to get more support.
