### ISSUE TITLE
Hi load problem.

### ISSUE THREAD

**Issue by eshpilevsky** [edumeet/edumeet#535]
Our server has 8 cores, 32GB of RAM, 20GB of hard drive. When there are 10 people in the room, everything starts to freeze and throw out the participants who want to connect. Tell me, please, what can it be? We need 30 people maximum to be able to communicate in one room and at the same time 300 people. What kind of server do we need in terms of capacity? and how to set up the current one, since with such capacities even 10 people cannot communicate normally, this is strange, apparently you need to set up somehow or something else, please tell me. Thank! Our link: https: //newedutech.xyz

**Comment by so010** [comment]
What bandwidth do you have on serverside?

**Comment by eshpilevsky** [comment]
@so010 100 Mbps

**Comment by so010** [comment]
> @so010 100 Mbps

That explains your problem! Some background information you can read in the wiki:
https://github.com/edumeet/edumeet/wiki/Scaling-and-recommended-Hardware

Enough bandwidth is necessary for such services. I don't understand your needs: 30 active participants visible at the same time for 300 passive participants will not be possible with your bandwidth. 
Your bandwidth could be enough for:
30 participants with 2 active visible speakers with medium resolution at 200kbps at the same time:
2 active participants * (300kbps (video) ' 12 kbps (audio)) * 30 passive participants = around 20mbps
Then there is a margin for slightly more participant or higher bandwidth.



Some tuning suggestions:

Try to tune your settings in server config
https://github.com/edumeet/edumeet/blob/master/server/config/config.example.js
- maxIncomingBitrate to 300000
- initialAvailableOutgoingBitrate : 100000


In App config you can try lastN settings lower than 4
and 	
simulcast                     : false,
https://github.com/edumeet/edumeet/blob/master/app/public/config/config.example.js

**Comment by eshpilevsky** [comment]
@so010 Let me give you an example: we have created 5 rooms, in each of which 15 people should communicate. Is 100 Mbps enough for this? 

With my configuration so far of 8 cores, 32GB of RAM, 100mg of server bandwidth, I can only create one room that can barely hold 10 people and everything starts to freeze.

**Comment by so010** [comment]
15participants * ( 300kbps + 12kbps) * 3 active participants * 5 rooms  = ca 70mbps

This could work if you tweak config as I suggested
