### ISSUE TITLE
1) I cloned the repo and performed all of these steps:

### ISSUE THREAD

**Issue by sajalsoumalya** [edumeet/edumeet#538]
1) I cloned the repo and performed all of these steps:
![image](https://user-images.githubusercontent.com/49373874/91720485-9ca14a00-eb6d-11ea-9efe-802a4e5a8d67.png)

2) Then, I went to the  directory
```
/edumeet/server/certs
```
 and generated a new cert and private key with the following command:
```
openssl req -x509 -newkey rsa:4096 -keyout privkey.pem -out cert.pem -days 365 -nodes -subj '/CN=localhost' 
```
![image](https://user-images.githubusercontent.com/49373874/91723491-3834b980-eb72-11ea-90b9-32d6120882f0.png)
Generating these two files here in the certs folder
![image](https://user-images.githubusercontent.com/49373874/91724107-30294980-eb73-11ea-92b6-a0853f2bdbf3.png)
3) 
Soon after, I added a turn/stun server 
* If using coturn, you can generate a user and key with:
```
$ turnadmin -k -u <username> -p <password>
```
For testing purposes, use this:
```
	
		{
			urls : [
				'turn:numb.viagenie.ca'
			],
			username   : 'webrtc@live.com',
			credential : 'muazkh'
		}
	
```

My final server configuration file (configs / server / config.js) looks like this:

```
const os = require('os');
const userRoles = require('../userRoles');

const {
	BYPASS_ROOM_LOCK,
	BYPASS_LOBBY
} = require('../access');

const {
	CHANGE_ROOM_LOCK,
	PROMOTE_PEER,
	SEND_CHAT,
	MODERATE_CHAT,
	SHARE_SCREEN,
	EXTRA_VIDEO,
	SHARE_FILE,
	MODERATE_FILES,
	MODERATE_ROOM
} = require('../permissions');

// const AwaitQueue = require('awaitqueue');
// const axios = require('axios');

module.exports =
{

	// URI and key for requesting geoip-based TURN server closest to the client
	turnAPIKey    : 'examplekey',
	turnAPIURI    : 'turn:numb.viagenie.ca',
	turnAPIparams : {
		'uri_schema' 	: 'turn',
		'transport' 		: 'tcp',
		'ip_ver'    		: 'ipv4',
		'servercount'	: '2'
	},

	// Backup turnservers if REST fails or is not configured
	backupTurnServers : [
		{
			urls : [
				'turn:numb.viagenie.ca'
			],
			username   : 'webrtc@live.com',
			credential : 'muazkh'
		}
	],
	fileTracker  : 'wss://tracker.lab.vvc.niif.hu:443',
	redisOptions : {},
	// session cookie secret
	cookieSecret : 'T0P-S3cR3t_cook!e',
	cookieName   : 'new-edutech.sid',
	// if you use encrypted private key the set the passphrase
	tls          :
	{
		cert : `/home/pier/Documentos/edumeet/server/certs/cert.pem`,
		// passphrase: 'key_password'
		key  : `/home/pier/Documentos/edumeet/server/certs/key.pem`
	},
	// listening Host or IP
	// If omitted listens on every IP. ("0.0.0.0" and "::")
	//listeningHost					: 'localhost',
	// Listening port for https server.
	listeningPort         : 3443,
	// Any http request is redirected to https.
	// Listening port for http server.
	listeningRedirectPort : 8080,
	// Listens only on http, only on listeningPort
	// listeningRedirectPort disabled
	// use case: loadbalancer backend
	httpOnly              : false,
	// WebServer/Express trust proxy config for httpOnly mode
	// You can find more info:
	//  - https://expressjs.com/en/guide/behind-proxies.html
	//  - https://www.npmjs.com/package/proxy-addr
	// use case: loadbalancer backend
	trustProxy            : '',
	// This logger class will have the log function
	// called every time there is a room created or destroyed,
	// or peer created or destroyed. This would then be able
	// to log to a file or external service.
	/* StatusLogger          : class
	{
		constructor()
		{
			this._queue = new AwaitQueue();
		}
		// rooms: rooms object
		// peers: peers object
		// eslint-disable-next-line no-unused-vars
		async log({ rooms, peers })
		{
			this._queue.push(async () =>
			{
				// Do your logging in here, use queue to keep correct order
				// eslint-disable-next-line no-console
				console.log('Number of rooms: ', rooms.size);
				// eslint-disable-next-line no-console
				console.log('Number of peers: ', peers.size);
			})
				.catch((error) =>
				{
					// eslint-disable-next-line no-console
					console.log('error in log', error);
				});
		}
	}, */
	// This function will be called on successful login through oidc.
	// Use this function to map your oidc userinfo to the Peer object.
	// The roomId is equal to the room name.
	// See examples below.
	// Examples:
	/*
	// All authenicated users will be MODERATOR and AUTHENTICATED
	userMapping : async ({ peer, roomId, userinfo }) =>
	{
		peer.addRole(userRoles.MODERATOR);
		peer.addRole(userRoles.AUTHENTICATED);
	},
	// All authenicated users will be AUTHENTICATED,
	// and those with the moderator role set in the userinfo
	// will also be MODERATOR
	userMapping : async ({ peer, roomId, userinfo }) =>
	{
		if (
			Array.isArray(userinfo.meet_roles) &&
			userinfo.meet_roles.includes('moderator')
		)
		{
			peer.addRole(userRoles.MODERATOR);
		}
		if (
			Array.isArray(userinfo.meet_roles) &&
			userinfo.meet_roles.includes('meetingadmin')
		)
		{
			peer.addRole(userRoles.ADMIN);
		}
		peer.addRole(userRoles.AUTHENTICATED);
	},
	// All authenicated users will be AUTHENTICATED,
	// and those with email ending with @example.com
	// will also be MODERATOR
	userMapping : async ({ peer, roomId, userinfo }) =>
	{
		if (userinfo.email && userinfo.email.endsWith('@example.com'))
		{
			peer.addRole(userRoles.MODERATOR);
		}
		peer.addRole(userRoles.AUTHENTICATED);
	}
	// All authenicated users will be AUTHENTICATED,
	// and those with email ending with @example.com
	// will also be MODERATOR
	userMapping : async ({ peer, roomId, userinfo }) =>
	{
		if (userinfo.email && userinfo.email.endsWith('@example.com'))
		{
			peer.addRole(userRoles.MODERATOR);
		}
		peer.addRole(userRoles.AUTHENTICATED);
	},
	*/
	// eslint-disable-next-line no-unused-vars
	userMapping           : async ({ peer, roomId, userinfo }) =>
	{
		if (userinfo.picture != null)
		{
			if (!userinfo.picture.match(/^http/g))
			{
				peer.picture = `data:image/jpeg;base64, ${userinfo.picture}`;
			}
			else
			{
				peer.picture = userinfo.picture;
			}
		}

		if (userinfo.nickname != null)
		{
			peer.displayName = userinfo.nickname;
		}

		if (userinfo.name != null)
		{
			peer.displayName = userinfo.name;
		}

		if (userinfo.email != null)
		{
			peer.email = userinfo.email;
		}
	},
	// All users have the role "NORMAL" by default. Other roles need to be
	// added in the "userMapping" function. The following accesses and
	// permissions are arrays of roles. Roles can be changed in userRoles.js
	//
	// Example:
	// [ userRoles.MODERATOR, userRoles.AUTHENTICATED ]
	accessFromRoles : {
		// The role(s) will gain access to the room
		// even if it is locked (!)
		[BYPASS_ROOM_LOCK] : [ userRoles.ADMIN ],
		// The role(s) will gain access to the room without
		// going into the lobby. If you want to restrict access to your
		// server to only directly allow authenticated users, you could
		// add the userRoles.AUTHENTICATED to the user in the userMapping
		// function, and change to BYPASS_LOBBY : [ userRoles.AUTHENTICATED ]
		[BYPASS_LOBBY]     : [ userRoles.NORMAL ]
	},
	permissionsFromRoles : {
		// The role(s) have permission to lock/unlock a room
		[CHANGE_ROOM_LOCK] : [ userRoles.MODERATOR ],
		// The role(s) have permission to promote a peer from the lobby
		[PROMOTE_PEER]     : [ userRoles.NORMAL ],
		// The role(s) have permission to send chat messages
		[SEND_CHAT]        : [ userRoles.NORMAL ],
		// The role(s) have permission to moderate chat
		[MODERATE_CHAT]    : [ userRoles.MODERATOR ],
		// The role(s) have permission to share screen
		[SHARE_SCREEN]     : [ userRoles.NORMAL ],
		// The role(s) have permission to produce extra video
		[EXTRA_VIDEO]      : [ userRoles.NORMAL ],
		// The role(s) have permission to share files
		[SHARE_FILE]       : [ userRoles.NORMAL ],
		// The role(s) have permission to moderate files
		[MODERATE_FILES]   : [ userRoles.MODERATOR ],
		// The role(s) have permission to moderate room (e.g. kick user)
		[MODERATE_ROOM]    : [ userRoles.MODERATOR ]
	},
	// Array of permissions. If no peer with the permission in question
	// is in the room, all peers are permitted to do the action. The peers
	// that are allowed because of this rule will not be able to do this
	// action as soon as a peer with the permission joins. In this example
	// everyone will be able to lock/unlock room until a MODERATOR joins.
	allowWhenRoleMissing : [ CHANGE_ROOM_LOCK ],
	// When truthy, the room will be open to all users when as long as there
	// are allready users in the room
	activateOnHostJoin   : true,
	// When set, maxUsersPerRoom defines how many users can join
	// a single room. If not set, there is no limit.
	// maxUsersPerRoom    : 20,
	// Room size before spreading to new router
	routerScaleSize      : 40,
	// Socket timout value
	requestTimeout       : 20000,
	// Socket retries when timeout
	requestRetries       : 3,
	// Mediasoup settings
	mediasoup            :
	{
		numWorkers : Object.keys(os.cpus()).length,
		// mediasoup Worker settings.
		worker     :
		{
			logLevel : 'warn',
			logTags  :
			[
				'info',
				'ice',
				'dtls',
				'rtp',
				'srtp',
				'rtcp'
			],
			rtcMinPort : 40000,
			rtcMaxPort : 49999
		},
		// mediasoup Router settings.
		router :
		{
			// Router media codecs.
			mediaCodecs :
			[
				{
					kind      : 'audio',
					mimeType  : 'audio/opus',
					clockRate : 48000,
					channels  : 2
				},
				{
					kind       : 'video',
					mimeType   : 'video/VP8',
					clockRate  : 90000,
					parameters :
					{
						'x-google-start-bitrate' : 1000
					}
				},
				{
					kind       : 'video',
					mimeType   : 'video/VP9',
					clockRate  : 90000,
					parameters :
					{
						'profile-id'             : 2,
						'x-google-start-bitrate' : 1000
					}
				},
				{
					kind       : 'video',
					mimeType   : 'video/h264',
					clockRate  : 90000,
					parameters :
					{
						'packetization-mode'      : 1,
						'profile-level-id'        : '4d0032',
						'level-asymmetry-allowed' : 1,
						'x-google-start-bitrate'  : 1000
					}
				},
				{
					kind       : 'video',
					mimeType   : 'video/h264',
					clockRate  : 90000,
					parameters :
					{
						'packetization-mode'      : 1,
						'profile-level-id'        : '42e01f',
						'level-asymmetry-allowed' : 1,
						'x-google-start-bitrate'  : 1000
					}
				}
			]
		},
		// mediasoup WebRtcTransport settings.
		webRtcTransport :
		{
			listenIps :
			[
				// change 192.0.2.1 IPv4 to your server's IPv4 address!!
				{ ip: '192.168.1.3', announcedIp: null }

				// Can have multiple listening interfaces
				// change 2001:DB8::1 IPv6 to your server's IPv6 address!!
				// { ip: '2001:DB8::1', announcedIp: null }
			],
			initialAvailableOutgoingBitrate : 1000000,
			minimumAvailableOutgoingBitrate : 600000,
			// Additional options that are not part of WebRtcTransportOptions.
			maxIncomingBitrate              : 1500000
		}
	}
	// Prometheus exporter
	/*
	prometheus: {
		deidentify: false, // deidentify IP addresses
		numeric: false, // show numeric IP addresses
		port: 8889, // allocated port
		quiet: false // include fewer labels
	}
	*/
};
```

_Originally posted by @pierguinzani in https://github.com/edumeet/edumeet/issues/529#issuecomment-683837746_

Git Clone Link Is Not Working  i need the Stable working Link

**Comment by bianxg** [comment]
It's sure that the git version can work fine.  Just follow steps in README.md. Need not turn/stun server when first test.

**Comment by pierguinzani** [comment]
What error appears when trying to give the following command?
```
git clone https://github.com/edumeet/edumeet.git
```

**Comment by livingloves** [comment]
> What error appears when trying to give the following command?
> 
> ```
> git clone https://github.com/edumeet/edumeet.git
> ```

Than It Worked

**Comment by livingloves** [comment]
if Want to Deploay it On My VPS then Also The '/CN=localhost' ?

`openssl req -x509 -newkey rsa:4096 -keyout privkey.pem -out cert.pem -days 365 -nodes -subj '/CN=localhost'`

**Comment by livingloves** [comment]
`root@jisu-Conv:/home/admin/edumeet/app# npm install
npm WARN deprecated @formatjs/intl-unified-numberformat@3.3.7: We have renamed the package to @formatjs/intl-numberformat
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated @hapi/joi@15.1.1: joi is leaving the @hapi organization and moving back to 'joi' (https://github.com/sideway/joi/issues/2411)
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated core-js@1.2.7: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated @hapi/address@2.1.4: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/topo@3.1.6: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/bourne@1.3.2: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated left-pad@1.3.0: use String.prototype.padStart()
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules/react-scripts/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"ia32"})
npm WARN notsup Unsupported engine for browserslist@4.14.2: wanted: {"node":"^6 || ^7 || ^8 || ^9 || ^10 || ^11 || ^12 || >=13.7"} (current: {"node":"13.0.1","npm":"6.12.0"})
npm WARN notsup Not compatible with your version of node/npm: browserslist@4.14.2
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules/jest-haste-map/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"ia32"})
npm WARN notsup Unsupported engine for watchpack-chokidar2@2.0.0: wanted: {"node":"<8.10.0"} (current: {"node":"13.0.1","npm":"6.12.0"})
npm WARN notsup Not compatible with your version of node/npm: watchpack-chokidar2@2.0.0
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules/watchpack-chokidar2/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"ia32"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules/webpack-dev-server/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"ia32"})

npm ERR! code 128
npm ERR! Command failed: git clone --depth=1 -q -b webtorrent git://github.com/feross/http-node.git /root/.npm/_cacache/tmp/git-clone-fcd43ea1
npm ERR! fatal: could not create leading directories of '/root/.npm/_cacache/tmp/git-clone-fcd43ea1': Permission denied
npm ERR!

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-09-10T07_07_19_999Z-debug.log
`

i am getting this error

**Comment by livingloves** [comment]
`Creating an optimized production build...
Failed to compile.

./src/index.css
Error: Package exports for '/home/admin/edumeet/app/node_modules/colorette' do not define a valid '.' target


npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! multiparty-meeting@3.3.0 build: `react-scripts build && mkdir -p ../server/public && rm -rf ../server/public/* && cp -r build/* ../server/public/`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the multiparty-meeting@3.3.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-09-10T09_11_57_547Z-debug.log
root@jisu-Conv:/home/admin/edumeet/app/node_modules#
`

getting eroor at the time of building  `npm run build'

**Comment by misi** [comment]
Do you use node version 10? I made a clean install yesterday without an issue. If you experience so many issue try to use the docker image. https://github.com/edumeet/edumeet-docker or https://github.com/edumeet/edumeet-ansible

**Comment by pierguinzani** [comment]
> if Want to Deploay it On My VPS then Also The '/CN=localhost' ?
> 
> `openssl req -x509 -newkey rsa:4096 -keyout privkey.pem -out cert.pem -days 365 -nodes -subj '/CN=localhost'`

No. To deploy to any VPS or server, put the public ip of the instance in place of localhost

**Comment by livingloves** [comment]
> Do you use node version 10? I made a clean install yesterday without an issue. If you experience so many issue try to use the docker image. https://github.com/edumeet/edumeet-docker or https://github.com/edumeet/edumeet-ansible

i use node version 13.0.1 

Can i install The Docker image on My VPS?
if I can Then How ?
Send me the steps ..

**Comment by livingloves** [comment]
i have those Problems But 
When i Am running `npm install` /server/ i am Getting This Error
  `  CC(target) /home/admin/edumeet/server/node_modules/mediasoup/worker/out/Release/obj.target/openssl/deps/openssl/openssl/ssl/bio_ssl.o
In file included from /usr/include/stdio.h:27:0,
                 from ../deps/openssl/openssl/ssl/bio_ssl.c:10:
/usr/include/features.h:367:25: fatal error: sys/cdefs.h: No such file or directory
compilation terminated.
deps/openssl/openssl.target.mk:789: recipe for target '/home/admin/edumeet/server/node_modules/mediasoup/worker/out/Release/obj.target/openssl/deps/openssl/openssl/ssl/bio_ssl.o' failed
make[1]: *** [/home/admin/edumeet/server/node_modules/mediasoup/worker/out/Release/obj.target/openssl/deps/openssl/openssl/ssl/bio_ssl.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/home/admin/edumeet/server/node_modules/mediasoup/worker/out'
Makefile:23: recipe for target 'default' failed
make: *** [default] Error 2
make: Leaving directory '/home/admin/edumeet/server/node_modules/mediasoup/worker'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mediasoup@3.6.19 postinstall: `node npm-scripts.js postinstall`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mediasoup@3.6.19 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-09-10T13_12_38_079Z-debug.log
root@jisu-Conv:/home/admin/edumeet/server#
`

please Help Me Out

**Comment by pierguinzani** [comment]
@livingloves, it is a problem when installing mediasoup. Install the requirements before installing mediasoup. 
https://mediasoup.org/documentation/v3/mediasoup/installation/

**Comment by livingloves** [comment]
> @livingloves, it is a problem when installing mediasoup. Install the requirements before installing mediasoup.
> https://mediasoup.org/documentation/v3/mediasoup/installation/

i have Installed All The Requirements but Still Getting the Same Error

**Comment by livingloves** [comment]
Which Version Of the mediasoup is Used in the Project

**Comment by livingloves** [comment]
i getting this error  on `npm start` 
```
root@jisu-Conv:/home/admin/edumeet/server# npm start

> multiparty-meeting-server@3.3.0 start /home/admin/edumeet/server
> node server.js

internal/modules/cjs/loader.js:463
  throw e;
  ^

Error: Package exports for '/home/admin/edumeet/server/node_modules/mediasoup/no                                                                                        de_modules/uuid' do not define a valid '.' target
    at resolveExportsTarget (internal/modules/cjs/loader.js:460:13)
    at resolveExports (internal/modules/cjs/loader.js:393:16)
    at Function.Module._findPath (internal/modules/cjs/loader.js:492:20)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:787:27)
    at Function.Module._load (internal/modules/cjs/loader.js:693:27)
    at Module.require (internal/modules/cjs/loader.js:864:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/admin/edumeet/server/node_modules/mediasoup/lib                                                                                        /Worker.js:6:16)
    at Module._compile (internal/modules/cjs/loader.js:971:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1011:10) {
  code: 'MODULE_NOT_FOUND'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! multiparty-meeting-server@3.3.0 start: `node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the multiparty-meeting-server@3.3.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional log                                                                                        ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-09-11T10_04_52_164Z-debug.log
root@jisu-Conv:/home/admin/edumeet/server#

```

**Comment by so010** [comment]
delete 'node_modules' folder and begin again from 'npm install'

**Comment by livingloves** [comment]
@so010 I have Done It But I am Getting the Error Again And Again 
 Please Help Me Out

**Comment by so010** [comment]
On your machine admin=root?

**Comment by livingloves** [comment]
Stop your locally running server. Copy systemd-service file multiparty-meeting.service to /etc/systemd/system/ and check location path settings:
```
$ cp multiparty-meeting.service /etc/systemd/system/
$ edit /etc/systemd/system/multiparty-meeting.service
```

Could You Please Tell Me What is exactly I need to Check (location Path)

and multiparty-meeting.service What i Need to Edit to deploy it on the Server?

**Comment by livingloves** [comment]
I am Geeting This Error When I am Trying to Run On Local Host

```
jisu_admin@jisu-Conv:~/edumeet/server$ npm start

> multiparty-meeting-server@3.3.0 start /home/jisu_admin/edumeet/server
> node server.js

/home/jisu_admin/edumeet/server/node_modules/jose/lib/help/rsa_primes.js:8
const ZERO = BigInt(0)
             ^

ReferenceError: BigInt is not defined
    at Object.<anonymous> (/home/jisu_admin/edumeet/server/node_modules/jose/lib/help/rsa_primes.js:8:14)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/jisu_admin/edumeet/server/node_modules/jose/lib/help/key_utils.js:11:23)
    at Module._compile (module.js:652:30)

npm ERR! Linux 5.4.0-47-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! multiparty-meeting-server@3.3.0 start: `node server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the multiparty-meeting-server@3.3.0 start script 'node server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the multiparty-meeting-server package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs multiparty-meeting-server
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls multiparty-meeting-server
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/jisu_admin/edumeet/server/npm-debug.log
jisu_admin@jisu-Conv:~/edumeet/server$ 

```

**Comment by livingloves** [comment]
> On your machine admin=root?

no admin is The User But i have Run it As Sudo a User

**Comment by so010** [comment]
Don't change users for npm install and running the service.
In multiparty-meeting.service there is a user and group the service should run as.  Please do all the steps for deploying as that user - not root.

**Comment by livingloves** [comment]
```
[Unit]
Description=JISU MEET is a audio / video meeting service running in the browser and powered by webRTC
After=network.target

[Service]
ExecStart=/usr/local/src/edumeet/server/server.js
Restart=always
User=jisu_admin
Group=jisu-Conv
Environment=PATH=/usr/bin:/usr/local/bin
Environment=NODE_ENV=production
WorkingDirectory=/usr/local/src/edumeet/server
AmbientCapabilities=CAP_NET_BIND_SERVICE

[Install]
WantedBy=multi-user.target
```


I have Changed The Following Is There Any other Changes are required?

Because When I am Performing The 
`systemctl start multiparty-meeting`


it is Giving Me  This Error


```
jisu_admin@jisu-Conv:~$ systemctl daemon-reload
==== AUTHENTICATING FOR org.freedesktop.systemd1.reload-daemon ===
Authentication is required to reload the systemd state.
Authenticating as: JISU,,, (jisu_admin)
Password:
==== AUTHENTICATION COMPLETE ===
jisu_admin@jisu-Conv:~$ systemctl start multiparty-meeting
==== AUTHENTICATING FOR org.freedesktop.systemd1.manage-units ===
Authentication is required to start 'multiparty-meeting.service'.
Authenticating as: JISU,,, (jisu_admin)
Password:
==== AUTHENTICATION COMPLETE ===
Failed to start multiparty-meeting.service: Unit multiparty-meeting.service not found.
jisu_admin@jisu-Conv:~$
```

**Comment by so010** [comment]
> Failed to start multiparty-meeting.service: Unit multiparty-meeting.service not found.
> jisu_admin@jisu-Conv:~$

service file not copied to right place and activated?

https://github.com/edumeet/edumeet#deploy-it-in-a-server

**Comment by livingloves** [comment]
i Have Copied To the Right Place  As Mentioned in the Documentation Now when I am Running It Is Not Giving Any Output But The Server is Not Starting Because I Can't Be Able to Access It from the Browser

**Comment by misi** [comment]
Am I understand your issue correctly?

Have you checked that it listen on port 80 on server
`netstat -lntp` or `ss -lntp`
Is node listen on port 80 and 443??

And your issue is that your browser get an error to access it remotely right?
Or what do you experience on browser side? Check borwser debug console network and console tab and
and also chrome://webrtc-internals  or about:webrtc depending on your browser

**Comment by livingloves** [comment]
No No I am Ablr to Use the Server By npm Start But When I am Performing `symmetrical  Start multiparty-meeting.service` The Server is not Starting 


`netstat -lntp` Result
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
```
tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN      -                   
tcp        0      0 127.0.0.1:631           0.0.0.0:*               LISTEN      -                   
tcp        0      0 0.0.0.0:7071            0.0.0.0:*               LISTEN      1584/anydesk        
tcp        0      0 0.0.0.0:40675           0.0.0.0:*               LISTEN      1584/anydesk        
tcp        0      0 0.0.0.0:60005           0.0.0.0:*               LISTEN      -                   
tcp        0      0 127.0.0.1:6379          0.0.0.0:*               LISTEN      -                   
tcp6       0      0 ::1:631                 :::*                    LISTEN      -                   
tcp6       0      0 :::60005                :::*                    LISTEN      -                   
tcp6       0      0 ::1:6379                :::*                    LISTEN      -        
```

**Comment by misi** [comment]
So npm start works fine? Right? I can't fully understand your last comment "Ablr"==?

I guess it is then systemd settings 

edit multiparty-meeting.service
Add to 
[Service]
AmbientCapabilities=CAP_NET_BIND_SERVICE

**Comment by livingloves** [comment]
> So npm start works fine? Right? I can't fully understand your last comment "Ablr"==?
> 
> I guess it is then systemd settings

Sorry, That was a Typo Error "ablr" == able




my multiparty-meeting.service is 

```
[Unit]
Description=JISU MEET is a audio / video meeting service running in the browser and powered by webRTC
After=network.target

[Service]
ExecStart=/usr/local/src/edumeet/server/server.js
Restart=always
User=jisu_admin
Group=jisu-Conv
Environment=PATH=/usr/bin:/usr/local/bin
Environment=NODE_ENV=production
WorkingDirectory=/usr/local/src/edumeet/server
AmbientCapabilities=CAP_NET_BIND_SERVICE

[Install]
WantedBy=multi-user.target

```
