### ISSUE TITLE
How can I Spotlight on more then One People at a time  ?

### ISSUE THREAD

**Issue by livingloves** [edumeet/edumeet#539]
How can I Spotlight on more then One People at a time  ?

i  mean i want  make Spotlight 5-6 people on my Meeting 

How can I Do that

**Comment by so010** [comment]
Search for lastN and maxLastN in /app/public/config/config.js it is documented there.
User can configure locally in the client under Settings / ADVANCED / "Number of visible videos" up to maxLastN.

**Comment by misi** [comment]
I think the question is answered so I close it. Please open new issue if you have further question.
