### ISSUE TITLE
Where is log file after deploy it in a server

### ISSUE THREAD

**Issue by bianxg** [edumeet/edumeet#543]
how can I output log to a file after deloy it in a server (using method: systemctl start multiparty-meeting)?

**Comment by so010** [comment]
You have access to your logs via `journalctl -u multiparty-meeting`
logs go to `/var/log/system.log`
For separate traditional logs add this to your multiparty-meeting.service file:
```
StandardOutput=append:/var/log/multiparty-meeting.log
StandardError=append:/var/log/multiparty-meeting-error.log
```
