### ISSUE TITLE
"Unable to join room", No Error!

### ISSUE THREAD

**Issue by callmemonky** [edumeet/edumeet#544]
I was working on this project, I made few changes in the UI. Everything was working then but after an hour, I started getting this error "Unable to join room". I am not able to debug this since, I didnt make new changes.

**Comment by misi** [comment]
We need more info to help. Version? 
Can you check logs on your browser debug console? On network tab and check browser console logs too?
We are unable to help without more info... Your issue is unusual.

**Comment by ShivKumarSaini** [comment]
Any luck on this issue ? Please share.

**Comment by roman-drozd-it** [comment]
No response for much more than 1 month.
