### ISSUE TITLE
DisplayMediaScreenShare _toConstraints bug

### ISSUE THREAD

**Issue by danimateo** [edumeet/edumeet#545]
Hello, this code: 

```
 if (isFinite(options.width)) {
      constraints.video.width = options.width;
 }
```
should be:
```
 if (isFinite(options.width.ideal)) {
      constraints.video.width = options.width.ideal;
 }
```

Otherwise, setting the default resolution is useless. I'm sensing this might also be the reason the screen share options are grayed out in MediaSettings.

**Comment by so010** [comment]
Will test, thanks for catching!
