### ISSUE TITLE
what's about stream forward logic

### ISSUE THREAD

**Issue by bianxg** [edumeet/edumeet#553]
Please explain basic logic that mediasoup forward audio or video stream. Thanks.
Such as how many audio streams will forward to a client? one most active , some active audio streams or all other clients’ audio streams. And how to complete the task.

How about video stream forward? Does client decide which video streams to forward and tell the server, or just the server forward all other client's video?

**Comment by so010** [comment]
If clients activate there media they will be send to server. Server distribute media stream only if they are subscribed from clients individually. So clients decide which streams they want to consume and this is dependent from layout / pinning of videos / muting / maxLastN config / speaker detection / ... Audio is a little bit different but follows the same idea.

**Comment by roman-drozd-it** [comment]
Has been explained. Closed.
