### ISSUE TITLE
Client request prefer layer according video size displayed (such as in Filmstrip view mode)

### ISSUE THREAD

**Issue by bianxg** [edumeet/edumeet#554]
Can add this feature?
app\src\RoomClient.js
async setConsumerPreferredLayers(consumerId, spatialLayer, temporalLayer)

**Comment by misi** [comment]
@bianxg  I don't see what you mean? Can you explain it more. We are planing to use this function soon.

**Comment by bianxg** [comment]
In filmstrip mode, we should prefer consumer layer according grid size(corresponding to the consumer) to save client's CPU load and download bitrate. Also for democratic mode, we only need middle layer for all consumers.

// Grid is:
// 4/5 speaker
// 1/5 filmstrip

**Comment by so010** [comment]
This is definitely something we will do soon.
