### ISSUE TITLE
Notification sounds 

### ISSUE THREAD

**Issue by samueldedios** [edumeet/edumeet#557]
turn off sound notifications by default

**Comment by misi** [comment]
Would it make sense if the default behavior of sound notification could be configured in app config?

**Comment by misi** [comment]
If you can please send a Pull Request of it and I will merge. If not I will add it to my TODO list.

**Comment by so010** [comment]
I think sound notifications should be "on" as default, but this depends on your usecase. I understand in big lectures this can be very annoying and we should make smarter decisions if a notification should be played or not eg rate limiting join notifications or switch automatically off for bigger rooms. Or if frequency is above a threshold show a mini-dialog to switch them off.

**Comment by jmencak** [comment]
Related to this subject.  I believe it would also be very useful if the notification sound could be different for users joining vs chat messages.  Imagine a webinar where the lecturer is not really interested in hearing (or wants to distinguish) that someone joined, but wants to be notified about a new chat message -- usually questions.

**Comment by roman-drozd-it** [comment]
Done regarding project 3.5
