### ISSUE TITLE
Screen sharing of other participants stays black and no audio

### ISSUE THREAD

**Issue by vimalraj-ponnusamy** [edumeet/edumeet#564]
Hi,

Deployed app and turn server in ubuntu server.

In Server browser, Screen sharing is working inside server.

But in my local browser screen sharing is not working .
What could this be?

Thanks

**Comment by misi** [comment]
We need more info. 
How did you deploy your application?
Which version?
Which browser and browser version do you use on client and server side..
It should work in general.

**Comment by vimalraj-ponnusamy** [comment]
hi @misi ,
Deployed it in ubuntu server app and by manual installation method mentioned in github and using the nginx to redirect.
I have using the latest version .
Using chrome browser Google Chrome is up to date
Version 85.0.4183.121 (Official Build) (64-bit) in both server and client.

Screen sharing is working inside the server.
but if I try this in outside of the server the receiver gets the black screen.

**Comment by so010** [comment]
> Screen sharing is working inside the server.

Client running on server locally?

**Comment by vimalraj-ponnusamy** [comment]
> > Screen sharing is working inside the server.
> 
> Client running on server locally?

yes and it is proxied via nginx to the domain url

**Comment by so010** [comment]
> > > Screen sharing is working inside the server.
> > 
> > 
> > Client running on server locally?
> 
> yes and it is proxied via nginx to the domain url

Screensharing is black in sending client as well?

**Comment by vimalraj-ponnusamy** [comment]
> > > > Screen sharing is working inside the server.
> > > 
> > > 
> > > Client running on server locally?
> > 
> > 
> > yes and it is proxied via nginx to the domain url
> 
> Screensharing is black in sending client as well?

no only receiver gets the black screen

**Comment by so010** [comment]
Do you have a link - I want to see this?

**Comment by vimalraj-ponnusamy** [comment]
> Do you have a link - I want to see this?

![image](https://user-images.githubusercontent.com/16756355/94245740-5656c500-ff38-11ea-950d-9590002c1f57.png)

![image](https://user-images.githubusercontent.com/16756355/94245796-6a022b80-ff38-11ea-8060-cdea707050ea.png)

**Comment by so010** [comment]
Red connection indicator!
Video and audio is working?

**Comment by vimalraj-ponnusamy** [comment]
> Red connection indicator!
> Video and audio is working?

no that also not working

**Comment by so010** [comment]
Check IP adresses in serverconfig, 
```
			listenIps :
 			[
 				{ ip:'your local interface address e.g. 0.0.0.0', announcedIp:'your public IP address e.g. 123.45.67.89' }
```
And check your TURN server logs if there is activity

**Comment by vimalraj-ponnusamy** [comment]
> Check IP adresses in serverconfig,
> 
> ```
> 			listenIps :
>  			[
>  				{ ip:'your local interface address e.g. 0.0.0.0', announcedIp:'your public IP address e.g. 123.45.67.89' }
> ```
> 
> And check your TURN server logs if there is activity

yeah in turn log I see this issue ,         
Cannot bind TLS/TCP listener socket to addr xx.xxx.xxx.xxx:3478

**Comment by vimalraj-ponnusamy** [comment]
Enabled

When i turned off the firewall in ubuntu machine , it is working now.

**Comment by so010** [comment]
You should open at least the listening port of your turnserver - looks like 3478 in your case. 
But the above error sounds like missing AmbientCapabilities=CAP_NET_BIND_SERVICE in turnservers service file.

**Comment by roman-drozd-it** [comment]
No response for much longer than 1 month.

**Comment by mohamed-ben-smida** [comment]
Hello, I'm facing the exact same issue on server and in local. (develop branch)
