### ISSUE TITLE
Video enhancement

### ISSUE THREAD

**Issue by zmartinovic** [edumeet/edumeet#567]
We would love to use eduMeet not only for meetings but also for lectures. To be able to do that, there should be number of changes (there could even be server setting to enable eduMeet to run as is for meetings of for webinars with different behaviors):

- moderator should be able to set number of visible videos to all participants
- moderator should be able to set main video (with screen share) to all participants in filmstrip layout
- non video participants should be hidden (no point to see large video block for participants with no camera)
- setting to join meeting with turned off video and audio (mute users when they join)

Also to note that even current video features make no sense. When you switch to filmstrip layout it makes random(?) video main and user can't change it. If that video is not broadcasting you will just see blank video all the time. Also if you enable for example 6 videos to be displayed and there are 6 out of 8 participants broadcasting video it will randomly(?) select 6 video streams even if they are not broadcasting. Only active streams should display, non video users should be automatically hidden.

**Comment by misi** [comment]
Many thanks for your suggestions.
Please let's split this issue into one enhancement /per issue. 
And after it we wil pick and assign it to the roadmap.
Many Thanks for your help and cooperation!

**Comment by zmartinovic** [comment]
Ok, no problem :) I will open individual tickets for each enhancement.
