### ISSUE TITLE
{“code”:1,”message”:”Session ID unknown”} - Are these normal socket.io responses?

### ISSUE THREAD

**Issue by exitrip** [edumeet/edumeet#568]
Hi,

I’m trying to debug a new, dead simple deployment on a GCP Ubuntu image.

Running the server, once i click the “Audio” or “Audio and Video” buttons from the {domain}/{roomname} URL, I see a quick flash of the room scripts load, a quick pop up “Unable to join room” and it reloads the previous URL.

Digging into this a bit, I see a bunch of queries/post/gets to:

/socket.io/?peerId=xxxxxxxxxx&roomId=xxxxxxxxxxxxxx&EIO=3&transport=polling&t=xxxxxxxx&sid=xxxxxxxx
that all have the response:
{“code”:1,“message”:“Session ID unknown”}

Which looks like it’s coming from socket.io, and there’s not much help other than “use websockets” elsewhere online…

1 - Is this normal behaviour, and so I should keep looking for my connection problems elsewhere?
2 - Any suggestions as to why this is happening… I’m using the “numb.viagenie.ca” turn server for testing, before deploying my own…

Thanks,

a hardware engineer

**Comment by exitrip** [comment]
I know this isn't an issue, but a question...  the mediasoup forums are very unhelpful, so I'm posting this here.  Any other suggestions of places to look for assistance?

**Comment by havfo** [comment]
This is as you say an issue with websocket and/or socket.io long-polling. Do you have a nginx, or similar, web proxy in front of the edumeet server? Are you running some sort of load balancing?

As a test you could modify the following line:
https://github.com/edumeet/edumeet/blob/67ae1a796d7c1873a82814ead33ccc3bd3776c59/app/src/RoomClient.js#L2045

Change it to:
`this._signalingSocket = io(this._signalingUrl, { transports: ['websocket'] });`

This disables long-polling, and uses only websockets.

Rebuild in the `app` folder and try again.

**Comment by roman-drozd-it** [comment]
No response much over 1 month.
