### ISSUE TITLE
I cannot install the letsencrypt certificate

### ISSUE THREAD

**Issue by volkankoc** [edumeet/edumeet#569]
I cannot install the letsencrypt certificate. I get an error that port 80 is being used.
Can you help with SSL setup.
apach2 disabled because use port 80
edumeet does not work this time when running apache
says port 80 in use

VPS - Ubuntu Server 18.04

**Comment by misi** [comment]
Try ti first stop edumeet and check if no process run on port 80 and run certbot and after it copy the cert and start edumeet.

**Comment by volkankoc** [comment]
server and domain are in separate companies.
Is this a problem

**Comment by misi** [comment]
@volkankoc I don't understand your last comment.  Can you please detail it?

**Comment by misi** [comment]
Getting a cert is not related strongly this project. Please ask help from your dns and server company, howto get such cert in your case. I don't think I can help you more in it.

**Comment by volkankoc** [comment]
> Getting a cert is not related strongly this project. Please ask help from your dns and server company, howto get such cert in your case. I don't think I can help you more in it.

Thank , im solved problem.
First stop apache server , after with cerbot key create.
and its work

**Comment by misi** [comment]
Great! Thanks for the feedback! I will close the issue then! Thanks!
