### ISSUE TITLE
User selectable main video in filmstrip layout

### ISSUE THREAD

**Issue by zmartinovic** [edumeet/edumeet#572]
User should be able to select main video in filmstrip layout. Displaying random video as main makes no sense and makes this layout useless.

**Comment by so010** [comment]
Hmm, please describe step by step to reproduce. Usually there is active speaker detection for main view. Do you talk about 'add to spotlight' function?

**Comment by zmartinovic** [comment]
Oh yes, you are right. First time I've tested active speaker detection was not working so great, but we were trying out some configurations so that could be the problem. It's ok now.
