### ISSUE TITLE
Mute users when they join

### ISSUE THREAD

**Issue by zmartinovic** [edumeet/edumeet#573]
Currently there are two option to join meeting: with video and only audio. There should be one more option (it can even be server side option) to mute users when they join. Many users like to explicitly enable mic and camera when they join a meeting and not to broadcast immediately.

**Comment by so010** [comment]
Next release will contain different join dialog with this functionality. App config has a option here as well:
https://github.com/edumeet/edumeet/blob/19867a7dc391d1808f56c1a2f7d1c157eed30476/app/public/config/config.example.js#L116

which will make participants joining muted as default in bigger rooms. But this will ask users still how they want to join and the browser tries to get media devices for later use but new join dialog will solve this.

**Comment by zmartinovic** [comment]
Yes and in https://github.com/edumeet/edumeet/issues/581 I've wrote that we tried this config:
autoMuteThreshold : 0,
buttonControlBar : true,
defaultLayout : 'filmstrip',
drawerOverlayed : false,

but only defaultLayout seems to be working.

**Comment by so010** [comment]
It seems there are some issues with filmstrip but that is a different issue, only one cross each ;)
I consider this solved. Reopen or make a new issue.
