### ISSUE TITLE
I need help during setup

### ISSUE THREAD

**Issue by akindizayn1** [edumeet/edumeet#575]
Hello,

I want to install macOS Catalina on my computer, but I'm getting an error.

node -v
v14.12.0

npm -v
6.14.8

1) sudo apt install git npm build-essential redis
2) cp server / config / config.example.js server / config / config.js
3) cp app / public / config / config.example.js app / public / config / config.js
4) cd app
5) npm install
6) npm run build
7) cd ..
8) cd server
9) npm install
10) cd server
11) npm start

I share the screenshot of these operations in the attachment. But I can't run the system. Can you help me at what stages and what should I do? Sorry for typos because I used an English translation.

Thanks for the help.

<img width="885" alt="Ekran Resmi 2020-09-28 12 06 21" src="https://user-images.githubusercontent.com/72012423/94413101-4c74d200-0183-11eb-8468-c200a77dd5b3.png">

**Comment by misi** [comment]
You need to run a redis server on localhost. Please chect it.

**Comment by akindizayn1** [comment]
Thanks for the help. Now the system has worked but there is another problem. I write the room name and participant name, but he asks the same questions over and over again. What do you think is the cause of the problem?

<img width="1678" alt="Ekran Resmi 2020-09-28 22 31 32" src="https://user-images.githubusercontent.com/72012423/94477327-668dcf00-01da-11eb-860d-0b9b09e8422f.png">

**Comment by akindizayn1** [comment]
Can you help me please?

**Comment by so010** [comment]
Log on server and browser console?

**Comment by gunnurafi** [comment]
hello i need help in login in admin i didnt understand about it, how setup login auth please help out this please.

**Comment by so010** [comment]
@gunnurafi Please open separated  issue and describe what you tried already and where your problem is. Don't mess up other issues! And especially don't spam.

**Comment by roman-drozd-it** [comment]
No response much longer than 1 month.
