### ISSUE TITLE
Router not found

### ISSUE THREAD

**Issue by Astagor** [edumeet/edumeet#580]
From time to time I have the following error in the logs:
`Sep 29 10:33:46 webrtc2 multiparty-meeting[22225]: 2020-09-29T08:33:46.491Z edumeet-server:WARN:Room _createConsumer() | [error:"Error: Router not found at Channel._processMessage (/var/www/servers/multiparty-meeting/server/node_modules/mediasoup/lib/Channel.js:206:37) at Socket.Channel._consumerSocket.on (/var/www/servers/multiparty-meeting/server/node_modules/mediasoup/lib/Channel.js:68:34) at Socket.emit (events.js:198:13) at Socket.EventEmitter.emit (domain.js:448:20) at addChunk (_stream_readable.js:288:12) at readableAddChunk (_stream_readable.js:269:11) at Socket.Readable.push (_stream_readable.js:224:10) at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)"]
Sep 29 10:33:46 webrtc2 multiparty-meeting[22225]: 2020-09-29T08:33:46.491Z mediasoup:ERROR:Channel [pid:22236 Worker::GetRouterFromRequest() | throwing MediaSoupError: Router not found`

I went though the code, did some tests, but cannot find a reason how can a router not exist. The routers are being created for each room with the creation of the room, so it should never happen that a router is closed if the room exists. Any ideas? @havfo

**Comment by misi** [comment]
To get more info to troubleshoot the issue, try to increase log level of mediasoup to get more info about when such router is going for shutdown.. 
Just my 2 cents.

**Comment by roman-drozd-it** [comment]
@Astagor Did you manage it?
