### ISSUE TITLE
Question: simultaneous users in room and client config

### ISSUE THREAD

**Issue by zmartinovic** [edumeet/edumeet#581]
We are testing on our dev installation (cluster of 2 eduMeet servers, testing with around 25 participants) and when number of users try to enter the same room number of them turn up in empty room on the same address. So, we all have the same URL but we are not all in the same room. Now, in server config I can see 2 variables: 
// maxUsersPerRoom    : 20
routerScaleSize      : 40,

So, maxUsersPerRoom is commented out and in documentation it states that there is no limit of users in one room (that is what we want). What dose routerScaleSize dose? How can we make all participants to be present together in the same room?

My other question is about client config. We want default to be shown filmstrip mode, all users to be muted on join, that media controls are separated and that block overly in not hiding part of the content. In settings we have:
autoMuteThreshold    : 0,
buttonControlBar       : true,
defaultLayout             : 'filmstrip',
drawerOverlayed       : false,

but only defaultLayout seems to be working. Any idea why other settings are not set as default?

Best,
Zvonko

**Comment by zmartinovic** [comment]
Any info on this routerScaleSize variable? We want "unlimited" users in one room (URL) all together.

Thanks,
Zvonko

**Comment by so010** [comment]
routerScaleSize will not limit the number of participants in one room.
Can you test with increasing participant number slowly. Are they appearing in same room  up to a limit and then appearing in a different room or is it randomly distributed from the beginning?
routerScaleSize is the limit from which the room should use an additional router - this should not split the room but scale it up to several server processes. You usually shouldn't change this.

**Comment by zmartinovic** [comment]
Hi,

it's bit hard to get larger number of people for testing in the same time, but this is what happened on two test me made: most participants ended up in the right room, but some entered the same room but they were alone or with few participants. We tested with around 25 people and the ones that connected last were in the "empty" room (or among the last). So they weren't randomly distributed, not in the obvious way.

What is strange that URL for them was the same. We also checked logs on both servers, and room URL only appeared in the logs of one server so they ended up on the correct server.

Best,
Zvonko

**Comment by so010** [comment]
Could you retry with latest develop branch, we had some bugs with scaling up to different routers?

**Comment by zmartinovic** [comment]
Thanks, we will try it and make a new test. I'll reply with the results :)

**Comment by ciaoamigoschat** [comment]
news?

**Comment by zmartinovic** [comment]
sorry, if you are referring to the original question about simultaneous users in room, yes it is fixed in latest dev branch and it was working just fine on our last test. default client config is also set :) closing the issue
