### ISSUE TITLE
Audio Crackling on IOS Devices

### ISSUE THREAD

**Issue by JoeMyers** [edumeet/edumeet#582]
We have a strange issue with audio crackling on output and input on several iOS devices. 

The user on the iOS device hears the crackling of the speakers and also the listeners hear the crackling of the streamed audio from the device.

We have tested on the following devices:

iPhone 7 running iOS 13.7 AND 14
iPhone XS running iOS 14
iPhone 6 running iOS 12.47

The issue seems to start when two users talk over each other, however, this could just be a coincidence. Has anyone else faced the same issue?

**Comment by so010** [comment]
Will have a look on this and have some testing clear for next week ....

**Comment by so010** [comment]
@JoeMyers could you test on letsmeet.no if it is fixed?

**Comment by delavegaOpengl** [comment]
We experienced the same strange behaviour.
Ipad Mini 3rd generation
Iphone 11 safari 14.0
No issues from desktop Windows 10 and android (we tested many devices), while on Linux no issue in Chrome, whilst audio and video not working on Firefox 82.0.
Moreover on iphone 6 and Ipad Mini 3 after sometime the screen freeze after the audio start crackling

**Comment by JoeMyers** [comment]
Just tested on letsmeet.no with 8 participants 6 PCs and 2 apple devices and we had occasional clicking, however, it was a little bit better than it was previously

**Comment by so010** [comment]
Could you try again at letsmeet.no?

**Comment by delavegaOpengl** [comment]
Unfortunately now letsmeet.no show blank screen on ipad 3 and iphon 6s. So tried to build my own serve and get same result, but if I implement @so010 proposed solution for crackling it loads on Ipad3 while on iphone 6s freeze on first frame. FYR i tested also the mediasoup client demo it starts almost on any device but the crackling is present as well.

**Comment by JoeMyers** [comment]
We still have the issue with crackling on letsmeet.no, seems to be less affected when echo cancellation is turned off and no one has video on.

Could it be a performance issue on the mobile devices?

**Comment by so010** [comment]
Looks like most of newest ios devices and newest MacOSX with safari have all the same crackling sound. Problem seems to be there as well on google meet and jitsi. We try to find a workaround but it looks like we have to put this to Apple.
