### ISSUE TITLE
 I have SSL certificate. But file extension .cer , crt , how is use ?

### ISSUE THREAD

**Issue by volkankoc** [edumeet/edumeet#583]
I got SLL certification and verified it. Four files have been sent to me. But the extensions are not .pem. How do I use these files for edumet?

**File names**
1-ETugraRoot
2-TrustSafe_SSLDV_SubCA.cer
3-domain.com.crt
4-domain.com.p7b

how do i use files.
im not use directadmin and cpanel, im use ubuntu server 18.04 (vps)

**Comment by volkankoc** [comment]
please help

**Comment by so010** [comment]
e.g. https://knowledge.digicert.com/solution/SO26449.html#:~:text=Note%3A%20The%20PEM%20format%20is,binary%20form%20of%20the%20certificate.

**Comment by volkankoc** [comment]
> e.g. https://knowledge.digicert.com/solution/SO26449.html#:~:text=Note%3A%20The%20PEM%20format%20is,binary%20form%20of%20the%20certificate.

ok , but Which privkey.pem certifica in 4 certifica

**Comment by so010** [comment]
I think domain.com.crt is your cert file. Your key is not there - you should have generated it by yourself and kept it secretly in the beginning of generating your cert request. Please read more about certificates and keys. It is important that you understand this by yourself. Here is not the right place to find help for this stuff. Ask your CA provider and use search engines.
