### ISSUE TITLE
How can I enable Userroles in this app? I cant seem make it work.

### ISSUE THREAD

**Issue by callmemonky** [edumeet/edumeet#592]

**Comment by so010** [comment]
Did you had a look at the config file there are some good examples. In principle you can define how userroles are controlled there in config and can even include your own programmatic logic  to make these decisions by yourself.
https://github.com/edumeet/edumeet/blob/19867a7dc391d1808f56c1a2f7d1c157eed30476/server/config/config.example.js#L149

**Comment by roman-drozd-it** [comment]
No response much over 1 month. Closed.
