### ISSUE TITLE
Update old npm packages

### ISSUE THREAD

**Issue by so010** [edumeet/edumeet#604]
There are a lot of outdated npm packages we use.
We should update and test that package by package.
Perhaps reconsider if we really need all of them or can implement functionality with other already used components/packages or implement functionality by ourself. Especially for just adding fancy elements or functionality which we can implement easily.
IMHO this is a big security issue. Not only using outdated packages but using that much packages - we never can't check if we install a back door with each of these packages.

**Comment by misi** [comment]
There are mechnaism to handle it. IMHO we need to focus on CI/CD pipeline to make build with up2date dependencies and it will handle the most of the issues.

**Comment by so010** [comment]
Yes, that is one important part of it. But to get there we have to write automated test to functionality we use in these packages as well. And we will get a lot of additional work to maintain API changes in these packages. What you can't handle are malicious packages. I think about packaged like twilio-npm 
https://www.zdnet.com/article/malicious-npm-package-opens-backdoors-on-programmers-computers/
So I think minimize external packages is a good strategy.

**Comment by havfo** [comment]
Fixed in new client/server
