### ISSUE TITLE
Media consent requested in joindialog, before room join in case if auth user required but noone is in the room

### ISSUE THREAD

**Issue by misi** [edumeet/edumeet#605]

**Comment by misi** [comment]
![Képernyőkép_2020-11-07_16-12-42](https://user-images.githubusercontent.com/311629/98444850-70c5b600-2114-11eb-9f2f-5f80b5ad9a2c.png)

**Comment by Astagor** [comment]
I seen on chrome, that it happens as my camera icon blinked for 1 second when entering lobby. On the other hand maybe this is not a bad idea, that the user gives permissions before he enters the room, as when he enters he might more easy miss the dialog, and in the lobby he has nothing interesting happening on the screen, so he might see the dialog more quickly. Just my thoughts.

**Comment by havfo** [comment]
Fixed in new client
