### ISSUE TITLE
Problems with mediasoup audio observer

### ISSUE THREAD

**Issue by Astagor** [edumeet/edumeet#606]
First of all is server/Room.js in line 1094 we have
	if (kind === 'audio')
				{
					this._audioLevelObserver.addProducer({ producerId: producer.id })
						.catch(() => {});
				}

You see that empty catche, bad thing. I have put an log error there and get from time to time:

Nov  6 08:55:18 webrtc2 multiparty-meeting[1487]: 2020-11-06T07:55:18.582Z edumeet-server:ERROR:Room this._audioLevelObserver.addProducer ERROR [error:"Error: Producer not found at Channel._processMessage (/var/www/servers/multiparty-meeting/server/node_modules/mediasoup/lib/Channel.js:206:37) at Socket.Channel._consumerSocket.on (/var/www/servers/multiparty-meeting/server/node_modules/mediasoup/lib/Channel.js:68:34) at Socket.emit (events.js:198:13) at Socket.EventEmitter.emit (domain.js:448:20) at addChunk (_stream_readable.js:288:12) at readableAddChunk (_stream_readable.js:269:11) at Socket.Readable.push (_stream_readable.js:224:10) at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)"]

Now, how can this happen???  Producer not found... we have just got the producer from mediasoup in line 1048

**Comment by Astagor** [comment]
https://mediasoup.discourse.group/t/remote-pipetransport-and-layerschange-volume-events/822/7

**Comment by so010** [comment]
Perhaps try catch produce command :
```
try
{
	producer = await transport.produce({ kind, rtpParameters, appData });
}
catch (error)
{
	logger.debug(
		'transport.produce failed: %o, kind: %s, rtpParameters: %o appdata %o',
		error, kind, rtpParameters, appData);
}
```
But anyway, we planned to go away from audioLevelObserver.
Audio levels on client side are right now observed from hark for all streams locally. 
I want to change that and speaker detection as well running on the client who generates the audio stream only and send that via signaling to all other clients. Then we need audioLevelObserver not any longer.
