### ISSUE TITLE
Bug: login is persistent in new session

### ISSUE THREAD

**Issue by zmartinovic** [edumeet/edumeet#612]
There is a bug that shows users as logged when they access room in new session if they were logged in in previous session. This happens to us when using OIDC. Even if it states that user is logged in, he is not, so he can't enter a room (we have set up room access and permissions based on user data that we get from OIDC). When we start a new session eduMeet should show user as not logged.

**Comment by misi** [comment]
Is the problem occur  if you use this latest version of develop sp commit https://github.com/edumeet/edumeet/commit/9625e3934804e60f34a9f1936c6d2c6890a96ed9?

**Comment by zmartinovic** [comment]
Thanks @misi. We will install latest dev and will replay back if it's solved :)

**Comment by zmartinovic** [comment]
@misi we have just tested with latest dev branch. it is better even if it's not perfect. so now if i open edumeet for a second time it will show me as logged in, but when i click to join it will show i'm not so i can login again. actually, this latest dev seems more inconsistent. few times after i login it wouldn't let me enter a room so i had to reload the page.
it is easier to show you. first video is dev branch from a week ago:
https://kosjenka.srce.hr/~zmartinovic/edumeet.mp4
second video is latest dev branch:
https://kosjenka.srce.hr/~zmartinovic/edumeet2.mp4

**Comment by misi** [comment]
See @Astagor 's PR https://github.com/edumeet/edumeet/pull/621

**Comment by zmartinovic** [comment]
@misi Yes, we have tried new dev as it's integrated and it is Ok now :)
