### ISSUE TITLE
Force authentication

### ISSUE THREAD

**Issue by sorincocorada** [edumeet/edumeet#613]
Would is be possible to force authentication in order to start the meeting?
To be more precise allow only the moderator(authenticated) to start the meeting

**Comment by zmartinovic** [comment]
Hi, you can do that. We have set up our installation like that. In our server config we have:
accessFromRoles : {
	[BYPASS_ROOM_LOCK] : [ userRoles.MODERATOR ],
	[BYPASS_LOBBY]     : [ userRoles.AUTHENTICATED ]
},
activateOnHostJoin   : true,
and commented:
//allowWhenRoleMissing : [ CHANGE_ROOM_LOCK ],

**Comment by sorincocorada** [comment]
Thank you very much, it works.
