### ISSUE TITLE
Bug in storage

### ISSUE THREAD

**Issue by Astagor** [edumeet/edumeet#616]
There is a problem with the values in the store.
For example, if a screen share has failed in store the vale "screenShareInProgress":true is set and even when the user reloads the page he cannot screen share (button disabled) because of this.

**Comment by Astagor** [comment]
The same is with raisedHand it gets persisted between reloads of the page.

**Comment by Astagor** [comment]
I did a temp fix in RoomClient.js in the _joinRomm function by adding

`			store.dispatch(meActions.setRaisedHand(false));
			store.dispatch(meActions.setAudioInProgress(false));
			store.dispatch(meActions.setAudioOutputInProgress(false));
			store.dispatch(meActions.setWebcamInProgress(false));
			store.dispatch(meActions.setScreenShareInProgress(false));
			store.dispatch(meActions.setRaisedHandInProgress(false));
			store.dispatch(meActions.setDisplayNameInProgress(false));
			store.dispatch(meActions.setIsSpeaking(false));
			store.dispatch(meActions.setIsSpeaking(false));`

**Comment by so010** [comment]
Hopefully fixed now
