### ISSUE TITLE
Audio setting client - server

### ISSUE THREAD

**Issue by Astagor** [edumeet/edumeet#617]
In the client config, we now have the new options with 96000 kHz, but in the server config in the media soup conf we still have

				{
					kind      : 'audio',
					mimeType  : 'audio/opus',
					clockRate : 48000,
					channels  : 2
				},

Should this not consistent? Clock 96000 and channels 1, as we set this also in client config? @so010

**Comment by so010** [comment]
After reading the RFC (https://tools.ietf.org/html/rfc7587) I changed back to 48000. Higher sampling rates will be resampled which is worse than sampling in 48000Hz in first place.
https://github.com/edumeet/edumeet/commit/7e850c979b2ff3072142fe9fa5dee5a9a47e73ec
