### ISSUE TITLE
The camera resolution is still 640x480 when join room with 'high' resolution setting.

### ISSUE THREAD

**Issue by bianxg** [edumeet/edumeet#620]
The reason is about below code:
const _askForPerms = () =>
	{
		if (mediaPerms.video || mediaPerms.audio)
		{
			// navigator.mediaDevices.getUserMedia(mediaPerms);
		}
	};
When remove calling getUserMedia(), it works. (The first time join room, it can work with this code.)
By the way, the older edumeet version has not this problem.

**Comment by so010** [comment]
Should be solved already (temporally) by https://github.com/edumeet/edumeet/commit/0a3e0da08c3dadec1fee021724cd6e6e62900a8d
