### ISSUE TITLE
How can i view debug messages on backend console?

### ISSUE THREAD

**Issue by hkizilhan** [edumeet/edumeet#622]
logger.error('any message');
logger.warn('any message');
logger.debug('any message');
logger.info('any message');
********************************
i tried followings:
DEBUG=true npm start
DEBUG=info npm start

i can't get any debug messages anyway...

**Comment by volkankoc** [comment]
Yes. I need the that. Please help me

**Comment by so010** [comment]
DEBUG="edumeet*" npm start
or if you want everything:
DEBUG="*" npm start
