### ISSUE TITLE
hi i didnt get moderator and admin im getting only noraml user entering in room, how to see moderator join the room

### ISSUE THREAD

**Issue by gunnurafi** [edumeet/edumeet#635]
hi i didnt get moderator and admin im getting only noraml user entering in room, how to see moderator join the room

![122](https://user-images.githubusercontent.com/72020866/100287769-4d678b80-2f9b-11eb-93bd-aae4eaea1e0f.png)

**Comment by misi** [comment]
See usermapping function in server config examples.
Make and "if" statement  base on user attributes/claims  and add peer.addRole(userRoles.ADMIN);

**Comment by gunnurafi** [comment]
hi i made a condition on if statement but it is not allowing me to join has moderator ,

**Comment by roman-drozd-it** [comment]
@gunnurafi Did you solve the problem?
