### ISSUE TITLE
may I have you to replace SocketIo to ProtoJs

### ISSUE THREAD

**Issue by big-brain** [edumeet/edumeet#636]
SocketIo cannot work well in other situation
1.at native mobile(android,ios),the experience of socketIO is so bad
2.the java signalling or other language backend signalling ,the support of socketio is so bad

I sepreate the meida and signaling conroller,so signalling server can be developed by other language, but I found the socketIO is so  terrobile,will you change it to a standard websocket framework

**Comment by misi** [comment]
Can you please explain the problems with socket.io. We need to understand the issues, so can you please describe all issues in very detailed way.  Many Thanks for you cooperation!!

**Comment by roman-drozd-it** [comment]
No response for more than 1 month.
