### ISSUE TITLE
No new version published? 

### ISSUE THREAD

**Issue by fabmazz** [edumeet/edumeet#638]
From what I can gather in https://github.com/edumeet/edumeet/compare/3.3...master, the version 3.4 has been prepared, and is probably ready. However, seems like a version tag is missing...

Since the new version fixes many problems of the previous one, and there are many instances running v3.3 which are vulnerable to these bugs, it would be critical to mark it as ready.

**Comment by so010** [comment]
@misi can I tag this without breaking sth for edumeet-docker?

**Comment by fabmazz** [comment]
I'm closing this as v3.4 is out
