### ISSUE TITLE
Multiple camera problem

### ISSUE THREAD

**Issue by pioskala** [edumeet/edumeet#639]
Hi, I have a problem with multiple cameras.
I'm working on Chrome 87.0.4280.66 (Windows 10 64 bit). My cameras are physical C920 and virtual ManyCam. I didn't tested it yet with two physical but heard also about similar problem in such configuration.
EduMEET doesn't remember my last choice and always selects  ManyCam as default (what's strange in incognito mode it's always C920). When I try to change the camera it's changin it but icon of camera is red (like it would be turned off but camera is working). Now I open incognito window and connect same room. It's still working. In this case it's ok - only small problem with the icon.
Another case is when I connect to a new room, my camera is again ManyCam. Connect same room from incognito mode with C920 camera and it's working. Now I'm changing ManyCam to C920 and this video stops. Actually I'm not able to select my physical camera even after reconnecting. I've tried same combination in Google Meet but there is even bigger problem with changing C920 to ManyCam - C920 crashes.
I don't know if this is a browser related problem or eduMEET but I wanted to report this situation may happen.

**Comment by so010** [comment]
I can't reproduce this on letsmeet.no with 2 physical cameras.
There were a lot of problems according to this with incompatible older saved local stores in browser and newer versions of webclient client, In latest version we delete complete local browser store if version is not included or to old. 
Did you have these problems on letsmeet as well?

**Comment by pioskala** [comment]
Thanks, now I don't have my second camera but tomorrow I will make some more tests also on letsmeet.no.

**Comment by pioskala** [comment]
Hi @so010 I've tested with letsmeet.no and everything works correctly. Before I was testing with PSNC instance what thought is up to date but it seems I need to update it. Thanks for checking, I'm closing this issue.
