### ISSUE TITLE
Sequential calls to ./connect.js --stats deletes socket and service craches

### ISSUE THREAD

**Issue by zmartinovic** [edumeet/edumeet#640]
We are traying to record some simple metrics to our Zabbix and an idea was to trigger ./connect.js --stats every 5 min to get current number of rooms and peers. But after a few calls it would delete socket and restart the service. Here are some logs.

meeting_err.log:
Error: This socket has been ended by the other party
    at Socket.writeAfterFIN [as write] (net.js:454:14)
    at Interactive.log (/usr/local/src/edumeet/server/lib/interactiveServer.js:581:17)
    at Interface.<anonymous> (/usr/local/src/edumeet/server/lib/interactiveServer.js:47:9)
    at Interface.emit (events.js:327:22)
    at Interface.EventEmitter.emit (domain.js:485:12)
    at Interface.close (readline.js:424:8)
    at Socket.ontermend (readline.js:209:10)
    at Socket.emit (events.js:327:22)
    at Socket.EventEmitter.emit (domain.js:485:12)
    at endReadableNT (_stream_readable.js:1201:12)
Emitted 'error' event on Socket instance at:
    at emitErrorNT (net.js:1340:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'EPIPE'
}
events.js:292
      throw er; // Unhandled 'error' event

console:
root@meet-dev02:~# systemctl status edumeet.service 
● edumeet.service - edumeet is a audio / video meeting service running in the browser and powered by webRTC
   Loaded: loaded (/etc/systemd/system/edumeet.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2020-12-02 20:14:19 CET; 1min 21s ago
 Main PID: 13884 (node)
    Tasks: 11 (limit: 4700)
   Memory: 30.4M
   CGroup: /system.slice/edumeet.service
           └─13884 edumeet-server
Dec 02 20:14:19 meet-dev02 systemd[1]: Started edumeet is a audio / video meeting service running in the browser and powered by webRTC.
root@meet-dev02:~# /usr/local/src/edumeet/server/connect.js --stats | awk '/rooms/' | awk -F\: '{print $2}'
0
root@meet-dev02:~# /usr/local/src/edumeet/server/connect.js --stats | awk '/rooms/' | awk -F\: '{print $2}'
0
root@meet-dev02:~# /usr/local/src/edumeet/server/connect.js --stats | awk '/rooms/' | awk -F\: '{print $2}'
events.js:292
      throw er; // Unhandled 'error' event
      ^
Error: connect ECONNREFUSED /tmp/edumeet-server.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1141:16)
Emitted 'error' event on Socket instance at:
    at Socket.onerror (_stream_readable.js:747:14)
    at Socket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:84:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '/tmp/edumeet-server.sock'
}
root@meet-dev02:~# systemctl status edumeet.service 
● edumeet.service - edumeet is a audio / video meeting service running in the browser and powered by webRTC
   Loaded: loaded (/etc/systemd/system/edumeet.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2020-12-02 20:15:47 CET; 3s ago
 Main PID: 13994 (node)
    Tasks: 11 (limit: 4700)
   Memory: 47.3M
   CGroup: /system.slice/edumeet.service
           └─13994 edumeet-server
Dec 02 20:15:47 meet-dev02 systemd[1]: Started edumeet is a audio / video meeting service running in the browser and powered by webRTC.

Do you have any idea why is this happening or do you have a better suggestion on how to gather some metrics. I know there is prometheus exporter but I would rather have it in our Zabbix.

**Comment by zmartinovic** [comment]
Also during restart and when running connect.js --stats it triggers:
"GET /.well-known/oauth-authorization-server/sso/module.php/oidc/openid-configuration.php HTTP/1.1" 404 281 "-" "openid-client/3.15.10 (https://github.com/panva/node-openid-client)"

**Comment by so010** [comment]
Connect.js is a little bit unstable and can crash whole service :(
Did you had a look at StatusLogger class? Should work out of the box. Please send pull request if you found a good way for pushing this to zabbix!

https://github.com/edumeet/edumeet/search?q=StatusLogger

**Comment by zmartinovic** [comment]
Thanks for the tip. We will try this and let you know. Probably not as a pull request as we haven't made our branch but if it works at least as a config snippet from our example.

**Comment by zmartinovic** [comment]
@so010 thanks, StatusLogger worked just fine. We took a simplest approach by using zabbix_sender to send data to predefined item on individual host. This is our example:

StatusLogger          : class
{
	constructor()
	{
		this._queue = new AwaitQueue();
	}
	async log({ rooms, peers })
	{
		this._queue.push(async () =>
		{
			const { exec } = require('child_process');
			exec('zabbix_sender -z zabbix-server -s edumeet-host -k edumeet.rooms -o '+rooms.size);
			exec('zabbix_sender -z zabbix-server -s edumeet-host -k edumeet.peers -o '+peers.size);
		});
	}
},

**Comment by misi** [comment]
The problem is not solved, only workaround has been found so I reopen it.

**Comment by vpalmisano** [comment]
Maybe closed with this PR https://github.com/edumeet/edumeet/pull/690

**Comment by so010** [comment]
:+1:
