### ISSUE TITLE
Error Running Edumeet Server on EC2

### ISSUE THREAD

**Issue by sabkaraja** [edumeet/edumeet#644]
I followed the manual installation guide on git/readme.

changed:
- turn server details (another EC2 instance created by me)
- redis instance (created by me)
- webrtc  
-- listeningPort: 443
-- { announcedIp: '3.4.5.6', ip: '1.2.3.4' } // announcedIp set as public-ip and ip set to internal ip

I have left the tls as it is because I wanted to see if the server connected before anything else

open ports
Ports	  Protocol	Source
80			tcp		0.0.0.0/0, ::/0
443			tcp		0.0.0.0/0, ::/0
22			tcp		0.0.0.0/0, ::/0
3443		tcp		0.0.0.0/0, ::/0
40000-49999	tcp		0.0.0.0/0, ::/0
40000-49999	udp		0.0.0.0/0, ::/0

> Dec 06 18:44:34 edumeet-test-1 systemd[1]: Started edumeet is a audio / video meeting service running in the browser and powered by webRTC.
> Dec 06 18:44:35 edumeet-test-1 server.js[2776]: - process.env.DEBUG: undefined
> Dec 06 18:44:35 edumeet-test-1 server.js[2776]: - config.mediasoup.worker.logLevel: warn
> Dec 06 18:44:35 edumeet-test-1 server.js[2776]: - config.mediasoup.worker.logTags: [ 'info', 'ice', 'dtls', 'rtp', 'srtp', 'rtcp' ]
> Dec 06 18:44:35 edumeet-test-1 server.js[2776]: events.js:174
> Dec 06 18:44:35 edumeet-test-1 server.js[2776]:       throw er; // Unhandled 'error' event
> Dec 06 18:44:35 edumeet-test-1 server.js[2776]:       ^
> Dec 06 18:44:35 edumeet-test-1 server.js[2776]: Error: listen EADDRINUSE: address already in use /tmp/edumeet-server.sock
> Dec 06 18:44:35 edumeet-test-1 server.js[2776]:     at Server.setupListenHandle [as _listen2] (net.js:1263:19)
> Dec 06 18:44:35 edumeet-test-1 server.js[2776]:     at listenInCluster (net.js:1328:12)
> Dec 06 18:44:35 edumeet-test-1 server.js[2776]:     at Server.listen (net.js:1426:5)
> Dec 06 18:44:35 edumeet-test-1 server.js[2776]:     at Promise (/home/ubuntu/edumeet/server/lib/interactiveServer.js:694:11)
> Dec 06 18:44:35 edumeet-test-1 server.js[2776]:     at new Promise (<anonymous>)
> Dec 06 18:44:35 edumeet-test-1 server.js[2776]:     at module.exports (/home/ubuntu/edumeet/server/lib/interactiveServer.js:689:9)
> Dec 06 18:44:35 edumeet-test-1 server.js[2776]:     at run (/home/ubuntu/edumeet/server/server.js:138:9)
> Dec 06 18:44:35 edumeet-test-1 server.js[2776]:     at Object.<anonymous> (/home/ubuntu/edumeet/server/server.js:826:1)
> Dec 06 18:44:35 edumeet-test-1 server.js[2776]:     at Module._compile (internal/modules/cjs/loader.js:778:30)
> Dec 06 18:44:35 edumeet-test-1 server.js[2776]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
> Dec 06 18:44:35 edumeet-test-1 server.js[2776]: Emitted 'error' event at:
> Dec 06 18:44:35 edumeet-test-1 server.js[2776]:     at emitErrorNT (net.js:1307:8)
> Dec 06 18:44:35 edumeet-test-1 server.js[2776]:     at process._tickCallback (internal/process/next_tick.js:63:19)
> Dec 06 18:44:35 edumeet-test-1 server.js[2776]:     at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
> Dec 06 18:44:35 edumeet-test-1 server.js[2776]:     at startup (internal/bootstrap/node.js:283:19)
> Dec 06 18:44:35 edumeet-test-1 server.js[2776]:     at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
> Dec 06 18:44:35 edumeet-test-1 systemd[1]: edumeet.service: Main process exited, code=exited, status=1/FAILURE
> Dec 06 18:44:35 edumeet-test-1 systemd[1]: edumeet.service: Failed with result 'exit-code'.

There is nothing else running on this server. I have seen this error when two listen methods are called in the same nodejs project.  Is it something missing in the documentation or the installation setting?

**Comment by so010** [comment]
Double-check for other listening processes: `lsof -Pni -sTCP:LISTEN`

Did you define `listeningHost` in config?

**Comment by sabkaraja** [comment]
> Double-check for other listening processes: `lsof -Pni -sTCP:LISTEN`
> 
> Did you define `listeningHost` in config?

I havent sent listeningHost. Should I be setting it to my public ip? I guess it says if you dont set, it will listen to all the hosts?

listening processes:

> COMMAND   PID            USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
> systemd-r 457 systemd-resolve   13u  IPv4  18184      0t0  TCP 127.0.0.53:53 (LISTEN)
> sshd      736            root    3u  IPv4  20337      0t0  TCP *:22 (LISTEN)
> sshd      736            root    4u  IPv6  20339      0t0  TCP *:22 (LISTEN)

**Comment by so010** [comment]
No, you should not set listeningHost. And sorry i didn't read you logs in deep. 
Try to remove /tmp/edumeet-server.sock if it exists.

**Comment by sabkaraja** [comment]
removing the /tmp/edumeet-server.sock helped. Service is running now. Earlier, the service was getting stopped.

Now when I am accessing the server via the ip, ec2-xxxx.compute.amazonaws.com and the subdomain I have setup, it says refused to connect.

Is there a missing step or two that I need to do?

thanks

**Comment by so010** [comment]
Try `export DEBUG=*; npm start` on console in server directory.

**Comment by sabkaraja** [comment]
I am getting an error about mediasoup

>   mediasoup createWorker() +0ms
>   mediasoup:Worker constructor() +0ms
>   mediasoup:Worker spawning worker process: /home/ubuntu/edumeet/server/node_modules/mediasoup/worker/out/Release/mediasoup-worker --logLevel=warn --logTag=info --logTag=ice --logTag=dtls --logTag=rtp --logTag=srtp --logTag=rtcp --rtcMinPort=40000 --rtcMaxPort=49999 +0ms
>   mediasoup:Channel constructor() +0ms
>   mediasoup:PayloadChannel constructor() +0ms
>   mediasoup:Worker close() +6ms
>   mediasoup:Channel close() +1ms
>   mediasoup:PayloadChannel close() +2ms
>   mediasoup:ERROR:Worker worker process failed [pid:undefined]: spawn /home/ubuntu/edumeet/server/node_modules/mediasoup/worker/out/Release/mediasoup-worker ENOENT +0ms
>   edumeet-server:ERROR run() [error:"{ Error: spawn /home/ubuntu/edumeet/server/node_modules/mediasoup/worker/out/Release/mediasoup-worker ENOENT at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19) at onErrorNT (internal/child_process.js:415:16) at process._tickCallback (internal/process/next_tick.js:63:19) at Function.Module.runMain (internal/modules/cjs/loader.js:834:11) at startup (internal/bootstrap/node.js:283:19) at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3) errno: 'ENOENT', code: 'ENOENT', syscall: 'spawn /home/ubuntu/edumeet/server/node_modules/mediasoup/worker/out/Release/mediasoup-worker', path: '/home/ubuntu/edumeet/server/node_modules/mediasoup/worker/out/Release/mediasoup-worker', spawnargs: [ '--logLevel=warn', '--logTag=info', '--logTag=ice', '--logTag=dtls', '--logTag=rtp', '--logTag=srtp', '--logTag=rtcp', '--rtcMinPort=40000', '--rtcMaxPort=49999' ] }"] +0ms
>

**Comment by sabkaraja** [comment]
looks like mediasoup doesnt get installed properly.
need to run install with 'sudo' 

if you already installed and are facing issue - remove mediasoup and add it again with `sudo npm i mediasoup`
