### ISSUE TITLE
Failed at the mediasoup@3.6.28 postinstall script.

### ISSUE THREAD

**Issue by rajeevvishva29** [edumeet/edumeet#645]
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mediasoup@3.6.28 postinstall: `node npm-scripts.js postinstall`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mediasoup@3.6.28 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by so010** [comment]
OS? eduMEET version/branch? node version?

**Comment by rajeevvishva29** [comment]
Windows 10 + eduMEET Manual installation + nodejs v13.14.0

**Comment by so010** [comment]
Windows is not best choice for development, mediasoup (our media switch) has some issues her eg:
https://mediasoup.org/documentation/v3/mediasoup/installation/#windows
and here:
https://mediasoup.discourse.group/t/installation-problem-windows-postinstall-script/527/7
I think the last post there is best way to go:
```
you have to activate and use the Linux environment in your windows 10
Step 1 - https://docs.microsoft.com/en-us/windows/wsl/install-win10
1.1 - after completed all, open Windows Terminal, then type/run “wsl” to switch to the Linux environment before going to Step 2.
```

**Comment by misi** [comment]
Try to use docker with linux containers on windows.. 
https://docs.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/linux-containers

**Comment by roman-drozd-it** [comment]
No further response for much over 1 month. Closed.
