### ISSUE TITLE
White page on iPhone 12 w/ Chrome and Firefox. Safari works

### ISSUE THREAD

**Issue by L4ky** [edumeet/edumeet#647]
Hi, 
i tried to open edumeet 3.4 from an iPhone 12 and i have some issues.

Safari works fine.
Chrome and Firefox show a blank page.

On Edumeet 3.3 the issue was different: edumeet displayed the unsupported browser page ( even if chrome installed version was way above the requirements ).

Unfortunately i have no more info to give, but i can retrieve everything that may be useful to find the bug.

Thank you
Luca

**Comment by roman-drozd-it** [comment]
Similar to #663
