### ISSUE TITLE
Resource Usage

### ISSUE THREAD

**Issue by 12nick12** [edumeet/edumeet#651]
Hi, I was wanting to use this for a large meeting around 80-100 clients and was curious if this is capable of scaling that large. There will be one video client and the rest will just be watching. What kind of resource usage is expected per end user?

**Comment by mi4aux** [comment]
edumeet is capable of scaling that large, for sure ...

my experience on a server (4core at 2,2ghz and 4gb ram) with over 120 participants:
cpu-usage ~50%, ram-usage ~2,4gb and network peaked at ~150mbit/s (~18mb/s).

at the moment there is no real broadcasting/webinar mode avaiable, but you can use edumeet simular to it (like [misi mentioned](https://github.com/edumeet/edumeet/issues/566#issuecomment-698202037)), and with some other recommended settings:
- set one presenter
- mute participants audio and video
- set lastN, limit maxLastN ... maybe set lockLastN to true
- turn off notificationSounds (set it as default for clients) 
- turn off showNotifications (set it as default for clients)
- standard video- and screenshare rates/resolutions should be fine

on client side not much needed ... it just has to handle one stream ...

**Comment by 12nick12** [comment]
Perfect, thank you for the reply.
