### ISSUE TITLE
Is it possible to run edumeet server in internal corporate network? 

### ISSUE THREAD

**Issue by hkizilhan** [edumeet/edumeet#652]
If we make routes for server(3443) and media ports(40000-49999) on the coporate router, is it works?

**Comment by mi4aux** [comment]
sure you can, you have just to proxy / route incoming requests on public ip to your internal ip
and with port forwarding for mentioned ports: `productionPort  : 443` (if not changed, 3443 is just standard development port)
and `rtcMinPort : 40000, rtcMaxPort : 49999` ... maybe think also to handle requests on standard http port 80
and set / change your server ip adress in `listenIps` array

**Comment by hkizilhan** [comment]
@mi4aux Thanks for answer. 
Another question:
 is this setup make any difference for TURN server? So, can users that coming behind another corporate/strict firewall  use TURN server?

**Comment by mi4aux** [comment]
for your TURN server its recommendable, that it runs on port 80 / 443 (not the standard ports 3478 / 5349),
so user that sit behind a strict firewall, can reach it properly ... 80 / 443 shouldn't be a problem for most corporate networks or on strict firewalls
