### ISSUE TITLE
participant's name is hard to read on white background 

### ISSUE THREAD

**Issue by nullaegy** [edumeet/edumeet#655]
it's almost impossible to read the participant's name when the webcam's background is white on the bottom left corner.
I suggest a black outline or a semi-transparent black background.

**Comment by misi** [comment]
Please help me little bit and propose howto adjust. This is the part of the actual code css:
https://github.com/edumeet/edumeet/blob/befb3df1448e52ab73bc1f8b00bd568d6b1ef67b/app/src/components/VideoContainers/VideoView.js#L148

We use material ui theme settimgs, so you can make in theory own theme and css adjustment/modification from config: https://github.com/edumeet/edumeet/blob/befb3df1448e52ab73bc1f8b00bd568d6b1ef67b/app/public/config/config.example.js#L171

**Comment by nullaegy** [comment]
probably a small css adjustment - semi transparent bg - would solve the issue, something like this:
`background-color: #0000007d;`

**Comment by roman-drozd-it** [comment]
@misi I think the proposed background "fix" should be added as a standard display of participant's name. It's looks better and it's more legible than the current style. Should I add it to develop branch?

**Comment by misi** [comment]
Yes thanks!

**Comment by roman-drozd-it** [comment]
@nullaegy The fix has been added to a develop branch. Please check. If everything is ok please close the issue. Thanks.

**Comment by misi** [comment]
LGTM

**Comment by nullaegy** [comment]
Thank you!
