### ISSUE TITLE
White Screen Error?

### ISSUE THREAD

**Issue by waycos** [edumeet/edumeet#663]
I am getting an error on iPhone 6 and above phones. Edumeet version 3.4.0. When participants join the conference, they encounter a white screen

**Comment by Aleeeeeeeex** [comment]
i got same, just restarted service on server and it works again.. Dont know why.

**Comment by roman-drozd-it** [comment]
@waycos  Did you solve the problem?

**Comment by roman-drozd-it** [comment]
similar to # 647
