### ISSUE TITLE
autoMuteThreshold = 0 - Still join with unmuted mic

### ISSUE THREAD

**Issue by Aleeeeeeeex** [edumeet/edumeet#664]
I have autoMuteThreshold = 0, but all user still join with mic enabled.. what am i doing wrong? 

Tested from Chrome, Edge and iPhone.

**Comment by Astagor** [comment]
It is a bug. I will fix it.

**Comment by Astagor** [comment]
Please get the newest develop, it should be fixed. If not, reopen this issue.
