### ISSUE TITLE
Maximum users in a single session support

### ISSUE THREAD

**Issue by Alex-YddeR** [edumeet/edumeet#670]
Hi Team,

Is there any test report or observation what is the maximum users in a single session with at-least LAST N about 10?

Thanks

**Comment by Aleeeeeeeex** [comment]
You can see here: #223

**Comment by Alex-YddeR** [comment]
Thanks, So the limit of 500 consumers per room is not there anymore? we can have as many as consumers on the base of cpu cores and threads.

Am i right.?

Thanks

**Comment by Astagor** [comment]
Yes, the 500 consumers per room is not a limit any more, as we use now Mediasoup routers to distribute users between the workers. But.... you cannot ensure that in some scenarios, the CPU cores will not overload, as you really scale now using the routerScaleSize in server/config. This value is the threshold of users in room after which a new user gets assigned to a new router. This is a value that should be set using empiric testing of your server cores. However, this number is difficult to assess as the load depends on who is muted, who sends video and so on. So you can have 20 users and the worker can have 60% load, but you can have 16 an 90% load. On my production server, when I allow maxLastN 20, I have set routerScaleSize to 15. On a server where I use it in a webinar mode, teacher maxLastN 20, studedents maxLastN 2, I have set  routerScaleSize  to 25.
