### ISSUE TITLE
Cache issue for login?

### ISSUE THREAD

**Issue by Aleeeeeeeex** [edumeet/edumeet#671]
Yesterday i was logged in and used the system.

Today i just opened the same url, and i see that i am still logged in from looking at the login button.. (It is saying log out)

When i press "Join room" i cant get access due to closed room. 

If i press logout and login again, it works just fine and i can enter the room.

System is only letting auth. users in, all normal users need to be allowed manually.

So it looks like some sessions are set, but i am missing the roles? 

![image](https://user-images.githubusercontent.com/22255599/103992019-ce699380-5193-11eb-951b-448729fb79a4.png)

**Comment by so010** [comment]
@Aleeeeeeeex which version are you running. We had a lot of problems with synchronizing of local-storage and session-state.
But should be resolved in develop.

**Comment by Kampflaus** [comment]
Hi there, will this soon be merged into master branch?
