### ISSUE TITLE
Consumer not found 

### ISSUE THREAD

**Issue by Astagor** [edumeet/edumeet#675]
I'm getting in the logs a lot of "Error: consumer with id "b7bc6235-1ce9-4822-8470-cabac1708249" not found" from server/lib/Room.js:1227.

In 1883 we have
		consumer.on('transportclose', () =>
		{
			// Remove from its map.
			consumerPeer.removeConsumer(consumer.id);
		});

Shouldn't we notify the peer that the transport has been closed? We do it on
producerclose
producerpause
producerresume
but not on transportclose.

Is this a bug? @so010

**Comment by Astagor** [comment]
Reading [https://github.com/versatica/mediasoup-website/blob/master/documentation/v3/communication-between-client-and-server.md#communicating-actions-and-events](url) :
"Consumer "transportclose". The client should call close() on the corresponding local consumer."
so I think we should notify the peer so he can do a close on the local consumer.

**Comment by Astagor** [comment]
Hmm, no comments? I have added in the event handler:
this._notification(consumerPeer.socket, 'consumerClosed', { consumerId: consumer.id });
and have deployed it on my 6 production servers. I'll watch the logs and see.

**Comment by so010** [comment]
Without looking through everything I think you are right! Can you make a PR?

**Comment by Astagor** [comment]
Done.

**Comment by Astagor** [comment]
Added PR #687

**Comment by roman-drozd-it** [comment]
@Astagor I'm closing it as completed/merged to develop by @so010.
