### ISSUE TITLE
server url not configurable anymore on app

### ISSUE THREAD

**Issue by MrSnoozles** [edumeet/edumeet#677]
Hi,

and first of all thank you for this great software.
I wanted to upgrade my installation running 3.2.1 to 3.4. Unfortunately I can't get it to work anymore, because there is no way to define an external server anymore. Before there was the `multipartyServer` configuration variable.

Is there a reason this was removed completely? Would it be possible to have this as an optional setting again?

**Comment by so010** [comment]
Do you want to host static html and edumeet server on separated servers?

**Comment by MrSnoozles** [comment]
Jipp, exactly.

**Comment by so010** [comment]
Can I ask why? If you are interested in load balancing have a look at https://github.com/edumeet/edumeet/blob/master/HAproxy.md
You can use this as well for forwarding server traffic to separated media server.

For now the client tries to connect eduMeet-server from start-URL. 

The change was this commit: https://github.com/edumeet/edumeet/commit/71e695b912598469a949b46d91a2843f75d22964#diff-16944e4ef66a7b1bd89a48867205696991b4e209e9761f33fd52342ccf695392
And the idea was as long as I remember to make setup easier.
As you see in the commit it would be quite easy to make an optional config value for this.

**Comment by MrSnoozles** [comment]
Because I'm using two client (on different urls) with one server. One has a different styling defined in app/config.js
It's probably a bit of an unusual use case but it was perfectly doable with the old version. Could I commit a PR that reenable that feature (but optionally, so the default setup is still easier)?
