### ISSUE TITLE
Federated login error

### ISSUE THREAD

**Issue by pioskala** [edumeet/edumeet#678]
I've tested federated login feature with added user roles and have problem when try to login from main page of eduMEET. When I login from room view, error doesn't appear. Here you can see log from browser console.
[meet.pionier.net.pl-1611244177501.log](https://github.com/edumeet/edumeet/files/5850616/meet.pionier.net.pl-1611244177501.log)
Could it be a problem with IdP, server or eduMEET?

**Comment by Astagor** [comment]
JoinDialog.js line 190:
displayName = displayName.trimLeft();
but how come that dispalyName is not a String?

in the browser console, with debug enabled, you should have something like this:
'receiveFromChildWindow() | [data:"..."]'

what is set as the value of displayName there?

**Comment by pioskala** [comment]
Thank you Astagor, now I see what's going on there. I've replaced default userMapping from server config with another one (similar to this one https://github.com/edumeet/edumeet/blob/develop/server/config/config.example.js#L206 ), where displayName is not set.. this way it's not a String! I see now that I need to merge both userMapping. Also thanks for hint with debug.
