### ISSUE TITLE
mic volume problem

### ISSUE THREAD

**Issue by dharmeshmaniar** [edumeet/edumeet#679]
Hi,

Some of the users' mic volume comes very low and other users in the room are barely able to hear them.
While these users mentioned that there is nothing wrong with their mic or the headset mic. They also mentioned that their voice is heard properly on other platforms like zoom or meet.

Upon diagnosing I found that recording device level on these users' machine was very low. Increasing the level manually under properties of recording device increased the volume.
Whereas zoom and meet are not facing this problem. 

Anyway to solve this without manually increasing the recording device level?

**Comment by so010** [comment]
try in app config 
`autoGainControl      : true, // default : false`

I consider to switch default to true.

**Comment by dharmeshmaniar** [comment]
Have tried autoGainControl : true but still problem with some users

**Comment by varundabke** [comment]
Keep noise threshold to lower value - it worked for me in several cases.
