### ISSUE TITLE
RoomClient.js uses associative arrays with deviceId key for webcams/audiodevices

### ISSUE THREAD

**Issue by jmencak** [edumeet/edumeet#694]
There are cases where [deviceId](https://developer.mozilla.org/en-US/docs/Web/API/MediaDeviceInfo/deviceId) may not be unique on a system, especially when using the same devices from one manufacturer.  This may result in the same `[vendor]:[product]` and the same `deviceId`.  Only one of the devices will then be visible in eduMEET.

The reason is the the fact `RoomClient.js` uses associative arrays with `deviceId` key to store the available devices.

Edit 2021-02-18:
Actualy, the two devices from the same manufacturer *are* visible as they have a unique `deviceId`.  Devices not visible are only the *Monitor* devices which share the same `deviceId` and only Firefox actually seems to show them anyway.  This is probably a very low-priority issue.

**Comment by so010** [comment]
Could you run in webconsole: 
CLIENT._webcams
and check if deviceId is actually same for both devices. I think the error is that we use label instead of deviceId as identifier.

**Comment by jmencak** [comment]
I don't own the identical webcams, so showing the identical `deviceId` with the two headphones from the same manufacturer connected:

```
$ lsusb|grep 'C-Media'
Bus 001 Device 010: ID 0d8c:013a C-Media Electronics, Inc. 
Bus 001 Device 012: ID 0d8c:013a C-Media Electronics, Inc. 
```

```
CLIENT._audioDevices
{…}
​
"4z0Lv4TQhxp0smkdry8l7osS+1AYeTaj5jS0M79dQzs=": MediaDeviceInfo { deviceId: "4z0Lv4TQhxp0smkdry8l7osS+1AYeTaj5jS0M79dQzs=", kind: "audioinput", label: "Monitor of USB PnP Sound Device Analog Stereo", … }
​
"BVkuz59Cuv69BtgRf31tNHVo8nRI3WA+8ADGghdG2+I=": MediaDeviceInfo { deviceId: "BVkuz59Cuv69BtgRf31tNHVo8nRI3WA+8ADGghdG2+I=", kind: "audioinput", label: "USB PnP Sound Device Mono", … }
​
"Jlj63cea4S9nJwiEuw8tRrtV0ODnRhjQWkfQKtBmBEc=": MediaDeviceInfo { deviceId: "Jlj63cea4S9nJwiEuw8tRrtV0ODnRhjQWkfQKtBmBEc=", kind: "audioinput", label: "USB PnP Sound Device Multichannel", … }
​
"M95A1MzhzSxO4gkWnsvRCcg3p8PoUT5DPPOQh4Cje0U=": MediaDeviceInfo { deviceId: "M95A1MzhzSxO4gkWnsvRCcg3p8PoUT5DPPOQh4Cje0U=", kind: "audioinput", label: "Built-in Audio Analog Stereo", … }
​
"y4JjEkU0aPcUdijDfK8dZvQDo7iN01ofO09S9taK/AU=": MediaDeviceInfo { deviceId: "y4JjEkU0aPcUdijDfK8dZvQDo7iN01ofO09S9taK/AU=", kind: "audioinput", label: "Monitor of Built-in Audio Analog Stereo", … }
​

```

I've added extra logging in `_updateAudioDevices()` / `RoomClient.js`.  The identical `deviceId` is `4z0Lv4TQhxp0smkdry8l7osS+1AYeTaj5jS0M79dQzs=`, however, I notice that this is the "Monitor" audio device and the two real headsets `USB PnP Sound Device Mono` and `USB PnP Sound Device Multichannel` were still selectable and worked.

```
deviceId: zZBiMqUxcbFpgXCxOZgKwL88Qh/A8V676vc9E9Pg7cs=; label: Integrated Camera: Integrated C RoomClient.js:4128:12
deviceId: y4JjEkU0aPcUdijDfK8dZvQDo7iN01ofO09S9taK/AU=; label: Monitor of Built-in Audio Analog Stereo RoomClient.js:4128:12
deviceId: M95A1MzhzSxO4gkWnsvRCcg3p8PoUT5DPPOQh4Cje0U=; label: Built-in Audio Analog Stereo RoomClient.js:4128:12
deviceId: 4z0Lv4TQhxp0smkdry8l7osS+1AYeTaj5jS0M79dQzs=; label: Monitor of USB PnP Sound Device Analog Stereo RoomClient.js:4128:12
deviceId: Jlj63cea4S9nJwiEuw8tRrtV0ODnRhjQWkfQKtBmBEc=; label: USB PnP Sound Device Multichannel RoomClient.js:4128:12
deviceId: 4z0Lv4TQhxp0smkdry8l7osS+1AYeTaj5jS0M79dQzs=; label: Monitor of USB PnP Sound Device Analog Stereo RoomClient.js:4128:12
deviceId: BVkuz59Cuv69BtgRf31tNHVo8nRI3WA+8ADGghdG2+I=; label: USB PnP Sound Device Mono RoomClient.js:4128:12
```
