### ISSUE TITLE
Can we run app and server component separately!!

### ISSUE THREAD

**Issue by Alex-YddeR** [edumeet/edumeet#699]
Dear Team,

Can i run app and server component separately, since i wanted server component to be deployed in load balance using HA Proxy and run app component using AWS cloud-front.

Please help us in steps to install server component only in load balance

Thanks

**Comment by so010** [comment]
It is related to that: https://github.com/edumeet/edumeet/issues/677  ?
Or do you want to separate media-nodes from signalling? This is not possible yet - have a look at feathttps://github.com/edumeet/edumeet/tree/feat-media-node which should do this if finished

**Comment by nareshinstavc** [comment]
Got it from #683 

Thanks
Naresh
