### ISSUE TITLE
Issue: Actually rtp media does not have diffserv marking. GoogDscp deprecated?

### ISSUE THREAD

**Issue by misi** [edumeet/edumeet#702]
**Replace googDscp?**

https://github.com/edumeet/edumeet/blob/a83a27b72c4a812f5e008320f927f56092978b5b/app/src/RoomClient.js#L82-L85

**With**
```
// Set IP DSCP field.
await producer.setRtpEncodingParameters({ networkPriority: 'high' });
```

**Comment by vpalmisano** [comment]
Adding some links for discussion:

- https://chromium.googlesource.com/external/webrtc/+/master/api/rtp_parameters.h
- https://github.com/w3c/webrtc-pc/issues/1888
- https://source.chromium.org/chromium/chromium/src/+/master:third_party/webrtc/media/engine/webrtc_voice_engine.cc;drc=ad3258647ec3945730de4673522c0f09a6663f42;l=1553

**Comment by misi** [comment]
Add the priority draft
* https://www.w3.org/TR/webrtc-priority

**Comment by misi** [comment]
Implementations are one step behind standardization..
* Tracking issue about Chrome implementation of rtcrtpencodingparameters priority: 
   https://bugs.chromium.org/p/webrtc/issues/detail?id=8630
* mediasoup-client use it: https://github.com/versatica/mediasoup-client/blob/4693b5b80f20de9b95955a4939bc9fdd039a0548/lib/handlers/Chrome74.js#L302

**Comment by vpalmisano** [comment]
> It's finished "per-sender" natively, meaning that you can set the bitrate priority between senders, but not per layers of a sender (encoding parameters). 

So it does make sense to apply, for example,  an higher `networkPriority` to audio producers and a low priority to video producers.

**Comment by misi** [comment]
IMHO networkPriority should be medium for video, and for audio high, so AF42 and AF42 according this:
https://source.chromium.org/chromium/chromium/src/+/master:third_party/webrtc/media/engine/webrtc_video_engine.cc;l=1096?q=_AF41&ss=chromium

**Comment by vpalmisano** [comment]
We could add a configuration property in the app config.js:
`networkPriorities: {
  audio: 'high',
  video: 'medium',
  data: 'low'
}`

**Comment by misi** [comment]
Af41 is lower priority class then EF, so it is even if both  audio and video is high you will get such order that audio has the highest priority.
So I agree and my proposal to have to additional to the different video classes (secondary video, screen share)

networkPriorities: { audio: 'high', mainVideo: 'high', additionalVideos: 'medium' , screenShare: 'medium'  data: 'low' }

**Comment by Astagor** [comment]
Sounds good to me @misi

**Comment by misi** [comment]
The problem is that I don't find the networkPriority for webtorrent.. :(. 
I can't set data priority to "low". it will be  the default and so I will remove from config until we don't find a way to add it.
