### ISSUE TITLE
Collect stats with ObservRTC

### ISSUE THREAD

**Issue by misi** [edumeet/edumeet#705]
Deploy with edumeet an ObserRTC
* https://github.com/ObserveRTC/observer-js
* https://github.com/ObserveRTC/observer

**Comment by vpalmisano** [comment]
Another solution could be: https://github.com/fippo/rtcstats

**Comment by misi** [comment]
https://observertc.org/docs/

**Comment by misi** [comment]
browser and metrics implementations: https://webrtc-stats.callstats.io/

**Comment by vpalmisano** [comment]
The GET request to `https://webrtc-stats.callstats.io/stats/scenario/list` fails after a timeout with 502 status.
