### ISSUE TITLE
Need guidance on room creation

### ISSUE THREAD

**Issue by ShivKumarSaini** [edumeet/edumeet#706]
How can I get to know that a particular room ID is already created and there is no need to create a room with that ID again before calling roomClient.join method ?

Please help or point me to the api / source code. Thanks!

**Comment by so010** [comment]
server.js has a Map() of rooms.
Look at getOrCreateRoom() function there:
https://github.com/edumeet/edumeet/blob/7b5126d5935ab10a026141cd13a7ef9adb22a943/server/server.js#L826

**Comment by so010** [comment]
From client side there is no request for this yet.
Client sends roomid while establishing connection with socket.io and room is created automatically if not existent.

**Comment by ShivKumarSaini** [comment]
okay. thanks
