### ISSUE TITLE
RTC listening ports range should be distributed among mediasoup workers

### ISSUE THREAD

**Issue by vpalmisano** [edumeet/edumeet#708]
In the current configuration all workers listen on the same UDP port range, leading to possible port range conflicts between connections listening on different workers, especially when the number of connections is high and/or the port range is small.

Ref. https://mediasoup.discourse.group/t/using-separate-rtcminport-rtcmaxport-setting-for-plaintransport/2193/4

**Comment by Astagor** [comment]
I have a bit different alg

	const portSpan = Math.floor((config.mediasoup.worker.rtcMaxPort - config.mediasoup.worker.rtcMinPort + 1) / numWorkers);

	for (let i = 0; i < numWorkers; ++i)
	{
		const worker = await mediasoup.createWorker(
			{
				logLevel   : config.mediasoup.worker.logLevel,
				logTags    : config.mediasoup.worker.logTags,
				rtcMinPort : (config.mediasoup.worker.rtcMinPort + i * portSpan),
				rtcMaxPort : (config.mediasoup.worker.rtcMinPort + (i + 1) * portSpan - 1)
			});
