### ISSUE TITLE
Simulcast Video Resolution

### ISSUE THREAD

**Issue by Alex-YddeR** [edumeet/edumeet#713]
Why it is always low resolution( 320x180) receiving by user 2 when user1 kept in on 640*360. And also resolution does not affect based on the video window size. how does it works.

same works well on letsmeet.no

Thanks

**Comment by so010** [comment]
You talking about actual develop branch?
Browser version?

**Comment by Astagor** [comment]
I can tell you from my experience, that the simulcast logic is a bit fuzzy. My example
I'm sending 1280x720 video and have 3 simulcast profiles defined. Then everything works as expected, all the resolution adoption works. However, if I send 640x360 video and still have 3 simulcast profiles, then the receiver ALWYS gets the second profile, never the highest, even if the preferred layers are set correct.  If I define 2 simulcast profiles for 640x360, then it starts to work fine again. It seems that, the browser when we are sending 640x360 video only encodes if 2 lowest profiles.

**Comment by Alex-YddeR** [comment]
Yes its on develop branch @Astagor explained it well. Problem when use default settings as below

simulcastEncodings :
[
{ scaleResolutionDownBy: 4 },
{ scaleResolutionDownBy: 2 },
{ scaleResolutionDownBy: 1 }
],

but it seems to be fine when use as below but needs to check thoroughly

simulcastEncodings :
[
{ maxBitRate: 50000 },
{ maxBitRate: 1000000 },
{ maxBitRate: 3800000 }
],
Thanks

**Comment by Astagor** [comment]
@Alex-YddeR please try the current develop. Copy the encoding profiles from config.example.js to your config.js

**Comment by Alex-YddeR** [comment]
@Astagor Thanks for the update. will try it now.

**Comment by roman-drozd-it** [comment]
Did it work for you @Alex-YddeR ? If so, please close the issue.
