### ISSUE TITLE
Adapt the control bars sizes to the available peer space

### ISSUE THREAD

**Issue by vpalmisano** [edumeet/edumeet#716]
![screenshot-10 0 0 137_3443-2021 03 12-15_36_14](https://user-images.githubusercontent.com/283319/110954506-dc30c600-8348-11eb-8faf-c88a30f99b93.png)

**Comment by Astagor** [comment]
I would say, for own controls:
 1 if "Hidden media controls" in settings is OFF, then the option "Separate media controls" should activate automatically, like the user would choose it in settings
 2 if  "Hidden media controls" in settings is ON, display the control buttons as it is on your picture, so they are beyond the video frame. Just make sure they are on a higher layer then the top bar. This way we have large clickable buttons

For remote peers I think it should also be like in option 2 above, display the control buttons so they are beyond the video frame. Just make sure they are on a higher layer then the top bar. They should not be squeezed like this.

**Comment by roman-drozd-it** [comment]
similar to #610
