### ISSUE TITLE
Add to spotlight usage

### ISSUE THREAD

**Issue by Alex-YddeR** [edumeet/edumeet#727]
in FilmStrip view when a participant added to spotlight it does not add the user to main window layout it always switches when someone speaks even the user added to spotlight.
i want to know what exactly is the usage of add to spotlight.

Thanks

**Comment by Astagor** [comment]
Well, the putting of a peer into spotlight just means that the peer will be visible if there are more peers than lastN video slots. There is a partially written code that enables in FilmStrip to decide which peer is the one in the big view, but this is not active. If there are no objections, I could reactivate it and change it a bit. I would propose that the newest added into spotlights is the one pinned in the bid video slot. Objections?

**Comment by Alex-YddeR** [comment]
This will be good feature since when someone presenting I need presenter video and screen share to be side by side and at the same time I don’t want any switching to be happened in VAD when enabled the spotlight.

**Comment by Astagor** [comment]
@Alex-YddeR I have merged the changes into develop. Please try it out. Now you have a pinning icon on the small videos in filmstrip mode.

**Comment by Alex-YddeR** [comment]
@Astagor **Amazing** it works as expected.Thanks so much for this feature.

**Comment by Astagor** [comment]
Great!
