### ISSUE TITLE
Bug: unable to join more then 19 peers in a room

### ISSUE THREAD

**Issue by zmartinovic** [edumeet/edumeet#733]
Hi,

we have a problem that we are unable to join more then 19 persons in a meeting. When extra people try to join while not authenticated (they access lobby), I get list of blank users (pic in attachment). If more than 19 moderators try to access same room, they end up in an empty room on the same URL.
Here is our entire server config:
```
const os = require('os');
const userRoles = require('../userRoles');

const {
	BYPASS_ROOM_LOCK,
	BYPASS_LOBBY
} = require('../access');

const {
	CHANGE_ROOM_LOCK,
	PROMOTE_PEER,
	MODIFY_ROLE,
	SEND_CHAT,
	MODERATE_CHAT,
	SHARE_AUDIO,
	SHARE_VIDEO,
	SHARE_SCREEN,
	EXTRA_VIDEO,
	SHARE_FILE,
	MODERATE_FILES,
	MODERATE_ROOM
} = require('../permissions');

const AwaitQueue = require('awaitqueue');
// const axios = require('axios');

module.exports =
{

	// Auth conf
	auth :
	{
		lti :
		{
			consumerKey    : 'xxxx',
			consumerSecret : 'xxxxx'
		},
		strategy : 'oidc',
		oidc:
		{
			// The issuer URL for OpenID Connect discovery
			// The OpenID Provider Configuration Document
			// could be discovered on:
			// issuerURL + '/.well-known/openid-configuration'

			issuerURL     : 'xxxxxxx,
			clientOptions :
			{
				client_id     : 'xxxxxxx',
				client_secret : 'xxxxxxx',
				scope         : 'openid profile email cn hrEduPersonAffiliation',
				// where client.example.com is your multiparty meeting server
				redirect_uri  : 'xxxxxxx'
			}

		}
	},
	// URI and key for requesting geoip-based TURN server closest to the client
	turnAPIKey    : 'xxxxxxx',
	turnAPIURI    : 'https://api.turn.geant.org/turn',
	turnAPIparams : {
		'uri_schema' 	: 'turn',
		'transport' 		: 'tcp',
		'ip_ver'    		: 'ipv4',
		'servercount'	: '2'
	},
	// Backup turnservers if REST fails or is not configured
	backupTurnServers : [
		{
			urls : [
				'turn:ltc.turn.geant.org:443?transport=tcp'
			],
			username   : 'xxxxxxx',
			credential : 'xxxxxxx'
		}
	],
	fileTracker  : 'wss://tracker.lab.vvc.niif.hu:443',
	//redisOptions : {},
	//redisOptions : { host: '10.8.62.11' },
	redisOptions : { host: 'xxxxxxx', prefix: 'meet_'},
	// session cookie secret
	cookieSecret : 'T0P-S3cR3t_cook!e',
	cookieName   : 'edumeet.sid',
	// if you use encrypted private key the set the passphrase
	tls          :
	{
		cert : `${__dirname}/../certs/mediasoup-demo.localhost.cert.pem`,
		// passphrase: 'key_password'
		key  : `${__dirname}/../certs/mediasoup-demo.localhost.key.pem`
	},
	// listening Host or IP 
	// If omitted listens on every IP. ("0.0.0.0" and "::")
	// listeningHost: 'localhost',
	// Listening port for https server.
	listeningPort         : 80,
	// Any http request is redirected to https.
	// Listening port for http server.
	//listeningRedirectPort : 80,
	// Listens only on http, only on listeningPort
	// listeningRedirectPort disabled
	// use case: loadbalancer backend
	httpOnly              : true,
	// WebServer/Express trust proxy config for httpOnly mode
	// You can find more info:
	//  - https://expressjs.com/en/guide/behind-proxies.html
	//  - https://www.npmjs.com/package/proxy-addr
	// use case: loadbalancer backend
	trustProxy            : '161.53.2.121, 161.53.2.122',
	//trustProxy		: '161.53.252.203',
	// This logger class will have the log function
	// called every time there is a room created or destroyed,
	// or peer created or destroyed. This would then be able
	// to log to a file or external service.
	StatusLogger          : class
	{
		constructor()
		{
			this._queue = new AwaitQueue();
		}

		// rooms: rooms object
		// peers: peers object
		// eslint-disable-next-line no-unused-vars
		async log({ rooms, peers })
		{
			this._queue.push(async () =>
			{
				// Do your logging in here, use queue to keep correct order
				// eslint-disable-next-line no-console
				// eslint-disable-next-line no-console
			})
				.catch((error) =>
				{
					// eslint-disable-next-line no-console
					console.log('error in log', error);
				});
		}
	},
	// This function will be called on successful login through oidc.
	// Use this function to map your oidc userinfo to the Peer object.
	// The roomId is equal to the room name.
	userMapping : async ({ peer, roomId, userinfo }) =>
	{
		if (userinfo.picture != null)
		{
			if (!userinfo.picture.match(/^http/g))
			{
				peer.picture = `data:image/jpeg;base64, ${userinfo.picture}`;
			}
			else
			{
				peer.picture = userinfo.picture;
			}
		}

		if (userinfo.nickname != null)
		{
			peer.displayName = userinfo.nickname;
		}

		if (userinfo.name != null)
		{
			peer.displayName = userinfo.name;
		}

		if (userinfo.email != null)
		{
			peer.email = userinfo.email;
		}

                if (userinfo.lti && userinfo.lti.roles && userinfo.lti.roles.includes('Administrator'))
		{
			peer.addRole(userRoles.AUTHENTICATED);
			peer.addRole(userRoles.ADMIN);
		}
		
		if (userinfo.lti && userinfo.lti.roles && userinfo.lti.roles.includes('Instructor'))
		{
			peer.addRole(userRoles.AUTHENTICATED);
			peer.addRole(userRoles.MODERATOR);
		}
		
		if (userinfo.lti && userinfo.lti.roles && userinfo.lti.roles.includes('Learner'))
		{
			peer.addRole(userRoles.AUTHENTICATED);
		}

		if (userinfo.hrEduPersonAffiliation)
		{
			peer.displayName = userinfo.cn[0];
			peer.addRole(userRoles.AUTHENTICATED);
			if (userinfo.hrEduPersonAffiliation.includes('djelatnik') && userinfo.email.endsWith('@srce.hr'))
			{
				peer.addRole(userRoles.MODERATOR);
			}
		}
		
	},
	// All users have the role "NORMAL" by default. Other roles need to be
	// added in the "userMapping" function. The following accesses and
	// permissions are arrays of roles. Roles can be changed in userRoles.js
	//
	// Example:
	// [ userRoles.MODERATOR, userRoles.AUTHENTICATED ]
	accessFromRoles : {
		// The role(s) will gain access to the room
		// even if it is locked (!)
		[BYPASS_ROOM_LOCK] : [ userRoles.MODERATOR ],
		// The role(s) will gain access to the room without
		// going into the lobby. If you want to restrict access to your
		// server to only directly allow authenticated users, you could
		// add the userRoles.AUTHENTICATED to the user in the userMapping
		// function, and change to BYPASS_LOBBY : [ userRoles.AUTHENTICATED ]
		[BYPASS_LOBBY]     : [ userRoles.AUTHENTICATED ]
	},
	permissionsFromRoles : {
		// The role(s) have permission to lock/unlock a room
		[CHANGE_ROOM_LOCK] : [ userRoles.MODERATOR ],
		// The role(s) have permission to promote a peer from the lobby
		[PROMOTE_PEER]		 : [ userRoles.MODERATOR ],
		// The role(s) have permission to give/remove other peers roles
		[MODIFY_ROLE]			 : [ userRoles.MODERATOR ],
		// The role(s) have permission to send chat messages
		[SEND_CHAT]				 : [ userRoles.NORMAL ],
		// The role(s) have permission to moderate chat
		[MODERATE_CHAT]		 : [ userRoles.MODERATOR ],
		// The role(s) have permission to share audio
		[SHARE_AUDIO]			 : [ userRoles.MODERATOR, userRoles.PRESENTER ],
		// The role(s) have permission to share video
		[SHARE_VIDEO]			 : [ userRoles.MODERATOR, userRoles.PRESENTER ],
		// The role(s) have permission to share screen
		[SHARE_SCREEN]		 : [ userRoles.MODERATOR, userRoles.PRESENTER ],
		// The role(s) have permission to produce extra video
		[EXTRA_VIDEO]			 : [ userRoles.MODERATOR, userRoles.PRESENTER ],
		// The role(s) have permission to share files
		[SHARE_FILE]			 : [ userRoles.MODERATOR, userRoles.PRESENTER ],
		// The role(s) have permission to moderate files
		[MODERATE_FILES]	 : [ userRoles.MODERATOR ],
		// The role(s) have permission to moderate room (e.g. kick user)
		[MODERATE_ROOM]		 : [ userRoles.MODERATOR ]
	},
	// Array of permissions. If no peer with the permission in question
	// is in the room, all peers are permitted to do the action. The peers
	// that are allowed because of this rule will not be able to do this 
	// action as soon as a peer with the permission joins. In this example
	// everyone will be able to lock/unlock room until a MODERATOR joins.
	//allowWhenRoleMissing : [ CHANGE_ROOM_LOCK ],
	// When truthy, the room will be open to all users when as long as there
	// are allready users in the room
	activateOnHostJoin   : false,
	// When set, maxUsersPerRoom defines how many users can join
	// a single room. If not set, there is no limit.
	// maxUsersPerRoom    : 20,
	// Room size before spreading to new router
	routerScaleSize      : 40,
	// Socket timout value
	requestTimeout       : 20000,
	// Socket retries when timeout
	requestRetries       : 3,
	// Mediasoup settings
	mediasoup            :
	{
		numWorkers : Object.keys(os.cpus()).length,
		// mediasoup Worker settings.
		worker     :
		{
			logLevel : 'warn',
			logTags  :
			[
				'info',
				'ice',
				'dtls',
				'rtp',
				'srtp',
				'rtcp'
			],
			rtcMinPort : 40000,
			rtcMaxPort : 49999
		},
		// mediasoup Router settings.
		router :
		{
			// Router media codecs.
			mediaCodecs :
			[
				{
					kind      : 'audio',
					mimeType  : 'audio/opus',
					clockRate : 48000,
					channels  : 2
				},
				{
					kind       : 'video',
					mimeType   : 'video/VP8',
					clockRate  : 90000,
					parameters :
					{
						'x-google-start-bitrate' : 1000
					}
				},
				{
					kind       : 'video',
					mimeType   : 'video/VP9',
					clockRate  : 90000,
					parameters :
					{
						'profile-id'             : 2,
						'x-google-start-bitrate' : 1000
					}
				},
				{
					kind       : 'video',
					mimeType   : 'video/h264',
					clockRate  : 90000,
					parameters :
					{
						'packetization-mode'      : 1,
						'profile-level-id'        : '4d0032',
						'level-asymmetry-allowed' : 1,
						'x-google-start-bitrate'  : 1000
					}
				},
				{
					kind       : 'video',
					mimeType   : 'video/h264',
					clockRate  : 90000,
					parameters :
					{
						'packetization-mode'      : 1,
						'profile-level-id'        : '42e01f',
						'level-asymmetry-allowed' : 1,
						'x-google-start-bitrate'  : 1000
					}
				}
			]
		},
		// mediasoup WebRtcTransport settings.
		webRtcTransport :
		{
			listenIps :
			[
				// change 192.0.2.1 IPv4 to your server's IPv4 address!!
				{ ip: '161.53.3.177', announcedIp: null }

				// Can have multiple listening interfaces
				// change 2001:DB8::1 IPv6 to your server's IPv6 address!!
				// { ip: '2001:DB8::1', announcedIp: null }
			],
			initialAvailableOutgoingBitrate : 1000000,
			minimumAvailableOutgoingBitrate : 600000,
			// Additional options that are not part of WebRtcTransportOptions.
			maxIncomingBitrate              : 1500000
		}
	}
	// Prometheus exporter
	/*
	prometheus: {
		deidentify: false, // deidentify IP addresses
		numeric: false, // show numeric IP addresses
		port: 8889, // allocated port
		quiet: false // include fewer labels
	}
	*/
};
```
We have 3 servers in a cluster, and are using develop branch some 2 weeks old (with b7f07dcce9466204a901122dc881bc58af28b250 revision).

Has anyone experienced this kind of problem and how to fix it?

Best,
Zvonko

**Comment by Astagor** [comment]
I do not see a photo attached.

**Comment by zmartinovic** [comment]
![edumeet-problem](https://user-images.githubusercontent.com/8968916/111966491-44c13500-8af7-11eb-9b27-ef7ae323abbf.jpg)

Sorry, forgot to upload :)

**Comment by zmartinovic** [comment]
Ok, one user informed us that he had the same problem, only with 12 users. If one user exits the meeting, other one can join. Is there maybe routing problem?

**Comment by Astagor** [comment]
This is very strange, as the only option in the software that limits the number of people in the room is maxUsersPerRoom. But if set, the users get a notice that the room is full. On one of my servers I have currently a room with 37 users in it.
What is your CPU load? Is there a mediaSoup worker near 100% when this happens?

**Comment by so010** [comment]
Can you reduce routerScaleSize to eg. 10 and see if this affects number of max participants until this problem occurs?

**Comment by so010** [comment]
Looks like your router up-scaling is not working - you are sure you use an unmodified develop branch?

**Comment by zmartinovic** [comment]
@Astagor load is almost none. We have 8 (virtual) CPUs on each server and the load in not worth mentioning. @so010 yes, we will try and reduce routerScaleSize to see what happens and let you know. And yes, we are using unmodified develop branch. Only thing we had custom is logging number of current peers and rooms to Zabbix from StatusLogger class, but commented it out to make sure it's not making problems just for sure. But the problem remained. We have dev machine with the same setup so we will try to set smaller routerScaleSize there first.

**Comment by Astagor** [comment]
And you have 8  mediasoup-workers running? ps -aux | grep mediasoup
If there is no mediasoup-worker process in top reaching 100%, it is not a problem of routerScaleSize. Make sure you look at the load per mediasoup-worker, not the total load of the machine, as if the total load is by 12.5% it could already mean that 1 worker is at 100% of a core.

**Comment by zmartinovic** [comment]
Right now if I run it on one of the servers I get:
ps -aux | grep mediasoup
nobody    6799  0.1  0.2  41932 21224 ?        Sl   09:37   0:10 /usr/local/src/edumeet/server/node_modules/mediasoup/worker/out/Release/mediasoup-worker --logLevel=warn --logTag=info --logTag=ice --logTag=dtls --logTag=rtp --logTag=srtp --logTag=rtcp --rtcMinPort=40000 --rtcMaxPort=49999
nobody    6801  0.2  0.2  46092 23292 ?        Sl   09:37   0:25 /usr/local/src/edumeet/server/node_modules/mediasoup/worker/out/Release/mediasoup-worker --logLevel=warn --logTag=info --logTag=ice --logTag=dtls --logTag=rtp --logTag=srtp --logTag=rtcp --rtcMinPort=40000 --rtcMaxPort=49999
nobody    6803  0.0  0.1  35028 12464 ?        Sl   09:37   0:00 /usr/local/src/edumeet/server/node_modules/mediasoup/worker/out/Release/mediasoup-worker --logLevel=warn --logTag=info --logTag=ice --logTag=dtls --logTag=rtp --logTag=srtp --logTag=rtcp --rtcMinPort=40000 --rtcMaxPort=49999
nobody    6805  0.0  0.1  35028 10472 ?        Sl   09:37   0:00 /usr/local/src/edumeet/server/node_modules/mediasoup/worker/out/Release/mediasoup-worker --logLevel=warn --logTag=info --logTag=ice --logTag=dtls --logTag=rtp --logTag=srtp --logTag=rtcp --rtcMinPort=40000 --rtcMaxPort=49999
nobody    6807  0.0  0.1  35028 12464 ?        Sl   09:37   0:00 /usr/local/src/edumeet/server/node_modules/mediasoup/worker/out/Release/mediasoup-worker --logLevel=warn --logTag=info --logTag=ice --logTag=dtls --logTag=rtp --logTag=srtp --logTag=rtcp --rtcMinPort=40000 --rtcMaxPort=49999
nobody    6809  0.0  0.1  35028 12480 ?        Sl   09:37   0:00 /usr/local/src/edumeet/server/node_modules/mediasoup/worker/out/Release/mediasoup-worker --logLevel=warn --logTag=info --logTag=ice --logTag=dtls --logTag=rtp --logTag=srtp --logTag=rtcp --rtcMinPort=40000 --rtcMaxPort=49999
nobody    6811  0.0  0.1  35028 12408 ?        Sl   09:37   0:00 /usr/local/src/edumeet/server/node_modules/mediasoup/worker/out/Release/mediasoup-worker --logLevel=warn --logTag=info --logTag=ice --logTag=dtls --logTag=rtp --logTag=srtp --logTag=rtcp --rtcMinPort=40000 --rtcMaxPort=49999
nobody    6813  0.0  0.1  35028 12444 ?        Sl   09:37   0:00 /usr/local/src/edumeet/server/node_modules/mediasoup/worker/out/Release/mediasoup-worker --logLevel=warn --logTag=info --logTag=ice --logTag=dtls --logTag=rtp --logTag=srtp --logTag=rtcp --rtcMinPort=40000 --rtcMaxPort=49999
root     12244  0.0  0.0   6208   824 pts/0    S+   12:19   0:00 grep mediasoup

**Comment by Astagor** [comment]
OK, so 8 workers are running. What about TOP when the issue happens?

**Comment by zmartinovic** [comment]
Ok, so we have tested it again on our production and again after 19 users no one was able to enter. here is the load:
```
ps -aux | grep mediasoup
nobody    6799  0.1  0.2  41932 21224 ?        Sl   09:37   0:10 /usr/local/src/edumeet/server/node_modules/mediasoup/worker/out/Release/mediasoup-worker --logLevel=warn --logTag=info --logTag=ice --logTag=dtls --logTag=rtp --logTag=srtp --logTag=rtcp --rtcMinPort=40000 --rtcMaxPort=49999
nobody    6801  0.3  0.5  70800 48104 ?        Sl   09:37   0:32 /usr/local/src/edumeet/server/node_modules/mediasoup/worker/out/Release/mediasoup-worker --logLevel=warn --logTag=info --logTag=ice --logTag=dtls --logTag=rtp --logTag=srtp --logTag=rtcp --rtcMinPort=40000 --rtcMaxPort=49999
nobody    6803  0.0  0.1  35028 12464 ?        Sl   09:37   0:00 /usr/local/src/edumeet/server/node_modules/mediasoup/worker/out/Release/mediasoup-worker --logLevel=warn --logTag=info --logTag=ice --logTag=dtls --logTag=rtp --logTag=srtp --logTag=rtcp --rtcMinPort=40000 --rtcMaxPort=49999
nobody    6805  0.0  0.1  35028 10472 ?        Sl   09:37   0:00 /usr/local/src/edumeet/server/node_modules/mediasoup/worker/out/Release/mediasoup-worker --logLevel=warn --logTag=info --logTag=ice --logTag=dtls --logTag=rtp --logTag=srtp --logTag=rtcp --rtcMinPort=40000 --rtcMaxPort=49999
nobody    6807  0.0  0.1  35028 12464 ?        Sl   09:37   0:00 /usr/local/src/edumeet/server/node_modules/mediasoup/worker/out/Release/mediasoup-worker --logLevel=warn --logTag=info --logTag=ice --logTag=dtls --logTag=rtp --logTag=srtp --logTag=rtcp --rtcMinPort=40000 --rtcMaxPort=49999
nobody    6809  0.0  0.1  35028 12480 ?        Sl   09:37   0:00 /usr/local/src/edumeet/server/node_modules/mediasoup/worker/out/Release/mediasoup-worker --logLevel=warn --logTag=info --logTag=ice --logTag=dtls --logTag=rtp --logTag=srtp --logTag=rtcp --rtcMinPort=40000 --rtcMaxPort=49999
nobody    6811  0.0  0.1  35028 12408 ?        Sl   09:37   0:00 /usr/local/src/edumeet/server/node_modules/mediasoup/worker/out/Release/mediasoup-worker --logLevel=warn --logTag=info --logTag=ice --logTag=dtls --logTag=rtp --logTag=srtp --logTag=rtcp --rtcMinPort=40000 --rtcMaxPort=49999
nobody    6813  0.0  0.1  35028 12444 ?        Sl   09:37   0:00 /usr/local/src/edumeet/server/node_modules/mediasoup/worker/out/Release/mediasoup-worker --logLevel=warn --logTag=info --logTag=ice --logTag=dtls --logTag=rtp --logTag=srtp --logTag=rtcp --rtcMinPort=40000 --rtcMaxPort=49999
moodle   12482  0.0  0.0   6208   896 pts/1    S+   12:32   0:00 grep mediasoup
```
![edumeet-top](https://user-images.githubusercontent.com/8968916/111984332-8b208f00-8b0b-11eb-843e-66ab4dba4950.jpg)

**Comment by Astagor** [comment]
Can you send me a linkt to a room with 19 users, so I can see the logs of my browser when the error occurs while trying to join?

**Comment by zmartinovic** [comment]
Uh we need to schedule this sincer it's not that easy to simulate 20 users so I need my colleagues to join at the same time so that we make 20 connections. We can do it today at 14:30 CET if it's ok with you.

**Comment by zmartinovic** [comment]
Btw we have tried routerScaleSize set to 10 on our test servers and the result is the same - 19 users can enter and that's it. since this is test environment no one else can be using it so it was 19 total in just one room running on the server.

**Comment by Astagor** [comment]
OK, I can be online 14:30 CET, but you can also open like multiple tabs in you browser, so you do not need 19 people.

**Comment by zmartinovic** [comment]
Haha ok, I will try if it doesn't crash my browser (and it dose tend to do that). We usually have 4 people each open a few and in different browsers for testing. URL is https://meet.srce.hr/edumeet-test so see you there at 14:30 CET :) 

Thanks :)

**Comment by zmartinovic** [comment]
@Astagor I don't know if you were able to test, but we tried it again and same thing. 19 users were able to join and all users after that would not be able to enter. If I leave page after I click join button, I would end up in empty room but server would reconnect me soon after

**Comment by Astagor** [comment]
Well, yes and no, it was as if your server was totally overloaded on the signaling level. I got these in the logs:
![image](https://user-images.githubusercontent.com/11389003/111998759-9cbe6280-8b1c-11eb-8f23-58f6354fd77f.png)

Do you use an nginx or apache in front of edumeet?

**Comment by zmartinovic** [comment]
Same here:
![edumeet-test](https://user-images.githubusercontent.com/8968916/111999314-240bd600-8b1d-11eb-9d90-80561f87af95.jpg)
But on the server side everything is flat, not load of any kind.

We use Haproxy as LB.

**Comment by Astagor** [comment]
Hmm, the HAproxy stuff I have never tested, but I would say it might be it. I have only single server instances and just joined a room 22 times from my browser without problems.

**Comment by so010** [comment]
HAproxy we havn't tested yet with develop. Can you post your conf?

**Comment by so010** [comment]
Try to change `maxconn 20` parameter in HAProxy conf

**Comment by zmartinovic** [comment]
Hell, just looked at HAProxy config and yes, we did have 20 connections limit -_-
server meet01.srce.hr 161.53.3.177:80 check maxconn 20 verify none

Even on our Moodle servers we have 300 connections, so it was a mistake on our part. Tomorrow we will test with a new maxconn settings and will let you know. Thanks @Astagor and @so010 for your help :)

**Comment by so010** [comment]
@zmartinovic since we didn't tested HAProxy setup on develop-branch with auth/login - please share with us your experience! Please publish your resiults on  https://github.com/edumeet/edumeet/discussions

**Comment by zmartinovic** [comment]
@so010 sure, I've posted a reply :)
