### ISSUE TITLE
Option of not allowing participants to unmute themselves

### ISSUE THREAD

**Issue by Alex-YddeR** [edumeet/edumeet#735]
There should be a option to not Allow participants to unmute themselves. Moderator can give access to unmute to individual or all participants upon request 

Thanks

**Comment by so010** [comment]
Suggestions for how this could look like in UI?

"Moderator actions" could be replaced by:
"Room permissions":
- [ ] everybody can talk  
- [ ] everybody can send video
- [ ] everybody can share screen

and in the end a MUTE ALL MEDIA - button

**Comment by Astagor** [comment]
I'm not sure if this is a good idea to have. I think that we should not limit the user unmuting. Currently, the moderator can mute a participant and he can tell him to unmute only if he wants to say something. If the participant does not listen, it is a malicious behavior, so the moderator should kick kim out of the room. I think that giving a 4th way of muting  will cause that nobody will understand how it works (we have: 1. mute for myself, 2. mute for all, 3. Mute all for all). Maybe there should be a separate "layout" with TV like production features, where 1 GOD-Moderator controls all audio and video streams.

**Comment by so010** [comment]
Yeah, that's why I asked ;-)
But you've never been in a "Zoom bombed" meeting - I suppose? Could be difficult to fight as moderator against robots muting / unmuting all the time in a >100 participant meeting.
School teachers could wish such option as well - I think.

In order to NOT make it more difficult for the moderator I would like to replace "Moderator actions" - section by "Room permissions".

**Comment by Alex-YddeR** [comment]
That’s correct also In a large conference session where trainer/teacher is teaching the students, if one or some of the random students unmute by mistake it will disturb the whole session. 

I also had an experience where students will share the link to other users who are non invitees can also login and make the session problematic.Since some students also log in with guest names keep wrong messages in chat and make the session more problematic 

so I would suggest there should be nee menu item for the role moderator as security 
where we can have all these buttons

- Everybody can talk
- Everybody can send video
- Everybody can send screenshare
- Everybody can chat
- Everybody can file share

Also when above security option is enabled if someone asks the option of unmute or screenshare moderator should have option of giving access to only that user instead of enabling for all the users like enabling users into lobby.

**Comment by Astagor** [comment]
@so010 but I think we have this fictionally, roles. I will show you an extension I have made for TV production and maybe based on this we can work on a concept.

**Comment by Alex-YddeR** [comment]
This option is very important in schools and large webinars/events and also its add up security. 
![Screenshot 2021-03-23 at 12 31 40 PM](https://user-images.githubusercontent.com/65006646/112106724-0d748600-8bd4-11eb-91e1-ec4dd12a1888.png)

**Comment by so010** [comment]
> @so010 but I think we have this fictionally, roles. I will show you an extension I have made for TV production and maybe based on this we can work on a concept.
Yes, I know the roles are there but a consistent GUI is missing and yes let's work out a concept. The picture from @Alex-YddeR is the security menu directly available with 1-click from main window in Zoom which is a really nice concept with only some flaws.

**Comment by zmartinovic** [comment]
This is on a trace of https://github.com/edumeet/edumeet/issues/738 I've just posted. I like Adobe Connect solution for this. In Adobe Connect you can enable certain rights for participants, you can autopromote participants to presenters or you can grant specific rights to one or multiple participants via user list (attendees pod).

**Comment by ramansss** [comment]
Hi All,
Any update about this feature?
How can we enable it?
