### ISSUE TITLE
ScreenShare Button Disabled on MAC Safari 14.03

### ISSUE THREAD

**Issue by Alex-YddeR** [edumeet/edumeet#749]
Hi,

Not able to do screen-share from safari since button is in disabled state
Safari Version: Version 14.0.3 (16610.4.3.1.4)
MacOS : MacOS Big Sur Version 11.2

Edumeet Branch: Develop

Thanks
Alex

**Comment by Astagor** [comment]
Did you check in the system settings that Safari b can record screen?

**Comment by Alex-YddeR** [comment]
Yes, both screen recording and accessibility are enabled for safari under privacy settings. but still i cannot share the screen from safari.

![Screenshot 2021-03-31 at 9 06 32 AM](https://user-images.githubusercontent.com/65006646/113087051-76758280-9200-11eb-99c5-ceee3d428c66.png)

![Screenshot 2021-03-31 at 9 06 43 AM](https://user-images.githubusercontent.com/65006646/113087046-74132880-9200-11eb-8de2-332661ff27d6.png)

**Comment by dharmeshmaniar** [comment]
Hi,

The problem is in app/src/ScreenShare.js on line 240 where comparison of version is done.
In safari the decimal point comparison does not work. like > 13.0
What I did was to split the device.version and take only major version for comparison.
After that it allowed screenshare option in Safari 14. 

Changed Code snippet:
export default class ScreenShare
{
        static create(device)
        {
                var ver = device.version.split(".");
                if (isElectron() && electron)
                        return new ElectronScreenShare();
                else if (device.platform !== 'desktop')
                        return new DefaultScreenShare();
                else
                {
                        switch (device.flag)
                        {
                                case 'firefox':
                                {
                                        if (ver[0] < 66)
                                                return new FirefoxScreenShare();
                                        else
                                                return new DisplayMediaScreenShare();
                                }
                                case 'safari':
                                {
                                        if (ver[0] >= 13)
                                                return new DisplayMediaScreenShare();
                                        else
                                                return new DefaultScreenShare();
                                }
                                case 'chrome':
                                case 'chromium':
                                case 'opera':
                                case 'edge':
                                {
                                        return new DisplayMediaScreenShare();
                                }
                                default:
                                {
                                        return new DefaultScreenShare();
                                }
                        }
                }
        }
}

**Comment by Alex-YddeR** [comment]
This is working with new safari browser now.

Thanks
