### ISSUE TITLE
Local test is impossible

### ISSUE THREAD

**Issue by DanteIka** [edumeet/edumeet#755]
GET https://localhost:3443/socket.io/?peerId=dlrfs8m8&roomId=k6tbbiwr&EIO=3&transport=polling&t=NYBxcAI net::ERR_CONNECTION_REFUSED

I got this error when I try to join the room in the local development environment.

What is the reason? I can't go now

**Comment by vpalmisano** [comment]
Try looking for errors in the edumeet server logs using:
```docker-compose logs -f  edumeet```

**Comment by hkizilhan** [comment]
Seems like SSL certificate problem to me...
Browsers no longer allow self-signed certificates if not properly configured.
I suggest  https://mkcert.dev/

**Comment by vpalmisano** [comment]
You can visit the :8443 url first, accepting the certificate exception, and then you can visit the :3443 endpoint.
