### ISSUE TITLE
Firefox Screen-Share 

### ISSUE THREAD

**Issue by Alex-YddeR** [edumeet/edumeet#761]
Dear Team,

when we click on screen-share on Firefox and somehow i did not allowed the popup in the first time. Next time again when i click on the screen-share it gives an **error occurred message.** 
refreshing and joining back works. my question here, is it how it works with firefox or we need to fix it.

Thanks

**Comment by Astagor** [comment]
It seems a FF issue, when the user dismissed the screen sharing dialog the first time, it never show again and FF assumes the user did not give permission to the website to screen share. We get "DOMException: The request is not allowed by the user agent or the platform in the current context". I do not see now how to fix it.
