### ISSUE TITLE
update socket.io

### ISSUE THREAD

**Issue by alangecker** [edumeet/edumeet#762]
Because I had some stability issues with the socket.io connections, I looked into the socket handling and have seen that quite outdated packages are in use for that.

| Package | In use | Latest
|-------------|----------|-----------|
|socket.io | `2.4.1` | `4.0.1`
|socket.io-client | `2.4.0` | `4.0.1`
|express-socket.io-session | `1.3.5` |  no release since 3 years

Due to incompatibilities it is not possible to simple switch to a newer version, some changes must be done.

Here is a simple example on how to combine socket.io 4 with express and passport:
https://github.com/socketio/socket.io/blob/master/examples/passport-example/index.js

**Comment by havfo** [comment]
Done in new client/server
