### ISSUE TITLE
Issue with video mute with keyboard letter V

### ISSUE THREAD

**Issue by Alex-YddeR** [edumeet/edumeet#765]
Dear Team,

When a user try to press the keyboard letter **V**  continuously ( by pressing letter **v** very fast ) with out waiting for the camera state to get enable or disable. now user cannot mute the video anymore and he needs to restart the session.
Could not verify the same with audio mute with letter **M**

Thanks

**Comment by roman-drozd-it** [comment]
Yes, confirmed.

**Comment by roman-drozd-it** [comment]
Additional information: This is not the case for very quick multiple **clicking** the camera button.

**Comment by havfo** [comment]
Fixed in new client
