### ISSUE TITLE
its not really an issue but issue/request, stereo audio

### ISSUE THREAD

**Issue by geekositalia** [edumeet/edumeet#766]
Hi, im jo boschetti from geekos daw, opensuse project for professional audio. I believe that this software is the best for streaming and teaching, many people have asked me for stereo videoconferencing to work in the audio branch as it is done with zoom (not in real time), I would be proud to present this project, for this type of use , but in addition to deactivating the filters, the possibility of making the room stereo is required, and allowing users to choose stereo or mono audio, have you thought of a similar feature?

**Comment by so010** [comment]
Move to discussions ...
