### ISSUE TITLE
Meeting conducting consuming alot of data for many users.

### ISSUE THREAD

**Issue by callmemonky** [edumeet/edumeet#774]
Can we do something about this?

**Comment by Alex-YddeR** [comment]
You need to explain the scenario example like Server OS and it’s config, Server Resources, No of users,  Browser and its  version LastN config etc

with out any proper scenario no one can do something about this

**Comment by callmemonky** [comment]
LastN = 100
MobileLastN = 100
Server Config
NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
Memory - 16gb
Browser Used - Chrome

**Comment by so010** [comment]
https://github.com/edumeet/edumeet/issues/773

**Comment by so010** [comment]
Decrease LastN under 20 and MobileLastN not above 4
