### ISSUE TITLE
Find a better solution for handling config files

### ISSUE THREAD

**Issue by alangecker** [edumeet/edumeet#783]
currently during build steps we are copying config files to multiple places:

#### frontend config locations
- `app/public/config/config.js` (default place)
- `app/build/config/config.js` (by frontend `yarn build`)
- `server/public/config/config.js` (by frontend `yarn build`)
- `server/dist/public/config/config.js` (by backend `yarn build`)

#### backend config locations
- `server/config/config.js` (default place)
- `server/dist/config/config.js` (by backend `yarn build`)

this will definitely lead to mistakes:
- people think they made a change, but it is not applied due to the wrong file
- changes in the wrong place get overwritten
- build steps necessary to propagate config changes

**Comment by roman-drozd-it** [comment]
I had a similar problem/mistake several times ;-)

What we could do to partially reduce the problem what comes to my mind now is:
- minify the build's configs
- comment at the beginning of build's config files like "Don't modify anything here_ bla bla bla" with path to the real config file
- put a file named like "DON'T MODIFY ANYTHING HERE" in build folders

**Comment by alangecker** [comment]
another partial solution could be to have the public path customizeable, so that we could also set it to the frontend dist folder directly per default:

```js
  publicPath: path.join(__dirname, '../../app/build/`)
```

**Comment by roman-drozd-it** [comment]
PR #888 

> * `app/build/config/config.js` (by frontend `yarn build`)

`app/build` doesn't exist anymore (moving instead of copying)

> * `server/public/config/config.js` (by frontend `yarn build`)

`server/public` doesn't exist anymore at this level (moved to `/server/dist/public`)

> * `server/dist/public/config/config.js` (by backend `yarn build`)

`server/dist/public` is now a folder not a link

> * `server/dist/config/config.js` (by backend `yarn build`)

added a warning file inside `/server/dist`
