### ISSUE TITLE
Quiet Noise on Headphones even all participants muted

### ISSUE THREAD

**Issue by Alex-YddeR** [edumeet/edumeet#784]
Dear Team,

we can hear a quite noise even all the participants muted there local MIC, as i am on headphone its quite noticeable noise
we are 4 people in session

Thanks

**Comment by Alex-YddeR** [comment]
Will get this tested again since i am not able to reproduce until that closing the isssue.

Thanks

**Comment by vpalmisano** [comment]
@so010 maybe we can move this to discussions, since it is an issue we have already experienced.
My idea is that it could be related to this: https://mediasoup.discourse.group/t/what-is-the-benefit-of-zerortponpause-if-i-pause-resume-producers-often/2703

**Comment by so010** [comment]
Since it is confirmed but not reproducible we should hold the issue open and try to gather more information. 
And since this really an issue it should stay as that. Otherwise we should be more aggressive with moving "not issues" to discussions.

**Comment by so010** [comment]
> My idea is that it could be related to this: https://mediasoup.discourse.group/t/what-is-the-benefit-of-zerortponpause-if-i-pause-resume-producers-often/2703

But we don't set zeroRtpOnPause=true anywhere.
My guess is that we have a race condition with enabling/disabling microphones and sometimes there is still one mic sending. Could be an unconnected microphone port. We had already experienced that someone sent audio in even so the mic was muted on sender side.

**Comment by varundabke** [comment]
I also experience this issue some times. Will record the sound if possible next time :)

**Comment by so010** [comment]
This mainly occurs while using the "voice activated unmute" functionality and I manage to reproduce it somehow, updating to last mediasoup should fix this. https://github.com/versatica/mediasoup-client/pull/180#issuecomment-924993691

As long as the transport for paused audio-streams is not stopped, there is generated artificial noise based on last received noise level.
