### ISSUE TITLE
TURN config using shared secret

### ISSUE THREAD

**Issue by suuchan** [edumeet/edumeet#789]
I have set up edumeet-docker successfully with a turn server with long-term secrets (user/pass). I do not see how I can configure it with a turn server that uses short-lived credentials generated by REST using a shared secret. I read the conversation in issue #251 but still fail to see where I can configure the REST URL or the shared secret.

Is there any documentation available or is this feature still missing in the master branch of edumeet as of today?

**Comment by misi** [comment]
If you have eduID/eduGain auth then goto turn.geant.org and use the service.
If you are outside see the https://github.com/edumeet/eduturn-restapi https://github.com/edumeet/eduturn-ansible to understand howto setup your own REST api

**Comment by roman-drozd-it** [comment]
No response for more than 1 month. Seems to be resolved.
