### ISSUE TITLE
Issue with mute remote video

### ISSUE THREAD

**Issue by Alex-YddeR** [edumeet/edumeet#795]
Dear Team,

There are 5 or 10 Participants in the session with LastN 10. There is no moderator in the session.
Now as a normal user when i mute any of the remote video it gets automatically activated again for me the moment he starts speaking. 
Is this the bug or it works like that.

Thanks
Alex

**Comment by so010** [comment]
Sound like a bug but I can't reproduce.
Just to make sure: You talking about "muting" the video not the audio and then video comes back when participant starts speaking?
All the muting of remote participants audio / video is not absolute so when remote participant mutes himself and then unmutes the audio/video will be reactivated for you.

**Comment by Alex-YddeR** [comment]
Will test this on https://letsmeets.no once and update again.

Scenario is as below

5 Participants in a session

user 1 mutes video of user 3 and user 4 locally to himself only, now when users starts speaking all the videos muted to user1 gets activated automatically.


Thanks

**Comment by Alex-YddeR** [comment]
It can easily reproducible  in letsmeet also.

we are 3 participants in the session, all are normal users.

Now user1 Muted User2 and User3 Video locally for him, now when both user2 and user3 start speaking at the same time videos of user2 and user3  gets unmuted automatically to user1


https://user-images.githubusercontent.com/65006646/115845032-14deb780-a43e-11eb-8b1c-d6b0e376d56c.mp4

Thanks
