### ISSUE TITLE
Video frame frozen for some users

### ISSUE THREAD

**Issue by varundabke** [edumeet/edumeet#796]
In a 20+ people meeting, I am audible to everyone. 
But for some ( 4 to 5 participants) , my video frame is frozen forever (some cases, it recovers after very long gap).
I am able to speak to these 4/5 people, I can also see their video properly.

While this was happening, I tried to pause my camera video and resumed it back - yet they were still seeing my stuck frame.

This is really bringing the meeting experience down.

What is the solution for this?  

Thanks in advance.

**Comment by varundabke** [comment]
Additional input:
When the frame is frozen, the advance mode shows STLCurrent both as empty.
When it gets restored to a value, it does start showing stream again.

**Comment by havfo** [comment]
This means you are bandwidth constrained. We need to handle this case.
