### ISSUE TITLE
Fallback to ICE relay

### ISSUE THREAD

**Issue by Astagor** [edumeet/edumeet#805]
Is there a way that we detect that media is blocked by a firewall and then fallback to using turn relay?

**Comment by so010** [comment]
It should happen automatically inside the browser if TURN is configured. In Firefox we always use TURN relay.

**Comment by Astagor** [comment]
ok, I will check. I have moved my TURN servers to 443, so I will see if this helps.

**Comment by vpalmisano** [comment]
You could look at chrome://webrtc-internals checking the type of the remote candidate (https://developer.mozilla.org/en-US/docs/Web/API/RTCIceCandidateType)

**Comment by misi** [comment]
It happens automatically. If iceConnectionState goes to failed we can make an iceRestart. 

See the note..
 https://w3c.github.io/webrtc-pc/#dom-rtcofferoptions-icerestart
