### ISSUE TITLE
File transfer not working

### ISSUE THREAD

**Issue by Theoban** [edumeet/edumeet#806]
The file transfer function does not seem to be working. The recipient sees that a file is available and clicking on it shows the progress bar, but the file never arrives. No error messages.

We use the services at letsmeet.no and edumeet.geant.org with Chrome, Vivaldi and Firefox.

**Comment by volkankoc** [comment]
> The file transfer function does not seem to be working. The recipient sees that a file is available and clicking on it shows the progress bar, but the file never arrives. No error messages.
> 
> We use the services at letsmeet.no and edumeet.geant.org with Chrome, Vivaldi and Firefox.

It is these settings in the config.js file that does this. Try adding your own filetracker.
config.example.js in
`
// bittorrent tracker
	fileTracker  : 'wss://tracker.lab.vvc.niif.hu:443',
`

**Comment by cs91chris** [comment]
> 
> 
> Hi, same issue here. I have manually installed the latest release. I have my own working webtorrent server, and I replaced the hardcoded link in RoomClient.js with the mine. I have a working turn server too. All log are enabled, and no errors appear. I see from log that the magnet link of file are correctly generated but the new torrent are not announced to my tracker. Everything seems ok, but no file arrives.

I am facing the same issue with develop branch.

**Comment by roman-drozd-it** [comment]
You need to provide another tracker i.e. _wss://tracker.openwebtorrent.com_ [here](https://github.com/edumeet/edumeet/blob/master/server/config/config.example.js#L126), but of course, in your _config.js_ created from _config.example.js_ file.

It will be fixed soon in master and develop branches in _config.example.js_ template.

**Comment by roman-drozd-it** [comment]
Fixed as mentioned above. If you still have a problem, please reopen this issue.
