### ISSUE TITLE
Option to increase time in switching active speaker 

### ISSUE THREAD

**Issue by Alex-YddeR** [edumeet/edumeet#810]
Dear Team,

Is there any config to increase the active speaker detection time video switch between the speakers

Thanks

**Comment by havfo** [comment]
This is not exposed in any settings, but can be manually changed here: https://github.com/edumeet/edumeet/blob/90121d0fb65c2fe1f3daf8c477ad5c6501aff236/server/lib/Room.js#L223

That is time in milliseconds between the active speaker checks.
