### ISSUE TITLE
Fail to switch language to Chinese (Traditional) 

### ISSUE THREAD

**Issue by ray1422** [edumeet/edumeet#861]
When I switch language to Chinese (Traditional), it always switch to Chinese (**Simplified**). I guess it's related to  https://github.com/edumeet/edumeet/blob/707c486ba650d6cbc25c246fc2308b0f9d113140/app/src/translations/locales.js#L127
I'm on master branch

**Comment by roman-drozd-it** [comment]
Hi @ray1422, should be fixed now on develop branch and soon on master. Please test.
Thanks again.
