### ISSUE TITLE
Client Disconnecting with Error on server request 

### ISSUE THREAD

**Issue by Alex-YddeR** [edumeet/edumeet#862]
Dear Team,

Server: Ubuntu 18.04 LTS, 8vCPU, 16GB RAM Hosted on AWS 
In large meeting with 60 to 80 participants with default LASTN=5 for some users we are facing disconnections with error message Error on server request. 

Total no of peers on this server at this time with parallel other meetings : 100 to 110 Peers
**is it client side error or server?**

_Also how to calculate total no of consumers utilising on server._

Thanks
Alex

**Comment by so010** [comment]
What branch are you running?

**Comment by Alex-YddeR** [comment]
Develop Branch but not with the latest commit

**Comment by so010** [comment]
Where you see the error message? Can you include her the error message / log?

**Comment by nareshinstavc** [comment]
we see notification on browser as all the regular notifications in red alert. during this time client gets disconnected and connect back automatically. Since this is reported by multiple users i could not get a screenshot or log.

Do we get any logs on server for this kind of events? if yes how can we track it. 
we started the Service with PM2.

Thanks

**Comment by Alex-YddeR** [comment]
We see error message on browser like all other notifications in red alert, during this time client get disconnects from session and connect back automatically. since it is reported by other users i could not get screenshot or logs.

Is there any way we can get logs on server for these of events? If yes how can i enable it as we started service with PM2.

Also noticed when there is an issue in client network which has disconnected the session and when gets connected back it takes at-least 10 seconds to get audio from other users or to send audio which is observed in large meetings only and reported by multiple users.


Thanks

**Comment by Alex-YddeR** [comment]
> Also noticed when there is an issue in client network who has disconnected from the session and when gets connected back it takes at-least 10 seconds to get audio from other users or to send audio which is observed in large meetings only and reported by multiple users.

Even a new user who is joining to the meeting when there are already 50 participants joined, receiving audio takes at-least 10 seconds of time 

Thanks

**Comment by so010** [comment]
But after this 10 seconds audio is realtime or it is still delayed?

**Comment by Alex-YddeR** [comment]
I mean audio delay here has no audio from other users until 10 seconds after that it is seemless. 

It seems is it trying to subscribe all users and it is taking sometime to do so ?

No of visible videos for some users is 16 and default for all users is 5
 
Thanks

**Comment by Alex-YddeR** [comment]
Any one able to reproduce this delay in audio receiving when disconnected and join back in large meetings more than 40 users. 

This delay is some times more than 30 seconds

**Comment by Alex-YddeR** [comment]
Dear Team,

Anything on the above mentioned issue.

Thanks

**Comment by Astagor** [comment]
Hi, I have groups of students, usually 30-50 using edumeet, and nobody did report such a problem. Of course, now (July, August, September) the university has holidays, so currently I do not have such large groups. But in May and June there were no reports.

**Comment by Alex-YddeR** [comment]
Hi Astagor,

we have no problems with 50 users. problem starts when more users try to join like lets say more than 70.
we have done multiple meetings with 250 and 400 real users both got failed.

Thanks
Naresh

**Comment by havfo** [comment]
This will be fixed in the new client currently being developed in the edumeet-client repo.

**Comment by havfo** [comment]
Should be fixed in new client
