### ISSUE TITLE
Latest Develop Branch Issue.

### ISSUE THREAD

**Issue by Alex-YddeR** [edumeet/edumeet#864]
Hi, 

I just installed develop branch and finding the below issues as per the screenshots.

![Screenshot 2021-05-28 at 11 07 32 PM](https://user-images.githubusercontent.com/65006646/120022482-16396c00-c00a-11eb-8752-41613f14bef5.png)
![Screenshot 2021-05-28 at 11 07 48 PM](https://user-images.githubusercontent.com/65006646/120022490-189bc600-c00a-11eb-87bd-97eaedf19638.png)
 

And SEE THE CONFIGURATION DOCUMENTATION  is broken.

Thanks

**Comment by vpalmisano** [comment]
What is the error when visiting the /config page?
Anyway, the `defaultAudio` config has been removed.

**Comment by Alex-YddeR** [comment]
When visit to the page it’s white blank page with console errors as Syntax error: unexpected token <

**Comment by vpalmisano** [comment]
Can you share your config.js file? Are you trying the app build or the devel version?

**Comment by vpalmisano** [comment]
Fixed with https://github.com/edumeet/edumeet/pull/866

**Comment by nareshinstavc** [comment]
Below is the issue with new pull

config.js:154 Uncaught SyntaxError: Unexpected identifier
RoomClient.js:45 Uncaught TypeError: Cannot read property 'requestTimeout' of undefined
    at Object.180 (RoomClient.js:45)
    at f ((index):1)
    at Module.<anonymous> (index.js:1)
    at Module.279 (main.7442a069.chunk.js:1)
    at f ((index):1)
    at r ((index):1)
    at Array.t [as push] ((index):1)
    at main.7442a069.chunk.js:1

**Comment by Alex-YddeR** [comment]
Below error with new pull from develop branch

config.js:154 Uncaught SyntaxError: Unexpected identifier
RoomClient.js:45 Uncaught TypeError: Cannot read property 'requestTimeout' of undefined
    at Object.180 (RoomClient.js:45)
    at f ((index):1)
    at Module.<anonymous> (index.js:1)
    at Module.279 (main.7442a069.chunk.js:1)
    at f ((index):1)
    at r ((index):1)
    at Array.t [as push] ((index):1)
    at main.7442a069.chunk.js:1

**Comment by vpalmisano** [comment]
Can you share your app/public/config/config.js?

**Comment by Alex-YddeR** [comment]
Below is the config. i did not modified anything and i just used default template as it is under APP directory.

[config.txt](https://github.com/edumeet/edumeet/files/6570750/config.txt)

Thanks

**Comment by vpalmisano** [comment]
Please retry with the last commit on develop. It's safe to use a config.js like that:
```
var config = {};
```
Or containing only the properties that you need to customize.
