### ISSUE TITLE
"no Peer found"

### ISSUE THREAD

**Issue by callmemonky** [edumeet/edumeet#865]
We conducted a meeting of 120 participants, with lastN 12. Using a bug reporting service, constantly getting this error?
Any idea about this?

![image](https://user-images.githubusercontent.com/25193916/120060610-51718480-c076-11eb-853b-a2392d8a6153.png)

Supposedly, its coming from here

![image](https://user-images.githubusercontent.com/25193916/120060624-6d752600-c076-11eb-9928-c9f4f82fa552.png)

**Comment by so010** [comment]
This is not in our code base. You should contribute more in our project with your work - then we can solve your problems ;)

**Comment by roman-drozd-it** [comment]
No answer for a long time. Not related with our code base.
