### ISSUE TITLE
Highly Critical issue on MAC Safari

### ISSUE THREAD

**Issue by varundabke** [edumeet/edumeet#869]
![image](https://user-images.githubusercontent.com/8374300/120918628-f3c2e500-c6d2-11eb-8e5e-2397f6c90683.png)

Latest build on https://edumeet.geant.org/ fails to load on Safari on MAC - same case with latest build of my Dev instance - gives white screen with error.
I have an older build of the app on a client url ( not allowed to share publicly) - it works well in same safari. 

Please help!

Safari Version: 
![image](https://user-images.githubusercontent.com/8374300/120918883-6c767100-c6d4-11eb-9876-dc7890a23492.png)

Error on letsmeet.no
![image](https://user-images.githubusercontent.com/8374300/120920474-9a5fb380-c6dc-11eb-8883-fd9cb67c2132.png)

**Comment by ibc** [comment]
Don't mention me again, please.

**Comment by varundabke** [comment]
> Don't mention me again, please.

Edited. 
Is it working well on your Mac Safari's?

**Comment by Alex-YddeR** [comment]
It works on Version 14.1 (16611.1.21.161.6)

**Comment by varundabke** [comment]
> It works on Version 14.1 (16611.1.21.161.6)

Thanks Alex, what is the MAC OS version? I am trying on Mojave.

**Comment by Alex-YddeR** [comment]
> > It works on Version 14.1 (16611.1.21.161.6)
> 
> Thanks Alex, what is the MAC OS version? I am trying on Mojave.

11.3.1 (20E241) Big Sur

**Comment by roman-drozd-it** [comment]
seems to be solved.
