### ISSUE TITLE
mediasoup compile error after 'yarn' or 'npm install' command on develop branch.

### ISSUE THREAD

**Issue by hkizilhan** [edumeet/edumeet#876]
Following error occurring because there is no branch named '3.7.1-build-with-system-openssl'

...

-cpp/abseil-cpp/absl/synchronization/mutex.o
  CXX(target) /home/hakan/Desktop/edumeet/server/node_modules/mediasoup/worker/out/Release/obj.target/abseil/deps/libwebrtc/deps/abseil-cpp/abseil-cpp/absl/synchronization/internal/per_thread_sem.o
  CXX(target) /home/hakan/Desktop/edumeet/server/node_modules/mediasoup/worker/out/Release/obj.target/abseil/deps/libwebrtc/deps/abseil-cpp/abseil-cpp/absl/synchronization/internal/create_thread_identity.o
  CXX(target) /home/hakan/Desktop/edumeet/server/node_modules/mediasoup/worker/out/Release/obj.target/abseil/deps/libwebrtc/deps/abseil-cpp/abseil-cpp/absl/synchronization/internal/waiter.o
  CXX(target) /home/hakan/Desktop/edumeet/server/node_modules/mediasoup/worker/out/Release/obj.target/abseil/deps/libwebrtc/deps/abseil-cpp/abseil-cpp/absl/synchronization/internal/graphcycles.o
  CXX(target) /home/hakan/Desktop/edumeet/server/node_modules/mediasoup/worker/out/Release/obj.target/abseil/deps/libwebrtc/deps/abseil-cpp/abseil-cpp/absl/synchronization/barrier.o
../deps/libwebrtc/deps/abseil-cpp/abseil-cpp/absl/synchronization/internal/graphcycles.cc: In member function ‘void absl::synchronization_internal::GraphCycles::RemoveNode(void*)’:
../deps/libwebrtc/deps/abseil-cpp/abseil-cpp/absl/synchronization/internal/graphcycles.cc:450:26: error: ‘numeric_limits’ is not a member of ‘std’
  450 |   if (x->version == std::numeric_limits<uint32_t>::max()) {
      |                          ^~~~~~~~~~~~~~
../deps/libwebrtc/deps/abseil-cpp/abseil-cpp/absl/synchronization/internal/graphcycles.cc:450:49: error: expected primary-expression before ‘>’ token
  450 |   if (x->version == std::numeric_limits<uint32_t>::max()) {
      |                                                 ^
../deps/libwebrtc/deps/abseil-cpp/abseil-cpp/absl/synchronization/internal/graphcycles.cc:450:52: error: ‘::max’ has not been declared; did you mean ‘std::max’?
  450 |   if (x->version == std::numeric_limits<uint32_t>::max()) {
      |                                                    ^~~
      |                                                    std::max
In file included from /usr/include/c++/11.1.0/algorithm:62,
                 from ../deps/libwebrtc/deps/abseil-cpp/abseil-cpp/absl/synchronization/internal/graphcycles.cc:38:
/usr/include/c++/11.1.0/bits/stl_algo.h:3467:5: note: ‘std::max’ declared here
 3467 |     max(initializer_list<_Tp> __l, _Compare __comp)
      |     ^~~
At global scope:
cc1plus: note: unrecognized command-line option ‘-Wno-unknown-warning-option’ may have been intended to silence earlier diagnostics
make[1]: *** [deps/libwebrtc/deps/abseil-cpp/abseil.target.mk:152: /home/hakan/Desktop/edumeet/server/node_modules/mediasoup/worker/out/Release/obj.target/abseil/deps/libwebrtc/deps/abseil-cpp/abseil-cpp/absl/synchronization/internal/graphcycles.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/home/hakan/Desktop/edumeet/server/node_modules/mediasoup/worker/out'
make: *** [Makefile:25: default] Error 2
make: Leaving directory '/home/hakan/Desktop/edumeet/server/node_modules/mediasoup/worker'

**Comment by hkizilhan** [comment]
it's not a branch problem, sory.
But, there is a compilation issue. 
No error when tag removed.

**Comment by vpalmisano** [comment]
Try with gcc version 10.3.0. The problem seems related to some changes in gcc compiler (http://gcc.gnu.org/gcc-11/porting_to.html).

**Comment by hkizilhan** [comment]
> Try with gcc version 10. The problem seems related to some changes in gcc compiler (http://gcc.gnu.org/gcc-11/porting_to.html).

Confirmed, thanks...
