### ISSUE TITLE
iOS no Audio from other users until unmute mic

### ISSUE THREAD

**Issue by Alex-YddeR** [edumeet/edumeet#884]
Dear Team,

When iOS users join the session with mic mute by default, then there will be no audio from other users until unmute the mic. 

iOS users feel that there is no audio and it spoils the user experience. 
They need to unmute the mic then we get audio from others

Thanks
Alex

**Comment by Alex-YddeR** [comment]
Dear Team, 

This issue is happening with  some of the android mobile too. Mobile user wont here anything until mute and unmute back after login.

Thanks

**Comment by dinceremre** [comment]
any progress with this issue? apple users are struggling quite a lot

**Comment by Alex-YddeR** [comment]
Any fix on this? audio issue is having issues even on android sometimes.

**Comment by dinceremre** [comment]
fixed after ios 15 upgrade
