### ISSUE TITLE
not transfer file in Linux

### ISSUE THREAD

**Issue by galliaCodeWorld** [edumeet/edumeet#886]
Hello. 
I use edumeet in Linux. 
But I don't see download file.  Can you help me? https://178.62.253.150

![file-share-failed png](https://user-images.githubusercontent.com/86771168/126292053-5e050c52-059f-409f-92aa-eb870e8f8493.jpg)

**Comment by roman-drozd-it** [comment]
HI, the host doesn't seem to respond. The _File sharing_ should work proberly out of the box.
Additionally, you can also test a `develop` branch. There are many changes there including updated version of _File Sharing_.

**Comment by galliaCodeWorld** [comment]
thanks Roman.
I'd like you to kindly send me url of develop branch.
I hope to test the develop branch, really.

**Comment by roman-drozd-it** [comment]
When you `git clone git@github.com:edumeet/edumeet.git`
then `git checkout develop` and follow the instruction on
https://github.com/edumeet/edumeet/tree/develop

**Comment by galliaCodeWorld** [comment]
I'm happy to receive your message, thanks.
I'll try. all the best.

**Comment by roman-drozd-it** [comment]
I'm closing this issue, if any other problems related to it, please reopen it.
