### ISSUE TITLE
"too many WebMediaPlayers" intervention is breaking WebRTC functionality

### ISSUE THREAD

**Issue by dinceremre** [edumeet/edumeet#891]
Can we figure out a workaround for this chromium bug?

https://bugs.chromium.org/p/chromium/issues/detail?id=1232649#c87

**Comment by dinceremre** [comment]
weird that no one has encountered this.It screwed up almost every conferencing solution

**Comment by havfo** [comment]
The new client is conservative in the number of media elements it renders on screen. Should never be more than lastN video and the number of unmuted audio elements.
