### ISSUE TITLE
WKWebView Detected unsupported browser

### ISSUE THREAD

**Issue by Alex-YddeR** [edumeet/edumeet#912]
Hi,

we are trying to use edumeet embed in a iOS APP using WKWebView, when we try to load the URL it says detected unsupported browser. but same is working on safari browser.

Can you please let us know anything we need to change to support WKWebView

Thanks

**Comment by GergesEid** [comment]
I added this line of code and it will works fine with me.
Add it in viewDidLoad

myWKWebView.customUserAgent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36"

**Comment by GergesEid** [comment]
Hi @Alex-YddeR 

I added this line of code and it will works fine with me.
Add it in viewDidLoad

myWKWebView.customUserAgent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36"
