### ISSUE TITLE
Local recording disclaimer

### ISSUE THREAD

**Issue by N7Remus** [edumeet/edumeet#914]
Make local recording configurable in the config.js.
- [x] It shoud be disabled by default.
- [x] Make it role based too. 
- [x] It shoud display a disclaimer.
- [x] If the user doesn't accept it (changename, switch off media streams in recording) - Video.
- [x] If the user doesn't accept it (changename, switch off media streams in recording) - Audio.
- [x] Make the disclaimer work with multiple paralell recordings too (One consent for all recordings in the room).
- [x] hide screenshares too
- [x] Consent buttons are too close.
- [x] Do not show notification after notification is accepted.
- [x] Add translations
- [ ] Test

**Comment by roman-drozd-it** [comment]
Merged into develop. Closed.
