### ISSUE TITLE
Voice activated unmute Does not work when separate media controls enabled.

### ISSUE THREAD

**Issue by Alex-YddeR** [edumeet/edumeet#931]
Dear Team,

Voice activated unmute Does not work when separate media controls enabled. 

Thanks

**Comment by Astagor** [comment]
It works for me. Can you describe the test case?

**Comment by Alex-YddeR** [comment]
Please check with video. may be its with the UI issue.

https://user-images.githubusercontent.com/65006646/147077700-3e3437a1-b986-4b57-93dd-2216d920b330.mp4
