### ISSUE TITLE
Can not connect media stream on Flutter client

### ISSUE THREAD

**Issue by thothai94** [edumeet/edumeet#934]
I'm creating a Flutter client for edumeet base on mediasoup_flutter_client and socket_io_client. I have just successful joined in a meeting room. But I can not send and receive media stream (audio/video) between mobile client and server.
Can anyone can help me solve this issue?
Everyone can find my project here: https://github.com/thothai94/flutter-edumeet-client

**Comment by jack2992** [comment]
> I'm creating a Flutter client for edumeet base on mediasoup_flutter_client and socket_io_client. I have just successful joined in a meeting room. But I can not send and receive media stream (audio/video) between mobile client and server. Can anyone can help me solve this issue? Everyone can find my project here: https://github.com/thothai94/flutter-edumeet-client

I have the same issue.

**Comment by MinhCuongIT** [comment]
Any update for that?

**Comment by volkankoc** [comment]
> I'm creating a Flutter client for edumeet base on mediasoup_flutter_client and socket_io_client. I have just successful joined in a meeting room. But I can not send and receive media stream (audio/video) between mobile client and server. Can anyone can help me solve this issue? Everyone can find my project here: https://github.com/thothai94/flutter-edumeet-client

Are you continuing this project?
