### ISSUE TITLE
.deb packages not available anymore

### ISSUE THREAD

**Issue by L4ky** [edumeet/edumeet#935]
Hi, i see that job artifacts are expired so it's not possible anymore to download .deb packages.

Would it be possible to rebuild one of 3.4.0 version?

Thank you
Luca

**Comment by gitbot-v-21** [comment]
yes plz rebuild it!

the link on master and develop branches if broken!

**Comment by sd4v1d** [comment]
Action script repaired, and edumeet.deb artifact is created again. Is should be considered to add .deb file as release asset.
