### ISSUE TITLE
net::ERR_HTTP2_PROTOCOL_ERROR 200

### ISSUE THREAD

**Issue by piranna** [edumeet/edumeet#942]
After following install instructions from scratch, web app doesn't load and all requests get a `net::ERR_HTTP2_PROTOCOL_ERROR 200` error. Any clue why this can happen?

Node.js 17.3.1
Chrome 97.0.4692.71
Ubuntu Mate 21.10

**Comment by so010** [comment]
Could you try the actual release branch  with the install documentation there: 
https://github.com/edumeet/edumeet/tree/release-3.5.0

We don't support non LTS versions of node.js - but that does not mean it will not run. 
The master branch is definitely not working with node.js >= 15 but next major release 3.5.0 should work.

We tested with Node.js 13 14 15 16 and I think 17 should work too.

**Comment by piranna** [comment]
i've just checked it fails with node.js 17 & 18, but node.js 16 builds fine.

**Comment by piranna** [comment]
when / how it got completed? So far I tried it this week and it still didn't worked with Node.js 18...

**Comment by piranna** [comment]
when / how it got completed? So far I tried it this week and it still didn't worked with Node.js 18...

**Comment by piranna** [comment]
when / how it got completed? So far I tried it this week and it still didn't worked with Node.js 18...

**Comment by piranna** [comment]
when / how it got completed? So far I tried it this week and it still didn't worked with Node.js 18...

**Comment by havfo** [comment]
The new room server has fixed this error. No further development is happening on the old room server.
