### ISSUE TITLE
mute button - should not be disabled

### ISSUE THREAD

**Issue by Astagor** [edumeet/edumeet#949]
here it should not be disabled, but the whole tooltip should be micConsumer &&
https://github.com/edumeet/edumeet/blob/e3c1ccb492d6cb280a66bfaf2e12b3bd17a46103/app/src/components/Containers/Peer.js#L488
no if there is no audio stream the disabled button with the tooltip is shown
![image](https://user-images.githubusercontent.com/11389003/152233501-04b28d41-0274-47b0-a5ca-e4e3342fdee4.png)

**Comment by Astagor** [comment]
There are more errors now, if a peer mutes his mic the icon in the other peers does not turn red like before. However, when an admin mutes a peer for all, it does turn red. I think with your refactoring you have deleted some logic.

**Comment by roman-drozd-it** [comment]
1. solved, pushed into develop
2. it's works for me AFAIU what you mean, look below

https://user-images.githubusercontent.com/37835902/152269325-30bc5d5c-2524-4a4f-a4d1-d0339bf3b93e.mp4

**Comment by Astagor** [comment]
1. Thanks
2. true. It was just to late in the night. My mistake, sorry.
