### ISSUE TITLE
Click Join button can't enter the room

### ISSUE THREAD

**Issue by Sunshine-Qiu** [edumeet/edumeet#960]
I have seted up the window.navigator.language to be "en",but the console still show the error .If I click the Join button,the network will show Provisional headers are shown.In the edumeet source code,i have changed the mediasoup version into 2.6.19 because version of 3 i can't successfully npm install,and the redis version change to 4.0.3 so that when I npm start in the server there no error in the terminal.
![image](https://user-images.githubusercontent.com/60089252/154383371-a138a595-6e0e-456e-a463-cb7f925e77b2.png)
![image](https://user-images.githubusercontent.com/60089252/154383405-e4089e01-9fdf-40df-b32f-6d94b6161f65.png)
![image](https://user-images.githubusercontent.com/60089252/154384126-ef3b733e-aeba-4b77-8041-fbf30e158fad.png)
browsername:chrome
node.js version:13.7.0
npm:6.13.6
branch name:master

_Originally posted by @Emma-Qiu in https://github.com/edumeet/edumeet/issues/918#issuecomment-1042467739_

**Comment by roman-drozd-it** [comment]
Hi @Sunshine-Qiu, can you install and check the coming version https://github.com/edumeet/edumeet/tree/release-3.5.0, and let us know if you have the same problem?
Thanks.

**Comment by Sunshine-Qiu** [comment]
hi @roman-drozd-it  ,new version of edumeet I have download and change the branch to develop and run successfully in app, the network of /auth/check_login_status status show 200,but the console show the error in the first picture.
Because i can't successfully yarn in server , the errors are in the second picture.why the mediasoup version of 3 can't download but 2 can. 
how can i yarn in the server successfully,thank for u help.
![image](https://user-images.githubusercontent.com/60089252/154626860-38508742-96d2-4b93-ac28-f7dfb4463648.png)
![image](https://user-images.githubusercontent.com/60089252/154626502-ad03789f-c35b-4768-9306-364e7577ef74.png)

**Comment by Sunshine-Qiu** [comment]
hi @roman-drozd-it  ,new version of edumeet I have download and change the branch to develop and run successfully in app, the network of /auth/check_login_status status show 200,but the console show the error in the first picture.
Because i can't successfully yarn in server , the errors are in the second picture.why the mediasoup version of 3 can't download but 2 can. 
how can i yarn in the server successfully,thank for u help.
![image](https://user-images.githubusercontent.com/60089252/154626860-38508742-96d2-4b93-ac28-f7dfb4463648.png)
![image](https://user-images.githubusercontent.com/60089252/154626502-ad03789f-c35b-4768-9306-364e7577ef74.png)

**Comment by roman-drozd-it** [comment]
Can you try to install exacly `release-3.5.0` [Manual installation (build)](https://github.com/edumeet/edumeet/tree/release-3.5.0#manual-installation-build) step by step with exacly those dependencies?

Let me know what the result is.

**Comment by Sunshine-Qiu** [comment]
I flow the approach of Munual installation,when i yarn in the server,the terminal show the error in the first picture,i can't download the https://www.openssl.org/source/openssl-1.1.1l.tar.gz
![image](https://user-images.githubusercontent.com/60089252/154793187-1aa1a7f0-926a-419a-b27a-2bb071273c39.png)

**Comment by Astagor** [comment]
When I click the link I can download the file. What happens when you click the link? Where are you based?

**Comment by Sunshine-Qiu** [comment]
hi @Astagor ,when I click the link i can download the file too,But when i yarn in the terminal ,the console will show the error ,i don't know the reason,maybe something i din't set up correctly,so i can't go on the next step.I feel depressed and confused.

**Comment by sd4v1d** [comment]
Hi @Sunshine-Qiu, could you please provide information about your OS type & version? Could be some incompatibility issue.

I just tested manual installation instructions on minimal Linux OS (Debian stable) as base, and everything went OK. No errors. 
As @Astagor  and @roman-drozd-it  stated please use `release-3.5.0` branch, since `develop` branch is currently not synced with latest commits, so after cloning , run `git checkout release-3.5.0` and try to build.

Also if you could please try installation process described on my fork [README.md]( https://github.com/sd4v1d/edumeet/blob/release-3.5.0/README.md) (PR #957 currently under review before merged into original edumeet repository). I would appreciate if you could report back if you run on some inconsistency, missing or confusing instructions.

**Comment by Alex-YddeR** [comment]
Hi @Sunshine-Qiu, i can help you in deploying the app. please mail be directly on alexydder@gmail.com

Thanks

**Comment by so010** [comment]
https://stackoverflow.com/questions/42098126/mac-osx-python-ssl-sslerror-ssl-certificate-verify-failed-certificate-verify
