### ISSUE TITLE
Muted microphone becomes unmuted after connection drop and rejoin

### ISSUE THREAD

**Issue by so010** [edumeet/edumeet#964]
From community email list:
%%%
I have a problem with edumeet. The problem arises when someone has a poor connection and the connection is lost. After restoring the connection, the client enters the conference automatically with the microphone on. Interestingly, his microphone is marked in red, which suggests that it is turned off. Unfortunately, everyone can hear him. Before dropping the call, the microphone was turned off. My users are reporting the problem. I checked it out and it really is. The same happens not only on my servers but also on servers in other universities.
%%%

**Comment by Astagor** [comment]
I have fixed it in #963

**Comment by so010** [comment]
According to Barteck this is only in master branch but anyways closing this.
