### ISSUE TITLE
I'm getting cors error

### ISSUE THREAD

**Issue by Ramesh-php** [edumeet/edumeet#969]
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:3000/socket.io/?peerId=nn9glvgs&roomId=ekbb0ew9&EIO=3&transport=polling&t=Ny_XTAE. (Reason: CORS request did not succeed). Status code: (null).

**Comment by so010** [comment]
Please give us more context / information about server-OS, browser-version, what did you do for getting this error, ...
