### ISSUE TITLE
If build the app getting this error

### ISSUE THREAD

**Issue by Ramesh-php** [edumeet/edumeet#977]
D:\edumeet-master\app>yarn & yarn build
Search for the keywords to learn more about each warning.
To ignore, add // eslint-disable-next-line to the line before.

File sizes after gzip:

  245.95 KB (-5 B)  build\static\js\11.aefecf61.chunk.js
  168.51 KB (-3 B)  build\static\js\12.361af62b.chunk.js
  102.89 KB (-1 B)  build\static\js\main.be1f7440.chunk.js
  64.79 KB          build\static\js\13.4b7f9770.chunk.js
  38.23 KB          build\static\js\room.ee38ac4a.chunk.js
  20.13 KB          build\static\js\1.de2aa647.chunk.js
  18.49 KB (-1 B)   build\static\js\14.7fe00388.chunk.js
  6.73 KB           build\static\js\0.fe86bb42.chunk.js
  1.77 KB (-2 B)    build\static\js\runtime-main.bc9247f7.js
  1.32 KB           build\static\css\12.7c6c0c5f.chunk.css
  1.29 KB           build\static\js\file-saver.bc97249c.chunk.js
  1.11 KB           build\static\js\screensharing.c6454335.chunk.js
  421 B             build\static\js\app.c6314209.chunk.js
  355 B (-2 B)      build\static\css\main.a63fb4a9.chunk.css
  203 B             build\static\js\webtorrent.b512346c.chunk.js
  156 B             build\static\js\createtorrent.12a8b594.chunk.js
  141 B             build\static\js\socket.io.9bf69c83.chunk.js

The project was built assuming it is hosted at /.
You can control this with the homepage field in your package.json.

The build folder is ready to be deployed.
You may serve it with a static server:

  serve -s build

Find out more about deployment here:

  https://cra.link/deployment

'DEST' is not recognized as an internal or external command,
operable program or batch file.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command

**Comment by so010** [comment]
It will not install or build on Windows platform
