### ISSUE TITLE
if build the server side getting this error

### ISSUE THREAD

**Issue by Ramesh-php** [edumeet/edumeet#978]
D:\edumeet-master\server>yarn & yarn build
yarn install v1.22.17
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
[1/2] ⠠ bcrypt
error D:\edumeet-master\server\node_modules\mediasoup: Command failed.
Exit code: 1
Command: node npm-scripts.js postinstall
Arguments:
Directory: D:\edumeet-master\server\node_modules\mediasoup
Output:
npm-scripts.js [INFO] running task "postinstall"
npm-scripts.js [INFO] executing command: node npm-scripts.js worker:build
npm-scripts.js [INFO] running task "worker:build"
npm-scripts.js [INFO] executing command: make -C worker
make: Entering directory 'D:/edumeet-master/server/node_modules/mediasoup/worker'
# Updated pip and setuptools are needed for meson
# `--system` is not present everywhere and is only needed as workaround for
# Debian-specific issue (copied from
# https://github.com/gluster/gstatus/pull/33), fallback to command without
# `--system` if the first one fails.
python -m pip install --system --target=/d/edumeet-master/server/node_modules/mediasoup/worker/out/pip pip setuptools || \
        python -m pip install --target=/d/edumeet-master/server/node_modules/mediasoup/worker/out/pip pip setuptools || \
        echo "Installation failed, likely because PIP is unavailable, if you are on Debian/Ubuntu or derivative please install the python3-pip package"
/usr/bin/bash: python: command not found
/usr/bin/bash: line 1: python: command not found
Installation failed, likely because PIP is unavailable, if you are on Debian/Ubuntu or derivative please install the python3-pip package
# Install `meson` and `ninja` using `pip` into custom location, so we don't
# depend on system-wide installation.
python -m pip install --upgrade --target=/d/edumeet-master/server/node_modules/mediasoup/worker/out/pip  meson ninja
Makefile:57: recipe for target 'meson-ninja' failed
process_begin: CreateProcess(NULL, python -m pip install --upgrade --target=/d/edumeet-master/server/node_modules/mediasoup/worker/out/pip meson ninja, ...) failed.
make (e=2): The system cannot find the file specified.
make: *** [meson-ninja] Error 2
make: Leaving directory 'D:/edumeet-master/server/node_modules/mediasoup/worker'

yarn run v1.22.17
$ mkdir -p dist && find dist/* -maxdepth 0 ! -name public -exec rm -rf {} \; && tsc && ln -s ../certs dist/certs && chmod 755 dist/server.js && ( for fileExt in yaml json toml ; do [ -f config/config.$fileExt ] && cp config/config.$fileExt dist/config/; done ) | true && touch 'dist/ __AUTO_GENERATED_CONTENT_REFRESHED_AFTER_REBUILDING!__ '
fileExt was unexpected at this time.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command

**Comment by Astagor** [comment]
You are again building on Windows
D:/edumeet-master/server/node_modules/mediasoup/worker
We do not support Windows as an installation platform.
