### ISSUE TITLE
Device selection on the start page

### ISSUE THREAD

**Issue by mesutde** [edumeet/edumeet#983]
**device selection on the start page**
Hi.

If the microphone and audio device selection box on the setting screen at the bottom of the input area, the room name and room name on the start page are shown, we can change the device changes instantly.

**Sample:**
_Start Page Screen:_
1. Room Name
2. Your Name
3. **Select audio input device**
4. **Select audio output device**
5. **Select the audio preset**
6. **Select the camera preset**

And RealTime Test Audio/microphone bar.

i think it would be better this way

Thanks you.

**Comment by havfo** [comment]
This is being realized in the new client that is being worked on in the edumeet-client repo.
