### ISSUE TITLE
Trying to docker run build with 3.5.2 release fails

### ISSUE THREAD

**Issue by Ramesh-php** [edumeet/edumeet#985]
Step 16/32 : RUN npm run build --production
---> Running in 72406108318c

edumeet@3.5.2 build /opt/edumeet/app
react-scripts build && rm -rf ../server/public && DEST='../server/dist/public' && rm -rf $DEST && mkdir -p $DEST && mv -T build/ $DEST

Creating an optimized production build...
Failed to compile.

src/components/ConfigDocumentation.tsx
Line 1:1: Resolve error: typescript with invalid interface loaded as resolver import/no-duplicates
Line 1:1: Resolve error: typescript with invalid interface loaded as resolver import/extensions

src/components/ConfigError.tsx
Line 1:1: Resolve error: typescript with invalid interface loaded as resolver import/no-duplicates
Line 1:1: Resolve error: typescript with invalid interface loaded as resolver import/extensions

src/components/VideoContainers/AudioAnalyzer.ts
Line 1:1: Resolve error: typescript with invalid interface loaded as resolver import/no-duplicates
Line 1:1: Resolve error: typescript with invalid interface loaded as resolver import/extensions

src/config.ts
Line 1:1: Resolve error: typescript with invalid interface loaded as resolver import/no-duplicates

src/transforms/receiver.ts
Line 1:1: Resolve error: typescript with invalid interface loaded as resolver import/extensions
Line 1:1: Resolve error: typescript with invalid interface loaded as resolver import/no-duplicates

Search for the keywords to learn more about each error.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! edumeet@3.5.2 build: react-scripts build && rm -rf ../server/public && DEST='../server/dist/public' && rm -rf $DEST && mkdir -p $DEST && mv -T build/ $DEST
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the edumeet@3.5.2 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR! /root/.npm/_logs/2022-03-10T14_27_35_065Z-debug.log
ERROR: Service 'edumeet' failed to build: The command '/bin/sh -c npm run build --production' returned a non-zero code: 1
root@ubuntu-s-1vcpu-1gb-nyc1-01:/var/www/html/devopsmecca/edumeet-docker-master

**Comment by sd4v1d** [comment]
3.5.2 was not ready for docker build, please try with 3.5.3
