### ISSUE TITLE
Use ESM modules

### ISSUE THREAD

**Issue by piranna** [edumeet/edumeet#999]
Current code uses a mix of `require()` and `import` statements, but main problem is that TypeScript is configured to output CommonJS code instead of transpile to ESM modules. This makes it impossible to modify the code to use ESM-only modules.

I've tried multiple alternatives, including usage of dynamic `import()` of ESM modules, but transpilation converts them to `__importStar(require(...))`, so it's not working either. Only solutions I can think are:

- Change EduMeet Typescript configuration to transpile to ESM modules (ideal, and future proof)
- Update other projects to generate a CommonJS output in addition of an ESM one (unrealistic)

Not sure if this can be easily done, or should be set for the upcoming 4.0 version.

Bonus ball: `debug` package is disabled by default except if you define `DEBUG` environment variable, so nothing is logged in console and that error got silenced until I started adding traces directly in the transpiled code. A better alternative logging library should be found too.

**Comment by havfo** [comment]
There is now a new effort to modernize and rewrite edumeet code to typescript. See the edumeet-client and edumeet-room-server repos. The client is typescript from the ground up, and the room server will be next. There is a proposal for the next gen architecture here: ![edumeet-cloud.png](https://user-images.githubusercontent.com/920922/167262219-0295c7fd-8f0d-4b06-9738-20be675c18d6.png)

**Comment by piranna** [comment]
Great! Are you talking about https://github.com/edumeet/edumeet-client and https://github.com/edumeet/edumeet-room-server?

**Comment by havfo** [comment]
Yes, indeed. The names may change, but for now those are the new server and client repos.

**Comment by piranna** [comment]
Ok, thank you for the update :-)
